{
  "SOURCE": "AGT.lss",
  "COMMENT": "AGT module",
  "ARTIFACTS": [
    "AGT.INC",
    "AGT.html",
    "AGT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "AGT",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "AGT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "AGT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "AGT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402396799",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AGT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AGT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397363",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AGT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}