{
  "SOURCE": "AGT.lss",
  "COMMENT": "AGT module",
  "ARTIFACTS": [
    "AGT.INC",
    "AGT.html",
    "AGT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "AGT",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "AGT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "AGT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AGT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "AGT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402396799",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "9d0e9e1af770b18ad1a067574e55a6c5",
      "SIZE": 1971
    },
    {
      "NAME": "AGT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "4edf46b4ccfad010cc6a40f42a4aa811",
      "SIZE": 1326
    },
    {
      "NAME": "AGT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397363",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "e54605f13813f3729c88bbedc0e461af",
      "SIZE": 4400
    },
    {
      "NAME": "AGT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "a137177e7db9690e4a0a2293a2b865da",
      "SIZE": 281
    }
  ]
}