{
  "SOURCE": "AI.lss",
  "COMMENT": "AI module",
  "ARTIFACTS": [
    "AI.INC",
    "AI.html",
    "AI.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "AI",
  "DEPENDS": [
    "SEQ"
  ],
  "INSTALL": [
    {
      "TARGET": "AI.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AI.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AI.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "AI.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AI.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AI.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "AI.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402396821",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "07c6bee41faafdefa33ded84c38dc324",
      "SIZE": 2555
    },
    {
      "NAME": "AI.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "f669cad3071711258e43d2eff6b7ab40",
      "SIZE": 1442
    },
    {
      "NAME": "AI.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397363",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "f0d6a9e51e172a70c2501948b37b565b",
      "SIZE": 5469
    },
    {
      "NAME": "AI.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "4c77718aa6ab8f6d7b46128ca6323ea9",
      "SIZE": 586
    }
  ]
}