{
  "SOURCE": "ALL.lss",
  "COMMENT": "ALL module",
  "ARTIFACTS": [
    "ALL.INC",
    "ALL.html"
  ],
  "TYPE": "MODULE",
  "NAME": "ALL",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "ALL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ALL.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "ALL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ALL.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "ALL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402396838",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "89da57782283d134b814547de37b8643",
      "SIZE": 5053
    },
    {
      "NAME": "ALL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "2df9a6d0c3704457b38078518355bc86",
      "SIZE": 3221
    },
    {
      "NAME": "ALL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397364",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "120abbb62003b1d4a97ac7b20b680e03",
      "SIZE": 7912
    }
  ]
}