{
  "SOURCE": "AOPA.lss",
  "COMMENT": "AOPA module",
  "ARTIFACTS": [
    "AOPA.INC",
    "AOPA.html",
    "AOPA.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "AOPA",
  "DEPENDS": [
    "SEQ"
  ],
  "INSTALL": [
    {
      "TARGET": "AOPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AOPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AOPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "AOPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AOPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "AOPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "AOPA.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402396862",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AOPA.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AOPA.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397364",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "AOPA.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}