{
  "SOURCE": "BALREV.lss",
  "COMMENT": "BALREV module",
  "ARTIFACTS": [
    "BALREV.INC",
    "BALREV.html",
    "BALREV.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "BALREV",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "BALREV.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BALREV.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BALREV.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "BALREV.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BALREV.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BALREV.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "BALREV.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012716",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "f3fff9620240c89ee5eb7818af620467",
      "SIZE": 1730
    },
    {
      "NAME": "BALREV.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012768",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "5c480994a9b5157b07e28ce761da102c",
      "SIZE": 1245
    },
    {
      "NAME": "BALREV.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012786",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "247d7129fa441233988371f62456b202",
      "SIZE": 4050
    },
    {
      "NAME": "BALREV.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "b5c17feff0e63cce4a1456ed8ce9992a",
      "SIZE": 214
    }
  ]
}