{
  "SOURCE": "BQ.lss",
  "COMMENT": "BQ module",
  "ARTIFACTS": [
    "BQ.INC",
    "BQ.html",
    "BQ.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "BQ",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "BQ.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BQ.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BQ.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "BQ.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BQ.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BQ.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "BQ.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012717",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e2047ffd844510193fcfc60f7f84211e",
      "SIZE": 3476
    },
    {
      "NAME": "BQ.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012768",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "20fd4eb147272481d575c846fed9d5a1",
      "SIZE": 2203
    },
    {
      "NAME": "BQ.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012788",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "c82dbccffdcef24001f6ce2c795afe5d",
      "SIZE": 6804
    },
    {
      "NAME": "BQ.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "0605ce0256b7c51d18b8c92b66b81848",
      "SIZE": 133
    }
  ]
}