{
  "SOURCE": "BRKREM.lss",
  "COMMENT": "BRKREM module",
  "ARTIFACTS": [
    "BRKREM.INC",
    "BRKREM.html",
    "BRKREM.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "BRKREM",
  "DEPENDS": [
    "SDIFF"
  ],
  "INSTALL": [
    {
      "TARGET": "BRKREM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BRKREM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BRKREM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "BRKREM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BRKREM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "BRKREM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "BRKREM.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012717",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "871d634685cfc62f79d7d1424a0e0a6c",
      "SIZE": 1966
    },
    {
      "NAME": "BRKREM.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012770",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "d81583a5817a7c4d29660e6cae619a49",
      "SIZE": 1597
    },
    {
      "NAME": "BRKREM.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012837",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "ce42053259a4ae45d6e79695385a3a3b",
      "SIZE": 4166
    },
    {
      "NAME": "BRKREM.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "6c49f7019207d77786853885316fc7a4",
      "SIZE": 141
    }
  ]
}