{
  "SOURCE": "CHARS.lss",
  "COMMENT": "CHARS module",
  "ARTIFACTS": [
    "CHARS.INC",
    "CHARS.html",
    "CHARS.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "CHARS",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "CHARS.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CHARS.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CHARS.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "CHARS.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CHARS.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CHARS.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "CHARS.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012719",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e055ca95f35ac7b41efa892f4f4d9518",
      "SIZE": 3896
    },
    {
      "NAME": "CHARS.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012768",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6fb7f9f0ef41359716316fac7201f6ee",
      "SIZE": 3134
    },
    {
      "NAME": "CHARS.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012789",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "0fb4002cd7ae518682bf52dbe6cd842a",
      "SIZE": 6837
    },
    {
      "NAME": "CHARS.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "f6c33d7dbaaf83ae2a867a60be1b97ba",
      "SIZE": 139
    }
  ]
}