{
  "SOURCE": "COMB.lss",
  "COMMENT": "COMB module",
  "ARTIFACTS": [
    "COMB.INC",
    "COMB.html",
    "COMB.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "COMB",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "COMB.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMB.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMB.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "COMB.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMB.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMB.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "COMB.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012720",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "21817490cb0dd6f08bd546343cf61452",
      "SIZE": 1591
    },
    {
      "NAME": "COMB.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012768",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "fed26fc8235627d3b8cd1ad8000acfb6",
      "SIZE": 1304
    },
    {
      "NAME": "COMB.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012791",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "da46e9de170cbe4cd540c4870c7f1c7f",
      "SIZE": 3783
    },
    {
      "NAME": "COMB.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "b7f01bc4b4ca7b551839e03d48c2a5fa",
      "SIZE": 137
    }
  ]
}