{
  "SOURCE": "COMPLEX.lss",
  "COMMENT": "COMPLEX module",
  "ARTIFACTS": [
    "COMPLEX.INC",
    "COMPLEX.html",
    "COMPLEX.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "COMPLEX",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "COMPLEX.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMPLEX.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMPLEX.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "COMPLEX.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMPLEX.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COMPLEX.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "COMPLEX.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012721",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "4553c365007dde1fc38f73505919bbe6",
      "SIZE": 2478
    },
    {
      "NAME": "COMPLEX.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "9c26cbb208e2920b6fed083e80787f88",
      "SIZE": 2225
    },
    {
      "NAME": "COMPLEX.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012843",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "19cd762296d42810f521f4f36feeb272",
      "SIZE": 4902
    },
    {
      "NAME": "COMPLEX.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "5ddd22afeae172b386e40fdc70b13ac7",
      "SIZE": 143
    }
  ]
}