{
  "SOURCE": "compile.lss",
  "COMMENT": "compile module",
  "ARTIFACTS": [
    "compile",
    "compile.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "COMPILE",
  "DEPENDS": [
    "CHARS",
    "HOST",
    "REPL"
  ],
  "INSTALL": [
    {
      "TARGET": "compile",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "compile.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "compile",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "compile.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "compile.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012721",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "92cffbab1de38022ec7875cfb486a224",
      "SIZE": 7128
    },
    {
      "NAME": "compile",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "70880faeb446e801536fdd354738f8e6",
      "SIZE": 5896
    },
    {
      "NAME": "compile.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012792",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "b752252fa9bcb8b518ea6b74ec8a15a0",
      "SIZE": 10828
    }
  ]
}