{
  "SOURCE": "COUNT.lss",
  "COMMENT": "COUNT module",
  "ARTIFACTS": [
    "COUNT.INC",
    "COUNT.html",
    "COUNT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "COUNT",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "COUNT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COUNT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COUNT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "COUNT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COUNT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "COUNT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "COUNT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012722",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6ae64fa0c063d07406c39aad2d903f7b",
      "SIZE": 2002
    },
    {
      "NAME": "COUNT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012769",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "5c2f6bbb45806354bb9968645833ba7d",
      "SIZE": 1659
    },
    {
      "NAME": "COUNT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012793",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "b697608db4cd27ce3e8c96b354c8ff15",
      "SIZE": 4332
    },
    {
      "NAME": "COUNT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "36a76f4c2d3bceba13f3a0f8720b515f",
      "SIZE": 212
    }
  ]
}