{
  "SOURCE": "CSNOBOL4.lss",
  "COMMENT": "CSNOBOL4 module",
  "ARTIFACTS": [
    "CSNOBOL4.INC",
    "CSNOBOL4.html",
    "CSNOBOL4.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "CSNOBOL4",
  "DEPENDS": [
    "FFI"
  ],
  "INSTALL": [
    {
      "TARGET": "CSNOBOL4.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CSNOBOL4.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CSNOBOL4.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "CSNOBOL4.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CSNOBOL4.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CSNOBOL4.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "CSNOBOL4.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336573",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "CSNOBOL4.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394872",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "CSNOBOL4.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336577",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "CSNOBOL4.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336576",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}