{
  "SOURCE": "CVAR.lss",
  "COMMENT": "CVAR module",
  "ARTIFACTS": [
    "CVAR.INC",
    "CVAR.html",
    "CVAR.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "CVAR",
  "DEPENDS": [
    "CHARS",
    "HASH",
    "P64"
  ],
  "INSTALL": [
    {
      "TARGET": "CVAR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CVAR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CVAR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "CVAR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CVAR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "CVAR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "CVAR.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012723",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "a09079d49a7e5a609a7d1d0faeacc888",
      "SIZE": 8759
    },
    {
      "NAME": "CVAR.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394872",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "c27e72a9411be1abfd4d857921d06380",
      "SIZE": 5697
    },
    {
      "NAME": "CVAR.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012794",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "d87c4d8cd740c165416a5583937619f1",
      "SIZE": 14422
    },
    {
      "NAME": "CVAR.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "a7c2c085d8f639de763df1b5240b20f3",
      "SIZE": 138
    }
  ]
}