{
  "SOURCE": "DAY.lss",
  "COMMENT": "DAY module",
  "ARTIFACTS": [
    "DAY.INC",
    "DAY.html",
    "DAY.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DAY",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "DAY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DAY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DAY.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012723",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "105576902b9faf500d4c03b096939937",
      "SIZE": 2565
    },
    {
      "NAME": "DAY.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "85b773239e2eacc0008c670f9ecb77a1",
      "SIZE": 2174
    },
    {
      "NAME": "DAY.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012795",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "41db794a65bbf9be931cbefca24a2952",
      "SIZE": 4848
    },
    {
      "NAME": "DAY.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "0099843a7a6dfec0e9f063d55d7d264e",
      "SIZE": 135
    }
  ]
}