{
  "SOURCE": "DAY.lss",
  "COMMENT": "DAY module",
  "ARTIFACTS": [
    "DAY.INC",
    "DAY.html",
    "DAY.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DAY",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "DAY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DAY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DAY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DAY.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012723",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DAY.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DAY.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012795",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DAY.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}