{
  "SOURCE": "DDT.lss",
  "COMMENT": "DDT module",
  "ARTIFACTS": [
    "DDT.INC",
    "DDT.html",
    "DDT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DDT",
  "DEPENDS": [
    "CHARS",
    "FREEZE",
    "HOST",
    "QUOTE",
    "READLINE",
    "SLOAD",
    "TRIMB",
    "VDIFFER"
  ],
  "INSTALL": [
    {
      "TARGET": "DDT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DDT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DDT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DDT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DDT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DDT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DDT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012725",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "5d462bfc266da275833c083cc0cce7ba",
      "SIZE": 27582
    },
    {
      "NAME": "DDT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281634",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "42e03431fc6f8eb62bb6ea45b15ce448",
      "SIZE": 23065
    },
    {
      "NAME": "DDT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012796",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "b1e4d2a9602723f870d9bee708989c34",
      "SIZE": 43356
    },
    {
      "NAME": "DDT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "9fbf8f864b7a9f6deed8eaba53eb392a",
      "SIZE": 136
    }
  ]
}