-MODULE DDTCARD
-IN72
* NOTE THAT WE DON'T BRING IN THE INCLUDES SECTION
-LINE 30 "DDTCARD.lss"
-STITL DDTCARD
-EJECT
*
************************************************************************
*                                                                      *
*    ######   ######   #######   #####      #     ######   ######      *
*    #     #  #     #     #     #     #    # #    #     #  #     #     *
*    #     #  #     #     #     #         #   #   #     #  #     #     *
*    #     #  #     #     #     #        #     #  ######   #     #     *
*    #     #  #     #     #     #        #######  #   #    #     #     *
*    #     #  #     #     #     #     #  #     #  #    #   #     #     *
*    ######   ######      #      #####   #     #  #     #  ######      *
*                                                                      *
* DDTCARD       FOR USE WITH -M (MULTI-FILE) OR -L                     *
*                                                                      *
************************************************************************
*
* DDTCARD.lss
*
-LINE 14 "DDTCARD.lss"
         DDT()
*
* CE: .MSNOBOL4;
