{
  "SOURCE": "DEDUPA.lss",
  "COMMENT": "DEDUPA module",
  "ARTIFACTS": [
    "DEDUPA.INC",
    "DEDUPA.html",
    "DEDUPA.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DEDUPA",
  "DEPENDS": [
    "SEQ",
    "SIZEA"
  ],
  "INSTALL": [
    {
      "TARGET": "DEDUPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DEDUPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DEDUPA.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394204",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DEDUPA.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "600",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DEDUPA.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397365",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "DEDUPA.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}