{
  "SOURCE": "DEDUPA.lss",
  "COMMENT": "DEDUPA module",
  "ARTIFACTS": [
    "DEDUPA.INC",
    "DEDUPA.html",
    "DEDUPA.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DEDUPA",
  "DEPENDS": [
    "SEQ",
    "SIZEA"
  ],
  "INSTALL": [
    {
      "TARGET": "DEDUPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DEDUPA.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEDUPA.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DEDUPA.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394204",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "99e6e90b2223fdb840652377965b86d2",
      "SIZE": 2063
    },
    {
      "NAME": "DEDUPA.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "600",
      "LOCATION": "FILE",
      "MD5": "d271ba0e681211b79b7dc13cea4abc3b",
      "SIZE": 1535
    },
    {
      "NAME": "DEDUPA.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397365",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "6bddd73090c42ff3ff280bdbecd811da",
      "SIZE": 4304
    },
    {
      "NAME": "DEDUPA.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "e737018818e4d6278357b93872aa9fb7",
      "SIZE": 141
    }
  ]
}