{
  "SOURCE": "deretn.lss",
  "COMMENT": "deretn module",
  "ARTIFACTS": [
    "deretn",
    "deretn.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "DERETN",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "deretn",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deretn.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "deretn",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deretn.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "deretn.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012725",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "31c34d1e69ecf08dfe97e7a4c5decaa6",
      "SIZE": 1540
    },
    {
      "NAME": "deretn",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012783",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "ef7127069fc61add378bf71048b0c53a",
      "SIZE": 1443
    },
    {
      "NAME": "deretn.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012797",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "93cd6a8572a72e098f0fb447708c7e03",
      "SIZE": 3591
    }
  ]
}