#!/usr/bin/bash
         exec "snobol4" "-b" "$0" "$@"
-PROGRAM DERETN
-LINE 26 "deretn.lss"
-TITLE DERETN
START
*
************************************************************************
*                                                                      *
*                                                                      *
*         ######   #######  ######   #######  #######  #     #         *
*         #     #  #        #     #  #           #     ##    #         *
*         #     #  #        #     #  #           #     # #   #         *
*         #     #  #####    ######   #####       #     #  #  #         *
*         #     #  #        #   #    #           #     #   # #         *
*         #     #  #        #    #   #           #     #    ##         *
*         ######   #######  #     #  #######     #     #     #         *
*                                                                      *
* DERETN         REMOVE LINE NUMBERS FROM CODE SAVE FILE               *
*                                                                      *
************************************************************************
*
* deretn.lss
*
-LINE 12 "deretn.lss"
         TERMINAL = 'DERETN (FRI NOV 22 00:38:55 EST 2013)'
*
         S = DUPL(' ', 5)
*
TOP      (INPUT S) LEN(5) REM . L                                :F(END)
         OUTPUT = TRIM(L)                                         :(TOP)
*
END START
*
* CE: .MSNOBOL4;
