#!/usr/bin/bash
         exec "snobol4" "-b" "$0" "$@"
-TITLE DESEQ
-LINE 22 "deseq.lss"
START
*
************************************************************************
*                                                                      *
*             ######   #######   #####   #######   #####               *
*             #     #  #        #     #  #        #     #              *
*             #     #  #        #        #        #     #              *
*             #     #  #####     #####   #####    #     #              *
*             #     #  #              #  #        #   # #              *
*             #     #  #        #     #  #        #    #               *
*             ######   #######   #####   #######   #### #              *
*                                                                      *
* DESEQ             DESEQUENCE A SOURCE DECK (73-80)                   *
*                                                                      *
************************************************************************
*
* deseq.lss
*
-LINE 8 "deseq.lss"
         TERMINAL = 'DESEQ (SUN JUN 16 14:13:20 EDT 2013)'
*
         S = DUPL(' ', 72)
*
TOP      (INPUT S) LEN(72) . L                                   :F(END)
         OUTPUT = TRIM(L)                                         :(TOP)
*
END START
*
* CE: .MSNOBOL4;
