{
  "SOURCE": "deseql.lss",
  "COMMENT": "deseql module",
  "ARTIFACTS": [
    "deseql",
    "deseql.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "DESEQL",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "deseql",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deseql.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "deseql",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deseql.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "deseql.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012725",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "8132415d438660740db803bee1193537",
      "SIZE": 1383
    },
    {
      "NAME": "deseql",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012783",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "b86bcdd051e1aa0335f29ac0b12952bf",
      "SIZE": 1348
    },
    {
      "NAME": "deseql.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012797",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "1018cd9e1a8778c33d95e5ac2b4e8049",
      "SIZE": 3154
    }
  ]
}