{
  "SOURCE": "deseq.lss",
  "COMMENT": "deseq module",
  "ARTIFACTS": [
    "deseq",
    "deseq.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "DESEQ",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "deseq",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deseq.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "deseq",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "deseq.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "deseq.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012726",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "227302cc72940f2460bc9dabbbf463d6",
      "SIZE": 1568
    },
    {
      "NAME": "deseq",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012783",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "7eedc3eec1ab41ab46d8ba7d06768f4b",
      "SIZE": 1365
    },
    {
      "NAME": "deseq.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012798",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "5764e34c427954e9e7ef0dd2b2e76fda",
      "SIZE": 3551
    }
  ]
}