{
  "SOURCE": "DEXP.lss",
  "COMMENT": "DEXP module",
  "ARTIFACTS": [
    "DEXP.INC",
    "DEXP.html",
    "DEXP.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "DEXP",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "DEXP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEXP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEXP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "DEXP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEXP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "DEXP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "DEXP.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012726",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "58ef63588bb0d18b30e69cbd5ec61f52",
      "SIZE": 1729
    },
    {
      "NAME": "DEXP.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "8f05beb354014f64e03ca68ef6808b67",
      "SIZE": 1370
    },
    {
      "NAME": "DEXP.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012798",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "41522543835df949d7e7faa0d94f80d5",
      "SIZE": 3999
    },
    {
      "NAME": "DEXP.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "e86bc68a319d616f75703d0b757438f0",
      "SIZE": 137
    }
  ]
}