{
  "SOURCE": "embed.lss",
  "COMMENT": "embed module",
  "ARTIFACTS": [
    "embed",
    "embed.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "EMBED",
  "DEPENDS": [
    "CHARS",
    "SLOAD"
  ],
  "INSTALL": [
    {
      "TARGET": "embed",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "embed.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "embed",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "embed.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "embed.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012728",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6affaab80be52d9f68c8d2f08206c63e",
      "SIZE": 5659
    },
    {
      "NAME": "embed",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "fae573da5c662d4630a2a377f8268257",
      "SIZE": 3529
    },
    {
      "NAME": "embed.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012800",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "9ef8092c9300b0b648d16656dfcd598c",
      "SIZE": 9865
    }
  ]
}