{
  "SOURCE": "FASTBAL.lss",
  "COMMENT": "FASTBAL module",
  "ARTIFACTS": [
    "FASTBAL.INC",
    "FASTBAL.html",
    "FASTBAL.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FASTBAL",
  "DEPENDS": [
    "UNIQUE"
  ],
  "INSTALL": [
    {
      "TARGET": "FASTBAL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FASTBAL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FASTBAL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FASTBAL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FASTBAL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FASTBAL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FASTBAL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012728",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "8c2c9ed51ede8c4c3fabb52b60969976",
      "SIZE": 3624
    },
    {
      "NAME": "FASTBAL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012772",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "7310736119c8b1c3decca19bdac65178",
      "SIZE": 2023
    },
    {
      "NAME": "FASTBAL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012801",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "3835be23e466b518abfb62c41b880af9",
      "SIZE": 7466
    },
    {
      "NAME": "FASTBAL.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "539086834a4103ca1f0b2ebc0c29287c",
      "SIZE": 143
    }
  ]
}