{
  "SOURCE": "FENCE.lss",
  "COMMENT": "FENCE module",
  "ARTIFACTS": [
    "FENCE.INC",
    "FENCE.html",
    "FENCE.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FENCE",
  "DEPENDS": [
    "UNIQUE"
  ],
  "INSTALL": [
    {
      "TARGET": "FENCE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FENCE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FENCE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FENCE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FENCE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FENCE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FENCE.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012729",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e496f457a1647a440abedd9b989cef1f",
      "SIZE": 2167
    },
    {
      "NAME": "FENCE.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012772",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "05dc0736ecf8d8d2d282aa17702119be",
      "SIZE": 1264
    },
    {
      "NAME": "FENCE.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012801",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "65a538d71cbe64b543f4397cae59ba81",
      "SIZE": 4461
    },
    {
      "NAME": "FENCE.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "2c08ac2c5bcb3b88accc79f8b41bf58e",
      "SIZE": 139
    }
  ]
}