#line 43 "FFI.lss"
/* Generated by WRAPPER on 06/05/2014 13:33:55 */

#include "config.h"
#include "h.h"
#include "snotypes.h"
#include "macros.h"
#include "load.h"
#include "equ.h"
#include <string.h>

#line 44 "FFI.lss"

#include <ffi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include "p64.h"

static int errors;
static ffi_status ffi_error;

#line 72 "FFI.lss"

static void *interpret_ptype(char **s)
{
    int w = 32;
    int t = 2;
    if (**s == ',')
	++(*s);
    if (**s == 0)
	return NULL;
    for (; **s && (**s != ','); ++(*s)) {
	switch (**s) {
	case ' ':
	case '3':
	case '6':         break;
	case 'v':
	case 'V': t =  0; break;
	case 'u':
	case 'U': t =  1; break;
	case 's':
	case 'S': t =  2; break;
	case 'f':
	case 'F': t =  3; break;
	case 'd':
	case 'D': t =  4; break;
	case 'p':
	case 'P': t =  5; break;
	case 'e':
	case 'E': t =  6; break;
	case 'c':
	case 'C':
	case '8': w =  8; break;
	case '1': w = 16; break;
	case 'i':
	case 'I':
	case '2': w = 32; break;
	case 'l':
	case 'L':
	case '4': w = 64; break;
	default: ++errors; return NULL;
	}
    }
    switch (t) {
    case 0: return &ffi_type_void;
    case 1: switch (w) {
	    case  8: return &ffi_type_uint8;
	    case 16: return &ffi_type_uint16;
	    case 32: return &ffi_type_uint32;
	    case 64: return &ffi_type_uint64;
	    default: ++errors; return NULL;
	    }
    case 2: switch (w) {
	    case  8: return &ffi_type_sint8;
	    case 16: return &ffi_type_sint16;
	    case 32: return &ffi_type_sint32;
	    case 64: return &ffi_type_sint64;
	    default: +errors; return NULL;
	    }
    case 3: return &ffi_type_float;
    case 4: return &ffi_type_double;
    case 5: return &ffi_type_pointer;
    case 6: return &ffi_type_longdouble;
    default: ++errors; return NULL;
    }
    ++errors;
    return NULL;
}

#line 148 "FFI.lss"

typedef struct {
    ffi_cif *cif;
    ffi_type **arg_types;
    ffi_arg *arg_values;
    void **arg_ptrs;
    int *arg_needfree;
    ffi_type *result_type;
    ffi_arg result;
    int nargs;
    void *callp;
} ffi_t;

#line 169 "FFI.lss"

static int new_ffi(char *r, char *s)
{
    ffi_t *ffip;
    int n = 0;
    char *s2 = s;
    ffi_error = FFI_OK;
    ffip = malloc(sizeof(ffi_t));
    if (ffip == NULL) {
	return 0;
    }
    set_p_(ffip);
    set_p2_(get_p_());
    ffip->result_type = interpret_ptype(&r);
    if (ffip->result_type == NULL) {
	return 0;
    }
    errors = 0;
    while (interpret_ptype(&s)) {
	++n;
	if (errors)
	    return 0;
    }
    ffip->nargs = n;
    if (n == 0)
	n = 1;
    ffip->cif = malloc(sizeof(ffi_cif));
    ffip->arg_types = malloc((n + 1) * (sizeof(ffi_type *)));
    ffip->arg_values = malloc((n + 1) * (sizeof(ffi_arg)));
    ffip->arg_needfree = malloc((n + 1) * (sizeof(int)));
    ffip->arg_ptrs = malloc((n + 1) * (sizeof(void *)));
    if ((ffip->arg_types == NULL) ||
	(ffip->arg_values == NULL) ||
	(ffip->arg_ptrs == NULL) ||
	(ffip->arg_needfree == NULL) ||
	(ffip->cif == NULL))
	return 0;
    s = s2;
    n = 0;
    while ((ffip->arg_types[n] = interpret_ptype(&s)) != NULL) {
	ffip->arg_ptrs[n] = &ffip->arg_values[n];
	ffip->arg_needfree[n] = 0;
	++n;
    }
    ffi_error = ffi_prep_cif(ffip->cif,
			     FFI_DEFAULT_ABI,
			     ffip->nargs,
			     ffip->result_type,
			     ffip->arg_types);
    if (ffi_error != FFI_OK)
	return 0;
    return 1;
}


/* NEW_FFI(STRING,STRING)PREDICATE */
NEW_FFI( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    char arg1[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    getstring(LA_PTR(1), arg1, sizeof(arg1));
    if (new_ffi(arg0,arg1))
	RETNULL;
    RETFAIL;
}
#line 224 "FFI.lss"

#line 231 "FFI.lss"

static void clear_ffi(void)
{
    ffi_t *ffip = get_p_();
    int i;
    for (i = 0; i < ffip->nargs; ++i) {
	if (ffip->arg_needfree[i]) {
	    free((void *)ffip->arg_values[i]);
	    ffip->arg_needfree[i] = 0;
	}
    }
}


/* CLEAR_FFI() */
CLEAR_FFI( LA_ALIST ) LA_DCL
{
    clear_ffi();
    RETNULL;
}
#line 245 "FFI.lss"

#line 251 "FFI.lss"

static void free_ffi(void)
{
    ffi_t *ffip = get_p_();
    free(ffip->arg_values);
    free(ffip->arg_types);
    free(ffip->arg_needfree);
    free(ffip->cif);
    free(ffip);
}


/* FREE_FFI() */
FREE_FFI( LA_ALIST ) LA_DCL
{
    free_ffi();
    RETNULL;
}
#line 263 "FFI.lss"

#line 270 "FFI.lss"

static int par_n_needfree(int n)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_needfree[n - 1] = 1;
    return 1;
}


/* PAR_N_NEEDFREE(INTEGER)PREDICATE */
PAR_N_NEEDFREE( LA_ALIST ) LA_DCL
{
    if (par_n_needfree((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 281 "FFI.lss"

#line 287 "FFI.lss"

static int set_par_n_integer(int n, int v)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = v;
    return 1;
}


/* SET_PAR_N_INTEGER(INTEGER,INTEGER)PREDICATE */
SET_PAR_N_INTEGER( LA_ALIST ) LA_DCL
{
    if (set_par_n_integer((int)LA_INT(0),(int)LA_INT(1)))
	RETNULL;
    RETFAIL;
}
#line 299 "FFI.lss"

#line 306 "FFI.lss"

static int set_par_n_real(int n, double v)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = v;
    return 1;
}


/* SET_PAR_N_REAL(INTEGER,REAL)PREDICATE */
SET_PAR_N_REAL( LA_ALIST ) LA_DCL
{
    if (set_par_n_real((int)LA_INT(0),(double)LA_REAL(1)))
	RETNULL;
    RETFAIL;
}
#line 317 "FFI.lss"

#line 324 "FFI.lss"

static int set_par_n_p(int n)
{
    ffi_t *ffip = get_p2_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = (long)get_p_();
    return 1;
}


/* SET_PAR_N_P(INTEGER)PREDICATE */
SET_PAR_N_P( LA_ALIST ) LA_DCL
{
    if (set_par_n_p((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 335 "FFI.lss"

#line 341 "FFI.lss"

static int set_par_n_f(int n)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = get_f_();
    return 1;
}


/* SET_PAR_N_F(INTEGER)PREDICATE */
SET_PAR_N_F( LA_ALIST ) LA_DCL
{
    if (set_par_n_f((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 352 "FFI.lss"

#line 358 "FFI.lss"

static int set_par_n_d(int n)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = get_d_();
    return 1;
}


/* SET_PAR_N_D(INTEGER)PREDICATE */
SET_PAR_N_D( LA_ALIST ) LA_DCL
{
    if (set_par_n_d((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 369 "FFI.lss"

#line 375 "FFI.lss"

static int set_par_n_ld(int n)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
	return 0;
    ffip->arg_values[n - 1] = get_ld_();
    return 1;
}


/* SET_PAR_N_LD(INTEGER)PREDICATE */
SET_PAR_N_LD( LA_ALIST ) LA_DCL
{
    if (set_par_n_ld((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 386 "FFI.lss"

#line 393 "FFI.lss"

static int set_par_n_string(int n, char *s)
{
    ffi_t *ffip = get_p_();
    if ((n < 1) || (n > ffip->nargs))
        return 0;
    ffip->arg_values[n - 1] = (long)strdup(s);
    if (ffip->arg_values[n - 1] == (long)NULL)
        return 0;
    ffip->arg_needfree[n - 1] = 1;
    return 1;
}


/* SET_PAR_N_STRING(INTEGER,STRING)PREDICATE */
SET_PAR_N_STRING( LA_ALIST ) LA_DCL
{
    char arg1[1024];
    getstring(LA_PTR(1), arg1, sizeof(arg1));
    if (set_par_n_string((int)LA_INT(0),arg1))
	RETNULL;
    RETFAIL;
}
#line 408 "FFI.lss"

#line 414 "FFI.lss"

/* CIF in P2, FN in P */
static void set_callp(void)
{
    ffi_t *ffip = get_p2_();
    ffip->callp = get_p_();
}


/* SET_CALLP() */
SET_CALLP( LA_ALIST ) LA_DCL
{
    set_callp();
    RETNULL;
}
#line 423 "FFI.lss"

#line 429 "FFI.lss"

static void call_ffi(void)
{
    ffi_t *ffip = get_p_();
    ffi_call(ffip->cif, FFI_FN(ffip->callp),
	     &ffip->result, ffip->arg_ptrs);
    if (ffip->result_type == &ffi_type_void) /* */ ;
    else if ((ffip->result_type == &ffi_type_uint8) ||
	     (ffip->result_type == &ffi_type_sint8) ||
	     (ffip->result_type == &ffi_type_uint16) ||
	     (ffip->result_type == &ffi_type_sint16) ||
	     (ffip->result_type == &ffi_type_uint32) ||
	     (ffip->result_type == &ffi_type_sint32) ||
	     (ffip->result_type == &ffi_type_uint64) ||
	     (ffip->result_type == &ffi_type_sint64) ||
	     (ffip->result_type == &ffi_type_pointer))
	set_p_((void *)(long)ffip->result);
    else if (ffip->result_type == &ffi_type_float)
	set_f_(ffip->result);
    else if (ffip->result_type == &ffi_type_double)
	set_d_(ffip->result);
    else if (ffip->result_type == &ffi_type_longdouble)
	set_ld_(ffip->result);
}


/* CALL_FFI() */
CALL_FFI( LA_ALIST ) LA_DCL
{
    call_ffi();
    RETNULL;
}
#line 455 "FFI.lss"

#line 462 "FFI.lss"

static int call_integer_ffi(void)
{
    ffi_t *ffip = get_p_();
    ffi_call(ffip->cif, FFI_FN(ffip->callp),
	     &ffip->result, ffip->arg_ptrs);
    return ffip->result;
}


/* CALL_INTEGER_FFI()INTEGER */
CALL_INTEGER_FFI( LA_ALIST ) LA_DCL
{
    RETINT(call_integer_ffi());
}
#line 472 "FFI.lss"

static double call_real_ffi(void)
{
    ffi_t *ffip = get_p_();
    ffi_call(ffip->cif, FFI_FN(ffip->callp),
	     &ffip->result, ffip->arg_ptrs);
    return ffip->result;
}


/* CALL_REAL_FFI()REAL */
CALL_REAL_FFI( LA_ALIST ) LA_DCL
{
    RETREAL(call_real_ffi());
}
#line 482 "FFI.lss"

static char *call_string_ffi(void)
{
    ffi_t *ffip = get_p_();
    ffi_call(ffip->cif, FFI_FN(ffip->callp),
	     &ffip->result, ffip->arg_ptrs);
    return (char *)ffip->result;
}


/* CALL_STRING_FFI()STRING */
CALL_STRING_FFI( LA_ALIST ) LA_DCL
{
    RETSTR((char *)call_string_ffi());
}
#line 492 "FFI.lss"

#line 500 "FFI.lss"

/* DL functions
 */
static void dlopen_ffi(char *s, int n) { set_p_(dlopen(s, n)); }


/* DLOPEN_FFI(STRING,INTEGER) */
DLOPEN_FFI( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    dlopen_ffi(arg0,(int)LA_INT(1));
    RETNULL;
}
#line 506 "FFI.lss"

static char *dlerror_ffi(void)
{
    char *s = dlerror();
    if (s == NULL) return "";
    return s;
}


/* DLERROR_FFI()STRING */
DLERROR_FFI( LA_ALIST ) LA_DCL
{
    RETSTR((char *)dlerror_ffi());
}
#line 515 "FFI.lss"

static void dlsym_ffi(char *s) { set_p_(dlsym(get_p_(), s)); }


/* DLSYM_FFI(STRING) */
DLSYM_FFI( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    dlsym_ffi(arg0);
    RETNULL;
}
#line 519 "FFI.lss"

static int dlclose_ffi(void) { return dlclose(get_p_()); }


/* DLCLOSE_FFI()INTEGER */
DLCLOSE_FFI( LA_ALIST ) LA_DCL
{
    RETINT(dlclose_ffi());
}
#line 523 "FFI.lss"

