{
  "SOURCE": "FFI.lss",
  "COMMENT": "FFI module",
  "ARTIFACTS": [
    "FFI.INC",
    "FFI.html",
    "FFI.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FFI",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "FFI.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FFI.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FFI.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FFI.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FFI.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FFI.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FFI.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336388",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "800409da706178fbaa3648dd5ec4ef94",
      "SIZE": 16202
    },
    {
      "NAME": "FFI.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394872",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "07df5cb7400e3fc55a9ed1440e600a5f",
      "SIZE": 4525
    },
    {
      "NAME": "FFI.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336391",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "3c57339dc17a600ff9a4d42dba102b3e",
      "SIZE": 26233
    },
    {
      "NAME": "FFI.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402336391",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "e27af1fe91e7d9121bedc79a958245a0",
      "SIZE": 136
    }
  ]
}