{
  "SOURCE": "FLOOR.lss",
  "COMMENT": "FLOOR module",
  "ARTIFACTS": [
    "FLOOR.INC",
    "FLOOR.html",
    "FLOOR.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FLOOR",
  "DEPENDS": [
    "DEXP"
  ],
  "INSTALL": [
    {
      "TARGET": "FLOOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FLOOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FLOOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FLOOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FLOOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FLOOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FLOOR.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012730",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "1860ad5899f04bf88fc7a17ee6cf8687",
      "SIZE": 1790
    },
    {
      "NAME": "FLOOR.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012772",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "67cf56e7e622bad2f0ff30d2f6f65553",
      "SIZE": 1427
    },
    {
      "NAME": "FLOOR.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012803",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "b19c390cbbf9a20a1b528faba5050a94",
      "SIZE": 4116
    },
    {
      "NAME": "FLOOR.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "7258d57cc34c36e7c1ecbbee4bb0db8b",
      "SIZE": 139
    }
  ]
}