{
  "SOURCE": "FOR.lss",
  "COMMENT": "FOR module",
  "ARTIFACTS": [
    "FOR.INC",
    "FOR.html",
    "FOR.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FOR",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "FOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FOR.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012731",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "FOR.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "FOR.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012847",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "FOR.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}