{
  "SOURCE": "FOR.lss",
  "COMMENT": "FOR module",
  "ARTIFACTS": [
    "FOR.INC",
    "FOR.html",
    "FOR.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FOR",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "FOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FOR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FOR.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012731",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "49c9723dbaa175d6244eec5d1fc7d555",
      "SIZE": 8939
    },
    {
      "NAME": "FOR.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "97c0cea0f28548f7ccaa7d857c683786",
      "SIZE": 4670
    },
    {
      "NAME": "FOR.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012847",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "ae1e6f97f3c94a5cf33fa2595ab86aa4",
      "SIZE": 15123
    },
    {
      "NAME": "FOR.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "62097dcc865813b4bea87239803ca6cd",
      "SIZE": 2244
    }
  ]
}