{
  "SOURCE": "FOREACH.lss",
  "COMMENT": "FOREACH module",
  "ARTIFACTS": [
    "FOREACH.INC",
    "FOREACH.html",
    "FOREACH.tst"
  ],
  "TYPE": "PROGRAM",
  "NAME": "FOREACH",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "FOREACH.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOREACH.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOREACH.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FOREACH.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOREACH.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FOREACH.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FOREACH.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402487472",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "0b998b0c3ab6f0a540178cb9dd8e4e1b",
      "SIZE": 2617
    },
    {
      "NAME": "FOREACH.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402487480",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "10f846365e7092e09ee13fa9d6c51fca",
      "SIZE": 1214
    },
    {
      "NAME": "FOREACH.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402487480",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "343fe0f1e9be5e197425a21444610b9d",
      "SIZE": 5020
    },
    {
      "NAME": "FOREACH.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402487481",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "3923fcc353a6d9a0da2fa550265a5990",
      "SIZE": 408
    }
  ]
}