{
  "SOURCE": "FREEZE.lss",
  "COMMENT": "FREEZE module",
  "ARTIFACTS": [
    "FREEZE.INC",
    "FREEZE.html",
    "FREEZE.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "FREEZE",
  "DEPENDS": [
    "SYSTEM"
  ],
  "INSTALL": [
    {
      "TARGET": "FREEZE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FREEZE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FREEZE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "FREEZE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FREEZE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "FREEZE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "FREEZE.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012731",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "ccdfdccb120962e0d6acf58ac0ab53ce",
      "SIZE": 1641
    },
    {
      "NAME": "FREEZE.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "fc929c8e917370bf2c1e5a1de827a794",
      "SIZE": 1405
    },
    {
      "NAME": "FREEZE.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012847",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "f9395cb5eb8828e5f7c739d21bbd1c64",
      "SIZE": 3716
    },
    {
      "NAME": "FREEZE.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "fce2cf184a9b2bf0dbfd2aa06112d44c",
      "SIZE": 141
    }
  ]
}