{
  "SOURCE": "GCD.lss",
  "COMMENT": "GCD module",
  "ARTIFACTS": [
    "GCD.INC",
    "GCD.html",
    "GCD.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "GCD",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "GCD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "GCD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "GCD.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012731",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "GCD.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "GCD.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012842",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "GCD.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}