{
  "SOURCE": "GCD.lss",
  "COMMENT": "GCD module",
  "ARTIFACTS": [
    "GCD.INC",
    "GCD.html",
    "GCD.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "GCD",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "GCD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "GCD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GCD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "GCD.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012731",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "585b9c32357d393517ffc8b164b5e028",
      "SIZE": 1804
    },
    {
      "NAME": "GCD.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6a01a181c958bbcfabf98c6faa4d3fd2",
      "SIZE": 1485
    },
    {
      "NAME": "GCD.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012842",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "537256c4c4f8b124245346b979dbd75e",
      "SIZE": 4017
    },
    {
      "NAME": "GCD.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "075044312976cb87c35bff4aa6fbde82",
      "SIZE": 208
    }
  ]
}