{
  "SOURCE": "GOTOS.lss",
  "COMMENT": "GOTOS module",
  "ARTIFACTS": [
    "GOTOS.INC",
    "GOTOS.html",
    "GOTOS.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "GOTOS",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "GOTOS.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GOTOS.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GOTOS.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "GOTOS.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GOTOS.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "GOTOS.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "GOTOS.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012732",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e1059a9fd4c360d0f55bafa97be1d352",
      "SIZE": 2705
    },
    {
      "NAME": "GOTOS.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012772",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "8632821c235ef41be2d408da449e8183",
      "SIZE": 1715
    },
    {
      "NAME": "GOTOS.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012804",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "964d74511e684915e009be5719fb8c97",
      "SIZE": 5445
    },
    {
      "NAME": "GOTOS.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "ce07acfc86346adebd2c466d4e146dc4",
      "SIZE": 139
    }
  ]
}