{
  "SOURCE": "HOST.lss",
  "COMMENT": "HOST module",
  "ARTIFACTS": [
    "HOST.INC",
    "HOST.html",
    "HOST.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "HOST",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "HOST.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "HOST.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "HOST.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "HOST.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "HOST.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "HOST.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "HOST.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012733",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "9bf195fceb1cbcaaf3d9786867fdc24c",
      "SIZE": 4718
    },
    {
      "NAME": "HOST.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012769",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "222490f5f36c75c162fb2aa865c9aaf8",
      "SIZE": 3489
    },
    {
      "NAME": "HOST.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012805",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "8773b742d3cc04a8092072156796546b",
      "SIZE": 9055
    },
    {
      "NAME": "HOST.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "d6402eceb17e2507c3db8f31e4b37a05",
      "SIZE": 138
    }
  ]
}