{
  "SOURCE": "ifs.lss",
  "COMMENT": "ifs module",
  "ARTIFACTS": [
    "ifs",
    "ifs.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "IFS",
  "DEPENDS": [
    "CHARS",
    "FASTBAL",
    "HOST",
    "SYSTEM",
    "VDIFFER"
  ],
  "INSTALL": [
    {
      "TARGET": "ifs",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ifs.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "ifs",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ifs.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "ifs.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012734",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e2a5473c7f9dc81e8d165b6d27a910e6",
      "SIZE": 13230
    },
    {
      "NAME": "ifs",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "a718b7df4a0afa37f033e07e57711878",
      "SIZE": 11381
    },
    {
      "NAME": "ifs.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012806",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "3f39eb9a44d1cf763d0361c58a4fb152",
      "SIZE": 22086
    }
  ]
}