{
  "SOURCE": "illum.lss",
  "COMMENT": "illum module",
  "ARTIFACTS": [
    "illum",
    "illum.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "ILLUM",
  "DEPENDS": [
    "BQ",
    "CRACK",
    "SEQ",
    "TRIMB",
    "VDIFFER"
  ],
  "INSTALL": [
    {
      "TARGET": "illum",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "illum.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "illum",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "illum.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "illum.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012735",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "2248afb84e6c3f3641811d6e94015254",
      "SIZE": 2467
    },
    {
      "NAME": "illum",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "a0f201257e538806c2ee0d73cf981a7a",
      "SIZE": 2045
    },
    {
      "NAME": "illum.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012806",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "89313d2508e9f82d53c6537b1e9c7bf4",
      "SIZE": 4826
    }
  ]
}