{
  "SOURCE": "INFINIP.lss",
  "COMMENT": "INFINIP module",
  "ARTIFACTS": [
    "INFINIP.INC",
    "INFINIP.html",
    "INFINIP.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "INFINIP",
  "DEPENDS": [
    "REDEFINE",
    "SWAP"
  ],
  "INSTALL": [
    {
      "TARGET": "INFINIP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "INFINIP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "INFINIP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "INFINIP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "INFINIP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "INFINIP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "INFINIP.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012735",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "9a3e6cec342309dc07a95728147abdb5",
      "SIZE": 8383
    },
    {
      "NAME": "INFINIP.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012772",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "f761b8a89d2941dc3f7aa6396cf27485",
      "SIZE": 8074
    },
    {
      "NAME": "INFINIP.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012807",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "e084c4e8c7099aa73197d5dd4fbb13c4",
      "SIZE": 12842
    },
    {
      "NAME": "INFINIP.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "0a6ff5cac57f47f45b5d1c1424cbdc64",
      "SIZE": 144
    }
  ]
}