{
  "SOURCE": "ITERDIR.lss",
  "COMMENT": "ITERDIR module",
  "ARTIFACTS": [
    "ITERDIR.INC",
    "ITERDIR.html",
    "ITERDIR.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "ITERDIR",
  "DEPENDS": [
    "ATOL",
    "BQ",
    "CHARS",
    "CRACK",
    "LINK"
  ],
  "INSTALL": [
    {
      "TARGET": "ITERDIR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ITERDIR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ITERDIR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "ITERDIR.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ITERDIR.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ITERDIR.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "ITERDIR.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402201503",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "eab10293d5245f0c6c8ad510d60b7d98",
      "SIZE": 2728
    },
    {
      "NAME": "ITERDIR.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397362",
      "ACCESS": "600",
      "LOCATION": "FILE",
      "MD5": "9de693b6300d8f89dc64a58fb93b9c42",
      "SIZE": 1673
    },
    {
      "NAME": "ITERDIR.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402273692",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "084214aca180e5447f9108c42adc33b4",
      "SIZE": 5201
    },
    {
      "NAME": "ITERDIR.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402201644",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "ad6822d2897655a5acb83750bef106f2",
      "SIZE": 143
    }
  ]
}