#line 34 "JIT.lss"
/* Generated by WRAPPER on 06/20/2014 13:34:31 */

#include "config.h"
#include "h.h"
#include "snotypes.h"
#include "macros.h"
#include "load.h"
#include "equ.h"
#include <string.h>

#line 35 "JIT.lss"

#include <lightning.h>

#define jit_r_num_() JIT_R_NUM
#define jit_v_num_() JIT_V_NUM
#define jit_f_num_() JIT_F_NUM
static jit_state_t *_jit;
static int note_i = 0;
static char *note_s1 = "";
static char *note_s2 = "";
static char *get_note_s1(void) { return note_s1; }
static char *get_note_s2(void) { return note_s2; }
static int get_note_i(void) { return note_i; }
static void *jit_get_state(void) { return _jit; }
static void jit_set_state(void *p) { _jit = p; }
static int get_note_jit(void *p)
{
    return jit_get_note(p, &note_s1, &note_s2, &note_i);
}
#ifdef JIT_R0
#define r0_() JIT_R0
#else
#define r0() -1
#endif
#ifdef JIT_R1
#define r1_() JIT_R1
#else
#define r1_() -1
#endif
#ifdef JIT_R2
#define r2_() JIT_R2
#else
#define r2_() -1
#endif
#ifdef JIT_R3
#define r3_() JIT_R3
#else
#define r3_() -1
#endif
#ifdef JIT_V0
#define v0_() JIT_V0
#else
#define v0_() -1
#endif
#ifdef JIT_V1
#define v1_() JIT_V1
#else
#define v1_() -1
#endif
#ifdef JIT_V2
#define v2_() JIT_V2
#else
#define v2_() -1
#endif
#ifdef JIT_V3
#define v3_() JIT_V3
#else
#define v3_() -1
#endif
#ifdef JIT_F0
#define f0_() JIT_F0
#else
#define f0_() -1
#endif
#ifdef JIT_F1
#define f1_() JIT_F1
#else
#define f1_() -1
#endif
#ifdef JIT_F2
#define f2_() JIT_F2
#else
#define f2_() -1
#endif
#ifdef JIT_F3
#define f3_() JIT_F3
#else
#define f3_() -1
#endif
#ifdef JIT_F4
#define f4_() JIT_F4
#else
#define f4_() -1
#endif
#ifdef JIT_F5
#define f5_() JIT_F5
#else
#define f5_() -1
#endif
#ifdef JIT_F6
#define f6_() JIT_F6
#else
#define f6_() -1
#endif
#ifdef JIT_F7
#define f7_() JIT_F7
#else
#define f7_() -1
#endif
#ifdef JIT_FP
#define fp_() JIT_FP
#else
#define fp_() -1
#endif

/* INIT_JIT(STRING) */
INIT_JIT( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    init_jit(arg0);
    RETNULL;
}
#line 140 "JIT.lss"

/* FINISH_JIT() */
FINISH_JIT( LA_ALIST ) LA_DCL
{
    finish_jit();
    RETNULL;
}
#line 141 "JIT.lss"

/* JIT_GET_STATE()POINTER */
JIT_GET_STATE( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_get_state());
}
#line 142 "JIT.lss"

/* JIT_SET_STATE(POINTER) */
JIT_SET_STATE( LA_ALIST ) LA_DCL
{
    jit_set_state((void *)(long)LA_INT(0));
    RETNULL;
}
#line 143 "JIT.lss"

/* JIT_NEW_STATE()POINTER */
JIT_NEW_STATE( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_new_state());
}
#line 144 "JIT.lss"

/* JIT_DESTROY_STATE() */
JIT_DESTROY_STATE( LA_ALIST ) LA_DCL
{
    jit_destroy_state();
    RETNULL;
}
#line 145 "JIT.lss"

/* JIT_CLEAR_STATE() */
JIT_CLEAR_STATE( LA_ALIST ) LA_DCL
{
    jit_clear_state();
    RETNULL;
}
#line 146 "JIT.lss"

/* JIT_PROLOG() */
JIT_PROLOG( LA_ALIST ) LA_DCL
{
    jit_prolog();
    RETNULL;
}
#line 147 "JIT.lss"

/* JIT_EPILOG() */
JIT_EPILOG( LA_ALIST ) LA_DCL
{
    jit_epilog();
    RETNULL;
}
#line 148 "JIT.lss"

/* JIT_NOTE(STRING,INTEGER)POINTER */
JIT_NOTE( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    RETINT((long)jit_note(arg0,(int)LA_INT(1)));
}
#line 149 "JIT.lss"

/* JIT_NAME(STRING)POINTER */
JIT_NAME( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    RETINT((long)jit_name(arg0));
}
#line 150 "JIT.lss"

/* JIT_ADDRESS(POINTER)POINTER */
JIT_ADDRESS( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_address((void *)(long)LA_INT(0)));
}
#line 151 "JIT.lss"

/* JIT_DISASSEMBLE() */
JIT_DISASSEMBLE( LA_ALIST ) LA_DCL
{
    jit_disassemble();
    RETNULL;
}
#line 152 "JIT.lss"

/* JIT_EMIT()POINTER */
JIT_EMIT( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_emit());
}
#line 153 "JIT.lss"

/* JIT_PRINT() */
JIT_PRINT( LA_ALIST ) LA_DCL
{
    jit_print();
    RETNULL;
}
#line 154 "JIT.lss"

/* JIT_LABEL()POINTER */
JIT_LABEL( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_label());
}
#line 155 "JIT.lss"

/* JIT_ELLIPSIS() */
JIT_ELLIPSIS( LA_ALIST ) LA_DCL
{
    jit_ellipsis();
    RETNULL;
}
#line 156 "JIT.lss"

/* GET_NOTE_I()INTEGER */
GET_NOTE_I( LA_ALIST ) LA_DCL
{
    RETINT(get_note_i());
}
#line 157 "JIT.lss"

/* GET_NOTE_S1()STRING */
GET_NOTE_S1( LA_ALIST ) LA_DCL
{
    RETSTR((char *)get_note_s1());
}
#line 158 "JIT.lss"

/* GET_NOTE_S2()STRING */
GET_NOTE_S2( LA_ALIST ) LA_DCL
{
    RETSTR((char *)get_note_s2());
}
#line 159 "JIT.lss"

/* GET_NOTE_JIT(POINTER)PREDICATE */
GET_NOTE_JIT( LA_ALIST ) LA_DCL
{
    if (get_note_jit((void *)(long)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 160 "JIT.lss"

/* JIT_POINTER_P(POINTER)PREDICATE */
JIT_POINTER_P( LA_ALIST ) LA_DCL
{
    if (jit_pointer_p((void *)(long)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 161 "JIT.lss"

/* JIT_CALLEE_SAVE_P(INTEGER)PREDICATE */
JIT_CALLEE_SAVE_P( LA_ALIST ) LA_DCL
{
    if (jit_callee_save_p((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 162 "JIT.lss"

/* JIT_PATCH_AT(POINTER,POINTER) */
JIT_PATCH_AT( LA_ALIST ) LA_DCL
{
    jit_patch_at((void *)(long)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 163 "JIT.lss"

/* JIT_PATCH_ABS(POINTER,POINTER) */
JIT_PATCH_ABS( LA_ALIST ) LA_DCL
{
    jit_patch_abs((void *)(long)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 164 "JIT.lss"

/* JIT_PATCH(POINTER) */
JIT_PATCH( LA_ALIST ) LA_DCL
{
    jit_patch((void *)(long)LA_INT(0));
    RETNULL;
}
#line 165 "JIT.lss"

/* JIT_PREPARE() */
JIT_PREPARE( LA_ALIST ) LA_DCL
{
    jit_prepare();
    RETNULL;
}
#line 166 "JIT.lss"

/* JIT_ALLOCAI(INTEGER)INTEGER */
JIT_ALLOCAI( LA_ALIST ) LA_DCL
{
    RETINT(jit_allocai((int)LA_INT(0)));
}
#line 167 "JIT.lss"

/* JIT_DATA(POINTER,INTEGER,INTEGER)POINTER */
JIT_DATA( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_data((void *)(long)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 168 "JIT.lss"

/* JIT_FORWARD()POINTER */
JIT_FORWARD( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_forward());
}
#line 169 "JIT.lss"

/* JIT_INDIRECT()POINTER */
JIT_INDIRECT( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_indirect());
}
#line 170 "JIT.lss"

/* JIT_LIVE(INTEGER)POINTER */
JIT_LIVE( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_live((int)LA_INT(0)));
}
#line 171 "JIT.lss"

/* JIT_LINK(POINTER) */
JIT_LINK( LA_ALIST ) LA_DCL
{
    jit_link((void *)(long)LA_INT(0));
    RETNULL;
}
#line 172 "JIT.lss"

/* JIT_R_NUM_()INTEGER */
JIT_R_NUM_( LA_ALIST ) LA_DCL
{
    RETINT(jit_r_num_());
}
#line 173 "JIT.lss"

/* JIT_V_NUM_()INTEGER */
JIT_V_NUM_( LA_ALIST ) LA_DCL
{
    RETINT(jit_v_num_());
}
#line 174 "JIT.lss"

/* JIT_F_NUM_()INTEGER */
JIT_F_NUM_( LA_ALIST ) LA_DCL
{
    RETINT(jit_f_num_());
}
#line 175 "JIT.lss"

/* R0_()INTEGER */
R0_( LA_ALIST ) LA_DCL
{
    RETINT(r0_());
}
#line 176 "JIT.lss"

/* R1_()INTEGER */
R1_( LA_ALIST ) LA_DCL
{
    RETINT(r1_());
}
#line 177 "JIT.lss"

/* R2_()INTEGER */
R2_( LA_ALIST ) LA_DCL
{
    RETINT(r2_());
}
#line 178 "JIT.lss"

/* R3_()INTEGER */
R3_( LA_ALIST ) LA_DCL
{
    RETINT(r3_());
}
#line 179 "JIT.lss"

/* V0_()INTEGER */
V0_( LA_ALIST ) LA_DCL
{
    RETINT(v0_());
}
#line 180 "JIT.lss"

/* V1_()INTEGER */
V1_( LA_ALIST ) LA_DCL
{
    RETINT(v1_());
}
#line 181 "JIT.lss"

/* V2_()INTEGER */
V2_( LA_ALIST ) LA_DCL
{
    RETINT(v2_());
}
#line 182 "JIT.lss"

/* V3_()INTEGER */
V3_( LA_ALIST ) LA_DCL
{
    RETINT(v3_());
}
#line 183 "JIT.lss"

/* F0_()INTEGER */
F0_( LA_ALIST ) LA_DCL
{
    RETINT(f0_());
}
#line 184 "JIT.lss"

/* F1_()INTEGER */
F1_( LA_ALIST ) LA_DCL
{
    RETINT(f1_());
}
#line 185 "JIT.lss"

/* F2_()INTEGER */
F2_( LA_ALIST ) LA_DCL
{
    RETINT(f2_());
}
#line 186 "JIT.lss"

/* F3_()INTEGER */
F3_( LA_ALIST ) LA_DCL
{
    RETINT(f3_());
}
#line 187 "JIT.lss"

/* F4_()INTEGER */
F4_( LA_ALIST ) LA_DCL
{
    RETINT(f4_());
}
#line 188 "JIT.lss"

/* F5_()INTEGER */
F5_( LA_ALIST ) LA_DCL
{
    RETINT(f5_());
}
#line 189 "JIT.lss"

/* F6_()INTEGER */
F6_( LA_ALIST ) LA_DCL
{
    RETINT(f6_());
}
#line 190 "JIT.lss"

/* F7_()INTEGER */
F7_( LA_ALIST ) LA_DCL
{
    RETINT(f7_());
}
#line 191 "JIT.lss"

/* FP_()INTEGER */
FP_( LA_ALIST ) LA_DCL
{
    RETINT(fp_());
}
#line 192 "JIT.lss"

/* JIT_ADDR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ADDR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 193 "JIT.lss"

/* JIT_ADDR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ADDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 194 "JIT.lss"

/* JIT_ADDR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ADDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 195 "JIT.lss"

/* JIT_ADDI(INTEGER,INTEGER,LONG)POINTER */
JIT_ADDI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 196 "JIT.lss"

/* JIT_ADDI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_ADDI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addi_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 197 "JIT.lss"

/* JIT_ADDI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_ADDI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addi_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 198 "JIT.lss"

/* JIT_ADDXR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ADDXR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addxr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 199 "JIT.lss"

/* JIT_ADDXI(INTEGER,INTEGER,LONG)POINTER */
JIT_ADDXI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addxi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 200 "JIT.lss"

/* JIT_ADDCR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ADDCR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addcr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 201 "JIT.lss"

/* JIT_ADDCI(INTEGER,INTEGER,LONG)POINTER */
JIT_ADDCI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_addci((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 202 "JIT.lss"

/* JIT_SUBR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_SUBR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 203 "JIT.lss"

/* JIT_SUBR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_SUBR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 204 "JIT.lss"

/* JIT_SUBR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_SUBR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 205 "JIT.lss"

/* JIT_SUBI(INTEGER,INTEGER,LONG)POINTER */
JIT_SUBI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 206 "JIT.lss"

/* JIT_SUBI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_SUBI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subi_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 207 "JIT.lss"

/* JIT_SUBI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_SUBI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subi_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 208 "JIT.lss"

/* JIT_SUBXR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_SUBXR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subxr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 209 "JIT.lss"

/* JIT_SUBXI(INTEGER,INTEGER,LONG)POINTER */
JIT_SUBXI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subxi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 210 "JIT.lss"

/* JIT_SUBCR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_SUBCR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subcr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 211 "JIT.lss"

/* JIT_SUBCI(INTEGER,INTEGER,LONG)POINTER */
JIT_SUBCI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_subci((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 212 "JIT.lss"

/* JIT_MULR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_MULR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_mulr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 213 "JIT.lss"

/* JIT_MULR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_MULR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_mulr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 214 "JIT.lss"

/* JIT_MULR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_MULR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_mulr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 215 "JIT.lss"

/* JIT_MULI(INTEGER,INTEGER,LONG)POINTER */
JIT_MULI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_muli((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 216 "JIT.lss"

/* JIT_MULI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_MULI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_muli_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 217 "JIT.lss"

/* JIT_MULI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_MULI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_muli_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 218 "JIT.lss"

/* JIT_DIVR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_DIVR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 219 "JIT.lss"

/* JIT_DIVR_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_DIVR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divr_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 220 "JIT.lss"

/* JIT_DIVR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_DIVR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 221 "JIT.lss"

/* JIT_DIVR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_DIVR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 222 "JIT.lss"

/* JIT_DIVI(INTEGER,INTEGER,LONG)POINTER */
JIT_DIVI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 223 "JIT.lss"

/* JIT_DIVI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_DIVI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divi_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 224 "JIT.lss"

/* JIT_DIVI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_DIVI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divi_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 225 "JIT.lss"

/* JIT_DIVI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_DIVI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_divi_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 226 "JIT.lss"

/* JIT_REMR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_REMR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_remr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 227 "JIT.lss"

/* JIT_REMR_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_REMR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_remr_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 228 "JIT.lss"

/* JIT_REMI(INTEGER,INTEGER,LONG)POINTER */
JIT_REMI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_remi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 229 "JIT.lss"

/* JIT_REMI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_REMI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_remi_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 230 "JIT.lss"

/* JIT_ANDR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ANDR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_andr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 231 "JIT.lss"

/* JIT_ANDI(INTEGER,INTEGER,LONG)POINTER */
JIT_ANDI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_andi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 232 "JIT.lss"

/* JIT_ORR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ORR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_orr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 233 "JIT.lss"

/* JIT_ORI(INTEGER,INTEGER,LONG)POINTER */
JIT_ORI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ori((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 234 "JIT.lss"

/* JIT_XORR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_XORR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_xorr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 235 "JIT.lss"

/* JIT_XORI(INTEGER,INTEGER,LONG)POINTER */
JIT_XORI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_xori((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 236 "JIT.lss"

/* JIT_LSHR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LSHR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lshr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 237 "JIT.lss"

/* JIT_LSHI(INTEGER,INTEGER,LONG)POINTER */
JIT_LSHI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lshi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 238 "JIT.lss"

/* JIT_RSHR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_RSHR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_rshr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 239 "JIT.lss"

/* JIT_RSHR_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_RSHR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_rshr_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 240 "JIT.lss"

/* JIT_RSHI(INTEGER,INTEGER,LONG)POINTER */
JIT_RSHI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_rshi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 241 "JIT.lss"

/* JIT_RSHI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_RSHI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_rshi_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 242 "JIT.lss"

/* JIT_NEGR(INTEGER,INTEGER)POINTER */
JIT_NEGR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_negr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 243 "JIT.lss"

/* JIT_NEGR_F(INTEGER,INTEGER)POINTER */
JIT_NEGR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_negr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 244 "JIT.lss"

/* JIT_NEGR_D(INTEGER,INTEGER)POINTER */
JIT_NEGR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_negr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 245 "JIT.lss"

/* JIT_COMR(INTEGER,INTEGER)POINTER */
JIT_COMR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_comr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 246 "JIT.lss"

/* JIT_ABSR_F(INTEGER,INTEGER)POINTER */
JIT_ABSR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_absr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 247 "JIT.lss"

/* JIT_ABSR_D(INTEGER,INTEGER)POINTER */
JIT_ABSR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_absr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 248 "JIT.lss"

/* JIT_SQRTR_F(INTEGER,INTEGER)POINTER */
JIT_SQRTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sqrtr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 249 "JIT.lss"

/* JIT_SQRTR_D(INTEGER,INTEGER)POINTER */
JIT_SQRTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sqrtr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 250 "JIT.lss"

/* JIT_LTR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 251 "JIT.lss"

/* JIT_LTR_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltr_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 252 "JIT.lss"

/* JIT_LTR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 253 "JIT.lss"

/* JIT_LTR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 254 "JIT.lss"

/* JIT_LTI(INTEGER,INTEGER,LONG)POINTER */
JIT_LTI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lti((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 255 "JIT.lss"

/* JIT_LTI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_LTI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lti_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 256 "JIT.lss"

/* JIT_LTI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_LTI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lti_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 257 "JIT.lss"

/* JIT_LTI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_LTI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lti_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 258 "JIT.lss"

/* JIT_LER(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ler((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 259 "JIT.lss"

/* JIT_LER_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LER_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ler_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 260 "JIT.lss"

/* JIT_LER_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ler_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 261 "JIT.lss"

/* JIT_LER_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ler_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 262 "JIT.lss"

/* JIT_LEI(INTEGER,INTEGER,LONG)POINTER */
JIT_LEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lei((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 263 "JIT.lss"

/* JIT_LEI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_LEI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lei_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 264 "JIT.lss"

/* JIT_LEI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_LEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lei_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 265 "JIT.lss"

/* JIT_LEI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_LEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_lei_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 266 "JIT.lss"

/* JIT_GTR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GTR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gtr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 267 "JIT.lss"

/* JIT_GTR_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GTR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gtr_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 268 "JIT.lss"

/* JIT_GTR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gtr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 269 "JIT.lss"

/* JIT_GTR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gtr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 270 "JIT.lss"

/* JIT_GTI(INTEGER,INTEGER,LONG)POINTER */
JIT_GTI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gti((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 271 "JIT.lss"

/* JIT_GTI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_GTI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gti_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 272 "JIT.lss"

/* JIT_GTI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_GTI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gti_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 273 "JIT.lss"

/* JIT_GTI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_GTI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gti_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 274 "JIT.lss"

/* JIT_GER(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ger((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 275 "JIT.lss"

/* JIT_GER_U(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GER_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ger_u((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 276 "JIT.lss"

/* JIT_GER_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ger_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 277 "JIT.lss"

/* JIT_GER_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_GER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ger_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 278 "JIT.lss"

/* JIT_GEI(INTEGER,INTEGER,LONG)POINTER */
JIT_GEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gei((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 279 "JIT.lss"

/* JIT_GEI_U(INTEGER,INTEGER,LONG)POINTER */
JIT_GEI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gei_u((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 280 "JIT.lss"

/* JIT_GEI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_GEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gei_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 281 "JIT.lss"

/* JIT_GEI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_GEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_gei_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 282 "JIT.lss"

/* JIT_EQR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_EQR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 283 "JIT.lss"

/* JIT_EQR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_EQR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 284 "JIT.lss"

/* JIT_EQR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_EQR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 285 "JIT.lss"

/* JIT_EQI(INTEGER,INTEGER,LONG)POINTER */
JIT_EQI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqi((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 286 "JIT.lss"

/* JIT_EQI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_EQI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqi_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 287 "JIT.lss"

/* JIT_EQI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_EQI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_eqi_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 288 "JIT.lss"

/* JIT_NER(INTEGER,INTEGER,INTEGER)POINTER */
JIT_NER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ner((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 289 "JIT.lss"

/* JIT_NER_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_NER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ner_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 290 "JIT.lss"

/* JIT_NER_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_NER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ner_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 291 "JIT.lss"

/* JIT_NEI(INTEGER,INTEGER,LONG)POINTER */
JIT_NEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_nei((int)LA_INT(0),(int)LA_INT(1),(long)LA_INT(2)));
}
#line 292 "JIT.lss"

/* JIT_NEI_F(INTEGER,INTEGER,REAL)POINTER */
JIT_NEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_nei_f((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 293 "JIT.lss"

/* JIT_NEI_D(INTEGER,INTEGER,REAL)POINTER */
JIT_NEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_nei_d((int)LA_INT(0),(int)LA_INT(1),(double)LA_REAL(2)));
}
#line 294 "JIT.lss"

/* JIT_UNLTR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNLTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unltr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 295 "JIT.lss"

/* JIT_UNLTR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNLTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unltr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 296 "JIT.lss"

/* JIT_UNLER_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNLER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unler_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 297 "JIT.lss"

/* JIT_UNLER_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNLER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unler_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 298 "JIT.lss"

/* JIT_UNGTR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNGTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ungtr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 299 "JIT.lss"

/* JIT_UNGTR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNGTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ungtr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 300 "JIT.lss"

/* JIT_UNGER_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNGER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unger_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 301 "JIT.lss"

/* JIT_UNGER_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNGER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unger_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 302 "JIT.lss"

/* JIT_UNEQR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNEQR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_uneqr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 303 "JIT.lss"

/* JIT_UNEQR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNEQR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_uneqr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 304 "JIT.lss"

/* JIT_LTGTR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTGTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltgtr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 305 "JIT.lss"

/* JIT_LTGTR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LTGTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ltgtr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 306 "JIT.lss"

/* JIT_ORDR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ORDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ordr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 307 "JIT.lss"

/* JIT_ORDR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_ORDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ordr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 308 "JIT.lss"

/* JIT_UNORDR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNORDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unordr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 309 "JIT.lss"

/* JIT_UNORDR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_UNORDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_unordr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 310 "JIT.lss"

/* JIT_MOVR(INTEGER,INTEGER)POINTER */
JIT_MOVR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 311 "JIT.lss"

/* JIT_MOVR_F(INTEGER,INTEGER)POINTER */
JIT_MOVR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 312 "JIT.lss"

/* JIT_MOVR_D(INTEGER,INTEGER)POINTER */
JIT_MOVR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 313 "JIT.lss"

/* JIT_MOVI(INTEGER,LONG)POINTER */
JIT_MOVI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 314 "JIT.lss"

/* JIT_MOVI_F(INTEGER,REAL)POINTER */
JIT_MOVI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movi_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 315 "JIT.lss"

/* JIT_MOVI_D(INTEGER,REAL)POINTER */
JIT_MOVI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_movi_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 316 "JIT.lss"

/* JIT_EXTR_C(INTEGER,INTEGER)POINTER */
JIT_EXTR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_c((int)LA_INT(0),(int)LA_INT(1)));
}
#line 317 "JIT.lss"

/* JIT_EXTR_UC(INTEGER,INTEGER)POINTER */
JIT_EXTR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_uc((int)LA_INT(0),(int)LA_INT(1)));
}
#line 318 "JIT.lss"

/* JIT_EXTR_S(INTEGER,INTEGER)POINTER */
JIT_EXTR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_s((int)LA_INT(0),(int)LA_INT(1)));
}
#line 319 "JIT.lss"

/* JIT_EXTR_US(INTEGER,INTEGER)POINTER */
JIT_EXTR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_us((int)LA_INT(0),(int)LA_INT(1)));
}
#line 320 "JIT.lss"

/* JIT_EXTR_I(INTEGER,INTEGER)POINTER */
JIT_EXTR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_i((int)LA_INT(0),(int)LA_INT(1)));
}
#line 321 "JIT.lss"

/* JIT_EXTR_UI(INTEGER,INTEGER)POINTER */
JIT_EXTR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_ui((int)LA_INT(0),(int)LA_INT(1)));
}
#line 322 "JIT.lss"

/* JIT_EXTR_F(INTEGER,INTEGER)POINTER */
JIT_EXTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 323 "JIT.lss"

/* JIT_EXTR_D_F(INTEGER,INTEGER)POINTER */
JIT_EXTR_D_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_d_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 324 "JIT.lss"

/* JIT_EXTR_D(INTEGER,INTEGER)POINTER */
JIT_EXTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 325 "JIT.lss"

/* JIT_EXTR_F_D(INTEGER,INTEGER)POINTER */
JIT_EXTR_F_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_extr_f_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 326 "JIT.lss"

/* JIT_TRUNCR_F_I(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_F_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_f_i((int)LA_INT(0),(int)LA_INT(1)));
}
#line 327 "JIT.lss"

/* JIT_TRUNCR_F(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 328 "JIT.lss"

/* JIT_TRUNCR_F_L(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_F_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_f_l((int)LA_INT(0),(int)LA_INT(1)));
}
#line 329 "JIT.lss"

/* JIT_TRUNCR_D_I(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_D_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_d_i((int)LA_INT(0),(int)LA_INT(1)));
}
#line 330 "JIT.lss"

/* JIT_TRUNCR_D(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 331 "JIT.lss"

/* JIT_TRUNCR_D_L(INTEGER,INTEGER)POINTER */
JIT_TRUNCR_D_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_truncr_d_l((int)LA_INT(0),(int)LA_INT(1)));
}
#line 332 "JIT.lss"

/* JIT_HTONR(INTEGER,INTEGER)POINTER */
JIT_HTONR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_htonr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 333 "JIT.lss"

/* JIT_NTOHR(INTEGER,INTEGER)POINTER */
JIT_NTOHR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ntohr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 334 "JIT.lss"

/* JIT_LDR(INTEGER,INTEGER)POINTER */
JIT_LDR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 335 "JIT.lss"

/* JIT_LDR_C(INTEGER,INTEGER)POINTER */
JIT_LDR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_c((int)LA_INT(0),(int)LA_INT(1)));
}
#line 336 "JIT.lss"

/* JIT_LDR_UC(INTEGER,INTEGER)POINTER */
JIT_LDR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_uc((int)LA_INT(0),(int)LA_INT(1)));
}
#line 337 "JIT.lss"

/* JIT_LDR_S(INTEGER,INTEGER)POINTER */
JIT_LDR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_s((int)LA_INT(0),(int)LA_INT(1)));
}
#line 338 "JIT.lss"

/* JIT_LDR_US(INTEGER,INTEGER)POINTER */
JIT_LDR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_us((int)LA_INT(0),(int)LA_INT(1)));
}
#line 339 "JIT.lss"

/* JIT_LDR_I(INTEGER,INTEGER)POINTER */
JIT_LDR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_i((int)LA_INT(0),(int)LA_INT(1)));
}
#line 340 "JIT.lss"

/* JIT_LDR_UI(INTEGER,INTEGER)POINTER */
JIT_LDR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_ui((int)LA_INT(0),(int)LA_INT(1)));
}
#line 341 "JIT.lss"

/* JIT_LDR_L(INTEGER,INTEGER)POINTER */
JIT_LDR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_l((int)LA_INT(0),(int)LA_INT(1)));
}
#line 342 "JIT.lss"

/* JIT_LDR_F(INTEGER,INTEGER)POINTER */
JIT_LDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 343 "JIT.lss"

/* JIT_LDR_D(INTEGER,INTEGER)POINTER */
JIT_LDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 344 "JIT.lss"

/* JIT_LDI(INTEGER,POINTER)POINTER */
JIT_LDI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 345 "JIT.lss"

/* JIT_LDI_C(INTEGER,POINTER)POINTER */
JIT_LDI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_c((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 346 "JIT.lss"

/* JIT_LDI_UC(INTEGER,POINTER)POINTER */
JIT_LDI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_uc((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 347 "JIT.lss"

/* JIT_LDI_S(INTEGER,POINTER)POINTER */
JIT_LDI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_s((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 348 "JIT.lss"

/* JIT_LDI_US(INTEGER,POINTER)POINTER */
JIT_LDI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_us((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 349 "JIT.lss"

/* JIT_LDI_I(INTEGER,POINTER)POINTER */
JIT_LDI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_i((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 350 "JIT.lss"

/* JIT_LDI_UI(INTEGER,POINTER)POINTER */
JIT_LDI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_ui((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 351 "JIT.lss"

/* JIT_LDI_L(INTEGER,POINTER)POINTER */
JIT_LDI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_l((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 352 "JIT.lss"

/* JIT_LDI_F(INTEGER,POINTER)POINTER */
JIT_LDI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_f((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 353 "JIT.lss"

/* JIT_LDI_D(INTEGER,POINTER)POINTER */
JIT_LDI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldi_d((int)LA_INT(0),(void *)(long)LA_INT(1)));
}
#line 354 "JIT.lss"

/* JIT_LDXR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 355 "JIT.lss"

/* JIT_LDXR_C(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_c((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 356 "JIT.lss"

/* JIT_LDXR_UC(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_uc((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 357 "JIT.lss"

/* JIT_LDXR_S(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_s((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 358 "JIT.lss"

/* JIT_LDXR_US(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_us((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 359 "JIT.lss"

/* JIT_LDXR_I(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_i((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 360 "JIT.lss"

/* JIT_LDXR_UI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_ui((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 361 "JIT.lss"

/* JIT_LDXR_L(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_l((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 362 "JIT.lss"

/* JIT_LDXR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 363 "JIT.lss"

/* JIT_LDXR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 364 "JIT.lss"

/* JIT_LDXI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 365 "JIT.lss"

/* JIT_LDXI_C(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_c((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 366 "JIT.lss"

/* JIT_LDXI_UC(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_uc((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 367 "JIT.lss"

/* JIT_LDXI_S(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_s((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 368 "JIT.lss"

/* JIT_LDXI_US(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_us((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 369 "JIT.lss"

/* JIT_LDXI_I(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_i((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 370 "JIT.lss"

/* JIT_LDXI_UI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_ui((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 371 "JIT.lss"

/* JIT_LDXI_L(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_l((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 372 "JIT.lss"

/* JIT_LDXI_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 373 "JIT.lss"

/* JIT_LDXI_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_LDXI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_ldxi_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 374 "JIT.lss"

/* JIT_STR(INTEGER,INTEGER)POINTER */
JIT_STR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str((int)LA_INT(0),(int)LA_INT(1)));
}
#line 375 "JIT.lss"

/* JIT_STR_C(INTEGER,INTEGER)POINTER */
JIT_STR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_c((int)LA_INT(0),(int)LA_INT(1)));
}
#line 376 "JIT.lss"

/* JIT_STR_UC(INTEGER,INTEGER)POINTER */
JIT_STR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_uc((int)LA_INT(0),(int)LA_INT(1)));
}
#line 377 "JIT.lss"

/* JIT_STR_S(INTEGER,INTEGER)POINTER */
JIT_STR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_s((int)LA_INT(0),(int)LA_INT(1)));
}
#line 378 "JIT.lss"

/* JIT_STR_US(INTEGER,INTEGER)POINTER */
JIT_STR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_us((int)LA_INT(0),(int)LA_INT(1)));
}
#line 379 "JIT.lss"

/* JIT_STR_I(INTEGER,INTEGER)POINTER */
JIT_STR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_i((int)LA_INT(0),(int)LA_INT(1)));
}
#line 380 "JIT.lss"

/* JIT_STR_UI(INTEGER,INTEGER)POINTER */
JIT_STR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_ui((int)LA_INT(0),(int)LA_INT(1)));
}
#line 381 "JIT.lss"

/* JIT_STR_L(INTEGER,INTEGER)POINTER */
JIT_STR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_l((int)LA_INT(0),(int)LA_INT(1)));
}
#line 382 "JIT.lss"

/* JIT_STR_F(INTEGER,INTEGER)POINTER */
JIT_STR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 383 "JIT.lss"

/* JIT_STR_D(INTEGER,INTEGER)POINTER */
JIT_STR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_str_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 384 "JIT.lss"

/* JIT_STI(POINTER,INTEGER)POINTER */
JIT_STI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 385 "JIT.lss"

/* JIT_STI_C(POINTER,INTEGER)POINTER */
JIT_STI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_c((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 386 "JIT.lss"

/* JIT_STI_UC(POINTER,INTEGER)POINTER */
JIT_STI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_uc((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 387 "JIT.lss"

/* JIT_STI_S(POINTER,INTEGER)POINTER */
JIT_STI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_s((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 388 "JIT.lss"

/* JIT_STI_US(POINTER,INTEGER)POINTER */
JIT_STI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_us((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 389 "JIT.lss"

/* JIT_STI_I(POINTER,INTEGER)POINTER */
JIT_STI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_i((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 390 "JIT.lss"

/* JIT_STI_UI(POINTER,INTEGER)POINTER */
JIT_STI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_ui((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 391 "JIT.lss"

/* JIT_STI_L(POINTER,INTEGER)POINTER */
JIT_STI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_l((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 392 "JIT.lss"

/* JIT_STI_F(POINTER,INTEGER)POINTER */
JIT_STI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_f((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 393 "JIT.lss"

/* JIT_STI_D(POINTER,INTEGER)POINTER */
JIT_STI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_sti_d((void *)(long)LA_INT(0),(int)LA_INT(1)));
}
#line 394 "JIT.lss"

/* JIT_STXR(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 395 "JIT.lss"

/* JIT_STXR_C(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_c((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 396 "JIT.lss"

/* JIT_STXR_UC(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_uc((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 397 "JIT.lss"

/* JIT_STXR_S(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_s((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 398 "JIT.lss"

/* JIT_STXR_US(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_us((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 399 "JIT.lss"

/* JIT_STXR_I(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_i((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 400 "JIT.lss"

/* JIT_STXR_UI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_ui((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 401 "JIT.lss"

/* JIT_STXR_L(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_l((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 402 "JIT.lss"

/* JIT_STXR_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 403 "JIT.lss"

/* JIT_STXR_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxr_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 404 "JIT.lss"

/* JIT_STXI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 405 "JIT.lss"

/* JIT_STXI_C(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_c((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 406 "JIT.lss"

/* JIT_STXI_UC(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_uc((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 407 "JIT.lss"

/* JIT_STXI_S(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_s((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 408 "JIT.lss"

/* JIT_STXI_US(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_us((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 409 "JIT.lss"

/* JIT_STXI_I(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_i((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 410 "JIT.lss"

/* JIT_STXI_UI(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_ui((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 411 "JIT.lss"

/* JIT_STXI_L(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_l((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 412 "JIT.lss"

/* JIT_STXI_F(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_f((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 413 "JIT.lss"

/* JIT_STXI_D(INTEGER,INTEGER,INTEGER)POINTER */
JIT_STXI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_stxi_d((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2)));
}
#line 414 "JIT.lss"

/* JIT_PUSHARGR(INTEGER) */
JIT_PUSHARGR( LA_ALIST ) LA_DCL
{
    jit_pushargr((int)LA_INT(0));
    RETNULL;
}
#line 415 "JIT.lss"

/* JIT_PUSHARGR_C(INTEGER)POINTER */
JIT_PUSHARGR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_c((int)LA_INT(0)));
}
#line 416 "JIT.lss"

/* JIT_PUSHARGR_UC(INTEGER)POINTER */
JIT_PUSHARGR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_uc((int)LA_INT(0)));
}
#line 417 "JIT.lss"

/* JIT_PUSHARGR_S(INTEGER)POINTER */
JIT_PUSHARGR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_s((int)LA_INT(0)));
}
#line 418 "JIT.lss"

/* JIT_PUSHARGR_US(INTEGER)POINTER */
JIT_PUSHARGR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_us((int)LA_INT(0)));
}
#line 419 "JIT.lss"

/* JIT_PUSHARGR_I(INTEGER)POINTER */
JIT_PUSHARGR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_i((int)LA_INT(0)));
}
#line 420 "JIT.lss"

/* JIT_PUSHARGR_UI(INTEGER)POINTER */
JIT_PUSHARGR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_ui((int)LA_INT(0)));
}
#line 421 "JIT.lss"

/* JIT_PUSHARGR_L(INTEGER)POINTER */
JIT_PUSHARGR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargr_l((int)LA_INT(0)));
}
#line 422 "JIT.lss"

/* JIT_PUSHARGR_F(INTEGER) */
JIT_PUSHARGR_F( LA_ALIST ) LA_DCL
{
    jit_pushargr_f((int)LA_INT(0));
    RETNULL;
}
#line 423 "JIT.lss"

/* JIT_PUSHARGR_D(INTEGER) */
JIT_PUSHARGR_D( LA_ALIST ) LA_DCL
{
    jit_pushargr_d((int)LA_INT(0));
    RETNULL;
}
#line 424 "JIT.lss"

/* JIT_PUSHARGI(INTEGER) */
JIT_PUSHARGI( LA_ALIST ) LA_DCL
{
    jit_pushargi((int)LA_INT(0));
    RETNULL;
}
#line 425 "JIT.lss"

/* JIT_PUSHARGI_C(INTEGER)POINTER */
JIT_PUSHARGI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_c((int)LA_INT(0)));
}
#line 426 "JIT.lss"

/* JIT_PUSHARGI_UC(INTEGER)POINTER */
JIT_PUSHARGI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_uc((int)LA_INT(0)));
}
#line 427 "JIT.lss"

/* JIT_PUSHARGI_S(INTEGER)POINTER */
JIT_PUSHARGI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_s((int)LA_INT(0)));
}
#line 428 "JIT.lss"

/* JIT_PUSHARGI_US(INTEGER)POINTER */
JIT_PUSHARGI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_us((int)LA_INT(0)));
}
#line 429 "JIT.lss"

/* JIT_PUSHARGI_I(INTEGER)POINTER */
JIT_PUSHARGI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_i((int)LA_INT(0)));
}
#line 430 "JIT.lss"

/* JIT_PUSHARGI_UI(INTEGER)POINTER */
JIT_PUSHARGI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_ui((int)LA_INT(0)));
}
#line 431 "JIT.lss"

/* JIT_PUSHARGI_L(LONG)POINTER */
JIT_PUSHARGI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_pushargi_l((long)LA_INT(0)));
}
#line 432 "JIT.lss"

/* JIT_PUSHARGI_F(REAL) */
JIT_PUSHARGI_F( LA_ALIST ) LA_DCL
{
    jit_pushargi_f((double)LA_REAL(0));
    RETNULL;
}
#line 433 "JIT.lss"

/* JIT_PUSHARGI_D(REAL) */
JIT_PUSHARGI_D( LA_ALIST ) LA_DCL
{
    jit_pushargi_d((double)LA_REAL(0));
    RETNULL;
}
#line 434 "JIT.lss"

/* JIT_ARG()POINTER */
JIT_ARG( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg());
}
#line 435 "JIT.lss"

/* JIT_ARG_C(INTEGER)POINTER */
JIT_ARG_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_c((int)LA_INT(0)));
}
#line 436 "JIT.lss"

/* JIT_ARG_UC(INTEGER)POINTER */
JIT_ARG_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_uc((int)LA_INT(0)));
}
#line 437 "JIT.lss"

/* JIT_ARG_S(INTEGER)POINTER */
JIT_ARG_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_s((int)LA_INT(0)));
}
#line 438 "JIT.lss"

/* JIT_ARG_US(INTEGER)POINTER */
JIT_ARG_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_us((int)LA_INT(0)));
}
#line 439 "JIT.lss"

/* JIT_ARG_I(INTEGER)POINTER */
JIT_ARG_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_i((int)LA_INT(0)));
}
#line 440 "JIT.lss"

/* JIT_ARG_UI(INTEGER)POINTER */
JIT_ARG_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_ui((int)LA_INT(0)));
}
#line 441 "JIT.lss"

/* JIT_ARG_L(INTEGER)POINTER */
JIT_ARG_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_l((int)LA_INT(0)));
}
#line 442 "JIT.lss"

/* JIT_ARG_F()POINTER */
JIT_ARG_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_f());
}
#line 443 "JIT.lss"

/* JIT_ARG_D()POINTER */
JIT_ARG_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_arg_d());
}
#line 444 "JIT.lss"

/* JIT_GETARG(INTEGER,POINTER) */
JIT_GETARG( LA_ALIST ) LA_DCL
{
    jit_getarg((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 445 "JIT.lss"

/* JIT_GETARG_C(INTEGER,POINTER) */
JIT_GETARG_C( LA_ALIST ) LA_DCL
{
    jit_getarg_c((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 446 "JIT.lss"

/* JIT_GETARG_UC(INTEGER,POINTER) */
JIT_GETARG_UC( LA_ALIST ) LA_DCL
{
    jit_getarg_uc((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 447 "JIT.lss"

/* JIT_GETARG_S(INTEGER,POINTER) */
JIT_GETARG_S( LA_ALIST ) LA_DCL
{
    jit_getarg_s((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 448 "JIT.lss"

/* JIT_GETARG_US(INTEGER,POINTER) */
JIT_GETARG_US( LA_ALIST ) LA_DCL
{
    jit_getarg_us((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 449 "JIT.lss"

/* JIT_GETARG_I(INTEGER,POINTER) */
JIT_GETARG_I( LA_ALIST ) LA_DCL
{
    jit_getarg_i((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 450 "JIT.lss"

/* JIT_GETARG_UI(INTEGER,POINTER) */
JIT_GETARG_UI( LA_ALIST ) LA_DCL
{
    jit_getarg_ui((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 451 "JIT.lss"

/* JIT_GETARG_L(INTEGER,POINTER) */
JIT_GETARG_L( LA_ALIST ) LA_DCL
{
    jit_getarg_l((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 452 "JIT.lss"

/* JIT_GETARG_F(INTEGER,POINTER) */
JIT_GETARG_F( LA_ALIST ) LA_DCL
{
    jit_getarg_f((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 453 "JIT.lss"

/* JIT_GETARG_D(INTEGER,POINTER) */
JIT_GETARG_D( LA_ALIST ) LA_DCL
{
    jit_getarg_d((int)LA_INT(0),(void *)(long)LA_INT(1));
    RETNULL;
}
#line 454 "JIT.lss"

/* JIT_RET() */
JIT_RET( LA_ALIST ) LA_DCL
{
    jit_ret();
    RETNULL;
}
#line 455 "JIT.lss"

/* JIT_RETR(INTEGER) */
JIT_RETR( LA_ALIST ) LA_DCL
{
    jit_retr((int)LA_INT(0));
    RETNULL;
}
#line 456 "JIT.lss"

/* JIT_RETR_C(INTEGER)POINTER */
JIT_RETR_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_c((int)LA_INT(0)));
}
#line 457 "JIT.lss"

/* JIT_RETR_UC(INTEGER)POINTER */
JIT_RETR_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_uc((int)LA_INT(0)));
}
#line 458 "JIT.lss"

/* JIT_RETR_S(INTEGER)POINTER */
JIT_RETR_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_s((int)LA_INT(0)));
}
#line 459 "JIT.lss"

/* JIT_RETR_US(INTEGER)POINTER */
JIT_RETR_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_us((int)LA_INT(0)));
}
#line 460 "JIT.lss"

/* JIT_RETR_I(INTEGER)POINTER */
JIT_RETR_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_i((int)LA_INT(0)));
}
#line 461 "JIT.lss"

/* JIT_RETR_UI(INTEGER)POINTER */
JIT_RETR_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_ui((int)LA_INT(0)));
}
#line 462 "JIT.lss"

/* JIT_RETR_L(INTEGER)POINTER */
JIT_RETR_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_retr_l((int)LA_INT(0)));
}
#line 463 "JIT.lss"

/* JIT_RETR_F(INTEGER) */
JIT_RETR_F( LA_ALIST ) LA_DCL
{
    jit_retr_f((int)LA_INT(0));
    RETNULL;
}
#line 464 "JIT.lss"

/* JIT_RETR_D(INTEGER) */
JIT_RETR_D( LA_ALIST ) LA_DCL
{
    jit_retr_d((int)LA_INT(0));
    RETNULL;
}
#line 465 "JIT.lss"

/* JIT_RETI(INTEGER) */
JIT_RETI( LA_ALIST ) LA_DCL
{
    jit_reti((int)LA_INT(0));
    RETNULL;
}
#line 466 "JIT.lss"

/* JIT_RETI_C(INTEGER)POINTER */
JIT_RETI_C( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_c((int)LA_INT(0)));
}
#line 467 "JIT.lss"

/* JIT_RETI_UC(INTEGER)POINTER */
JIT_RETI_UC( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_uc((int)LA_INT(0)));
}
#line 468 "JIT.lss"

/* JIT_RETI_S(INTEGER)POINTER */
JIT_RETI_S( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_s((int)LA_INT(0)));
}
#line 469 "JIT.lss"

/* JIT_RETI_US(INTEGER)POINTER */
JIT_RETI_US( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_us((int)LA_INT(0)));
}
#line 470 "JIT.lss"

/* JIT_RETI_I(INTEGER)POINTER */
JIT_RETI_I( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_i((int)LA_INT(0)));
}
#line 471 "JIT.lss"

/* JIT_RETI_UI(INTEGER)POINTER */
JIT_RETI_UI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_ui((int)LA_INT(0)));
}
#line 472 "JIT.lss"

/* JIT_RETI_L(LONG)POINTER */
JIT_RETI_L( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_reti_l((long)LA_INT(0)));
}
#line 473 "JIT.lss"

/* JIT_RETI_F(REAL) */
JIT_RETI_F( LA_ALIST ) LA_DCL
{
    jit_reti_f((double)LA_REAL(0));
    RETNULL;
}
#line 474 "JIT.lss"

/* JIT_RETI_D(REAL) */
JIT_RETI_D( LA_ALIST ) LA_DCL
{
    jit_reti_d((double)LA_REAL(0));
    RETNULL;
}
#line 475 "JIT.lss"

/* JIT_RETVAL(INTEGER) */
JIT_RETVAL( LA_ALIST ) LA_DCL
{
    jit_retval((int)LA_INT(0));
    RETNULL;
}
#line 476 "JIT.lss"

/* JIT_RETVAL_C(INTEGER) */
JIT_RETVAL_C( LA_ALIST ) LA_DCL
{
    jit_retval_c((int)LA_INT(0));
    RETNULL;
}
#line 477 "JIT.lss"

/* JIT_RETVAL_UC(INTEGER) */
JIT_RETVAL_UC( LA_ALIST ) LA_DCL
{
    jit_retval_uc((int)LA_INT(0));
    RETNULL;
}
#line 478 "JIT.lss"

/* JIT_RETVAL_S(INTEGER) */
JIT_RETVAL_S( LA_ALIST ) LA_DCL
{
    jit_retval_s((int)LA_INT(0));
    RETNULL;
}
#line 479 "JIT.lss"

/* JIT_RETVAL_US(INTEGER) */
JIT_RETVAL_US( LA_ALIST ) LA_DCL
{
    jit_retval_us((int)LA_INT(0));
    RETNULL;
}
#line 480 "JIT.lss"

/* JIT_RETVAL_I(INTEGER) */
JIT_RETVAL_I( LA_ALIST ) LA_DCL
{
    jit_retval_i((int)LA_INT(0));
    RETNULL;
}
#line 481 "JIT.lss"

/* JIT_RETVAL_UI(INTEGER) */
JIT_RETVAL_UI( LA_ALIST ) LA_DCL
{
    jit_retval_ui((int)LA_INT(0));
    RETNULL;
}
#line 482 "JIT.lss"

/* JIT_RETVAL_L(INTEGER) */
JIT_RETVAL_L( LA_ALIST ) LA_DCL
{
    jit_retval_l((int)LA_INT(0));
    RETNULL;
}
#line 483 "JIT.lss"

/* JIT_RETVAL_F(INTEGER) */
JIT_RETVAL_F( LA_ALIST ) LA_DCL
{
    jit_retval_f((int)LA_INT(0));
    RETNULL;
}
#line 484 "JIT.lss"

/* JIT_RETVAL_D(INTEGER) */
JIT_RETVAL_D( LA_ALIST ) LA_DCL
{
    jit_retval_d((int)LA_INT(0));
    RETNULL;
}
#line 485 "JIT.lss"

/* JIT_BLTR(INTEGER,INTEGER)POINTER */
JIT_BLTR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 486 "JIT.lss"

/* JIT_BLTR_U(INTEGER,INTEGER)POINTER */
JIT_BLTR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 487 "JIT.lss"

/* JIT_BLTR_F(INTEGER,INTEGER)POINTER */
JIT_BLTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 488 "JIT.lss"

/* JIT_BLTR_D(INTEGER,INTEGER)POINTER */
JIT_BLTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 489 "JIT.lss"

/* JIT_BLTI(INTEGER,LONG)POINTER */
JIT_BLTI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blti((int)LA_INT(0),(long)LA_INT(1)));
}
#line 490 "JIT.lss"

/* JIT_BLTI_U(INTEGER,LONG)POINTER */
JIT_BLTI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blti_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 491 "JIT.lss"

/* JIT_BLTI_F(INTEGER,REAL)POINTER */
JIT_BLTI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blti_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 492 "JIT.lss"

/* JIT_BLTI_D(INTEGER,REAL)POINTER */
JIT_BLTI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blti_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 493 "JIT.lss"

/* JIT_BLER(INTEGER,INTEGER)POINTER */
JIT_BLER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bler((int)LA_INT(0),(int)LA_INT(1)));
}
#line 494 "JIT.lss"

/* JIT_BLER_U(INTEGER,INTEGER)POINTER */
JIT_BLER_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bler_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 495 "JIT.lss"

/* JIT_BLER_F(INTEGER,INTEGER)POINTER */
JIT_BLER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bler_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 496 "JIT.lss"

/* JIT_BLER_D(INTEGER,INTEGER)POINTER */
JIT_BLER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bler_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 497 "JIT.lss"

/* JIT_BLEI(INTEGER,LONG)POINTER */
JIT_BLEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blei((int)LA_INT(0),(long)LA_INT(1)));
}
#line 498 "JIT.lss"

/* JIT_BLEI_U(INTEGER,LONG)POINTER */
JIT_BLEI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blei_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 499 "JIT.lss"

/* JIT_BLEI_F(INTEGER,REAL)POINTER */
JIT_BLEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blei_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 500 "JIT.lss"

/* JIT_BLEI_D(INTEGER,REAL)POINTER */
JIT_BLEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_blei_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 501 "JIT.lss"

/* JIT_BGTR(INTEGER,INTEGER)POINTER */
JIT_BGTR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgtr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 502 "JIT.lss"

/* JIT_BGTR_U(INTEGER,INTEGER)POINTER */
JIT_BGTR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgtr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 503 "JIT.lss"

/* JIT_BGTR_F(INTEGER,INTEGER)POINTER */
JIT_BGTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgtr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 504 "JIT.lss"

/* JIT_BGTR_D(INTEGER,INTEGER)POINTER */
JIT_BGTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgtr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 505 "JIT.lss"

/* JIT_BGTI(INTEGER,LONG)POINTER */
JIT_BGTI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgti((int)LA_INT(0),(long)LA_INT(1)));
}
#line 506 "JIT.lss"

/* JIT_BGTI_U(INTEGER,LONG)POINTER */
JIT_BGTI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgti_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 507 "JIT.lss"

/* JIT_BGTI_F(INTEGER,REAL)POINTER */
JIT_BGTI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgti_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 508 "JIT.lss"

/* JIT_BGTI_D(INTEGER,REAL)POINTER */
JIT_BGTI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgti_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 509 "JIT.lss"

/* JIT_BGER(INTEGER,INTEGER)POINTER */
JIT_BGER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bger((int)LA_INT(0),(int)LA_INT(1)));
}
#line 510 "JIT.lss"

/* JIT_BGER_U(INTEGER,INTEGER)POINTER */
JIT_BGER_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bger_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 511 "JIT.lss"

/* JIT_BGER_F(INTEGER,INTEGER)POINTER */
JIT_BGER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bger_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 512 "JIT.lss"

/* JIT_BGER_D(INTEGER,INTEGER)POINTER */
JIT_BGER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bger_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 513 "JIT.lss"

/* JIT_BGEI(INTEGER,LONG)POINTER */
JIT_BGEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgei((int)LA_INT(0),(long)LA_INT(1)));
}
#line 514 "JIT.lss"

/* JIT_BGEI_U(INTEGER,LONG)POINTER */
JIT_BGEI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgei_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 515 "JIT.lss"

/* JIT_BGEI_F(INTEGER,REAL)POINTER */
JIT_BGEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgei_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 516 "JIT.lss"

/* JIT_BGEI_D(INTEGER,REAL)POINTER */
JIT_BGEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bgei_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 517 "JIT.lss"

/* JIT_BEQR(INTEGER,INTEGER)POINTER */
JIT_BEQR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 518 "JIT.lss"

/* JIT_BEQR_F(INTEGER,INTEGER)POINTER */
JIT_BEQR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 519 "JIT.lss"

/* JIT_BEQR_D(INTEGER,INTEGER)POINTER */
JIT_BEQR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 520 "JIT.lss"

/* JIT_BEQI(INTEGER,LONG)POINTER */
JIT_BEQI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 521 "JIT.lss"

/* JIT_BEQI_F(INTEGER,REAL)POINTER */
JIT_BEQI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqi_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 522 "JIT.lss"

/* JIT_BEQI_D(INTEGER,REAL)POINTER */
JIT_BEQI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_beqi_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 523 "JIT.lss"

/* JIT_BNER(INTEGER,INTEGER)POINTER */
JIT_BNER( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bner((int)LA_INT(0),(int)LA_INT(1)));
}
#line 524 "JIT.lss"

/* JIT_BNER_F(INTEGER,INTEGER)POINTER */
JIT_BNER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bner_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 525 "JIT.lss"

/* JIT_BNER_D(INTEGER,INTEGER)POINTER */
JIT_BNER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bner_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 526 "JIT.lss"

/* JIT_BNEI(INTEGER,LONG)POINTER */
JIT_BNEI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bnei((int)LA_INT(0),(long)LA_INT(1)));
}
#line 527 "JIT.lss"

/* JIT_BNEI_F(INTEGER,REAL)POINTER */
JIT_BNEI_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bnei_f((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 528 "JIT.lss"

/* JIT_BNEI_D(INTEGER,REAL)POINTER */
JIT_BNEI_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bnei_d((int)LA_INT(0),(double)LA_REAL(1)));
}
#line 529 "JIT.lss"

/* JIT_BUNLTR_F(INTEGER,INTEGER)POINTER */
JIT_BUNLTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunltr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 530 "JIT.lss"

/* JIT_BUNLTR_D(INTEGER,INTEGER)POINTER */
JIT_BUNLTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunltr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 531 "JIT.lss"

/* JIT_BUNLER_F(INTEGER,INTEGER)POINTER */
JIT_BUNLER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunler_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 532 "JIT.lss"

/* JIT_BUNLER_D(INTEGER,INTEGER)POINTER */
JIT_BUNLER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunler_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 533 "JIT.lss"

/* JIT_BUNGTR_F(INTEGER,INTEGER)POINTER */
JIT_BUNGTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bungtr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 534 "JIT.lss"

/* JIT_BUNGTR_D(INTEGER,INTEGER)POINTER */
JIT_BUNGTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bungtr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 535 "JIT.lss"

/* JIT_BUNGER_F(INTEGER,INTEGER)POINTER */
JIT_BUNGER_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunger_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 536 "JIT.lss"

/* JIT_BUNGER_D(INTEGER,INTEGER)POINTER */
JIT_BUNGER_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunger_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 537 "JIT.lss"

/* JIT_BUNEQR_F(INTEGER,INTEGER)POINTER */
JIT_BUNEQR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_buneqr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 538 "JIT.lss"

/* JIT_BUNEQR_D(INTEGER,INTEGER)POINTER */
JIT_BUNEQR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_buneqr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 539 "JIT.lss"

/* JIT_BLTGTR_F(INTEGER,INTEGER)POINTER */
JIT_BLTGTR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltgtr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 540 "JIT.lss"

/* JIT_BLTGTR_D(INTEGER,INTEGER)POINTER */
JIT_BLTGTR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bltgtr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 541 "JIT.lss"

/* JIT_BORDR_F(INTEGER,INTEGER)POINTER */
JIT_BORDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bordr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 542 "JIT.lss"

/* JIT_BORDR_D(INTEGER,INTEGER)POINTER */
JIT_BORDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bordr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 543 "JIT.lss"

/* JIT_BUNORDR_F(INTEGER,INTEGER)POINTER */
JIT_BUNORDR_F( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunordr_f((int)LA_INT(0),(int)LA_INT(1)));
}
#line 544 "JIT.lss"

/* JIT_BUNORDR_D(INTEGER,INTEGER)POINTER */
JIT_BUNORDR_D( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bunordr_d((int)LA_INT(0),(int)LA_INT(1)));
}
#line 545 "JIT.lss"

/* JIT_BMSR(INTEGER,INTEGER)POINTER */
JIT_BMSR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bmsr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 546 "JIT.lss"

/* JIT_BMSI(INTEGER,LONG)POINTER */
JIT_BMSI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bmsi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 547 "JIT.lss"

/* JIT_BMCR(INTEGER,INTEGER)POINTER */
JIT_BMCR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bmcr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 548 "JIT.lss"

/* JIT_BMCI(INTEGER,LONG)POINTER */
JIT_BMCI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bmci((int)LA_INT(0),(long)LA_INT(1)));
}
#line 549 "JIT.lss"

/* JIT_BOADDR(INTEGER,INTEGER)POINTER */
JIT_BOADDR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_boaddr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 550 "JIT.lss"

/* JIT_BOADDR_U(INTEGER,INTEGER)POINTER */
JIT_BOADDR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_boaddr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 551 "JIT.lss"

/* JIT_BOADDI(INTEGER,LONG)POINTER */
JIT_BOADDI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_boaddi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 552 "JIT.lss"

/* JIT_BOADDI_U(INTEGER,LONG)POINTER */
JIT_BOADDI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_boaddi_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 553 "JIT.lss"

/* JIT_BXADDR(INTEGER,INTEGER)POINTER */
JIT_BXADDR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxaddr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 554 "JIT.lss"

/* JIT_BXADDR_U(INTEGER,INTEGER)POINTER */
JIT_BXADDR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxaddr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 555 "JIT.lss"

/* JIT_BXADDI(INTEGER,LONG)POINTER */
JIT_BXADDI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxaddi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 556 "JIT.lss"

/* JIT_BXADDI_U(INTEGER,LONG)POINTER */
JIT_BXADDI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxaddi_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 557 "JIT.lss"

/* JIT_BOSUBR(INTEGER,INTEGER)POINTER */
JIT_BOSUBR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bosubr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 558 "JIT.lss"

/* JIT_BOSUBR_U(INTEGER,INTEGER)POINTER */
JIT_BOSUBR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bosubr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 559 "JIT.lss"

/* JIT_BOSUBI(INTEGER,LONG)POINTER */
JIT_BOSUBI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bosubi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 560 "JIT.lss"

/* JIT_BOSUBI_U(INTEGER,LONG)POINTER */
JIT_BOSUBI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bosubi_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 561 "JIT.lss"

/* JIT_BXSUBR(INTEGER,INTEGER)POINTER */
JIT_BXSUBR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxsubr((int)LA_INT(0),(int)LA_INT(1)));
}
#line 562 "JIT.lss"

/* JIT_BXSUBR_U(INTEGER,INTEGER)POINTER */
JIT_BXSUBR_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxsubr_u((int)LA_INT(0),(int)LA_INT(1)));
}
#line 563 "JIT.lss"

/* JIT_BXSUBI(INTEGER,LONG)POINTER */
JIT_BXSUBI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxsubi((int)LA_INT(0),(long)LA_INT(1)));
}
#line 564 "JIT.lss"

/* JIT_BXSUBI_U(INTEGER,LONG)POINTER */
JIT_BXSUBI_U( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_bxsubi_u((int)LA_INT(0),(long)LA_INT(1)));
}
#line 565 "JIT.lss"

/* JIT_CALLR(INTEGER)POINTER */
JIT_CALLR( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_callr((int)LA_INT(0)));
}
#line 566 "JIT.lss"

/* JIT_CALLI(POINTER)POINTER */
JIT_CALLI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_calli((void *)(long)LA_INT(0)));
}
#line 567 "JIT.lss"

/* JIT_FINISHR(INTEGER) */
JIT_FINISHR( LA_ALIST ) LA_DCL
{
    jit_finishr((int)LA_INT(0));
    RETNULL;
}
#line 568 "JIT.lss"

/* JIT_FINISHI(POINTER)POINTER */
JIT_FINISHI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_finishi((void *)(long)LA_INT(0)));
}
#line 569 "JIT.lss"

/* JIT_JMPR(INTEGER) */
JIT_JMPR( LA_ALIST ) LA_DCL
{
    jit_jmpr((int)LA_INT(0));
    RETNULL;
}
#line 570 "JIT.lss"

/* JIT_JMPI()POINTER */
JIT_JMPI( LA_ALIST ) LA_DCL
{
    RETINT((long)jit_jmpi());
}
#line 571 "JIT.lss"

