#line 36 "JIT.lss"
/* Generated by WRAPPER on 06/05/2014 13:33:58 */

#include "config.h"
#include "h.h"
#include "snotypes.h"
#include "macros.h"
#include "load.h"
#include "equ.h"
#include <string.h>

#line 37 "JIT.lss"

#include <lightning.h>
#include "p64.h"

/* Setup, state and misc */

/* INIT_JIT(STRING) */
INIT_JIT( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    init_jit(arg0);
    RETNULL;
}
#line 43 "JIT.lss"

/* FINISH_JIT() */
FINISH_JIT( LA_ALIST ) LA_DCL
{
    finish_jit();
    RETNULL;
}
#line 44 "JIT.lss"

static jit_state_t *_jit;

static void get_state_jit(void) { set_p_(_jit); }


/* GET_STATE_JIT() */
GET_STATE_JIT( LA_ALIST ) LA_DCL
{
    get_state_jit();
    RETNULL;
}
#line 50 "JIT.lss"

static void set_state_jit(void) { _jit = get_p_(); }


/* SET_STATE_JIT() */
SET_STATE_JIT( LA_ALIST ) LA_DCL
{
    set_state_jit();
    RETNULL;
}
#line 54 "JIT.lss"

static void new_state_jit(void) { set_p_(jit_new_state()); }


/* NEW_STATE_JIT() */
NEW_STATE_JIT( LA_ALIST ) LA_DCL
{
    new_state_jit();
    RETNULL;
}
#line 58 "JIT.lss"

static void destroy_state_jit(void) { jit_destroy_state(); }


/* DESTROY_STATE_JIT() */
DESTROY_STATE_JIT( LA_ALIST ) LA_DCL
{
    destroy_state_jit();
    RETNULL;
}
#line 62 "JIT.lss"

static void clear_state_jit(void) { jit_clear_state(); }


/* CLEAR_STATE_JIT() */
CLEAR_STATE_JIT( LA_ALIST ) LA_DCL
{
    clear_state_jit();
    RETNULL;
}
#line 66 "JIT.lss"

static void prolog_jit(void) { jit_prolog(); }


/* PROLOG_JIT() */
PROLOG_JIT( LA_ALIST ) LA_DCL
{
    prolog_jit();
    RETNULL;
}
#line 70 "JIT.lss"

static void epilog_jit(void) { jit_epilog(); }


/* EPILOG_JIT() */
EPILOG_JIT( LA_ALIST ) LA_DCL
{
    epilog_jit();
    RETNULL;
}
#line 74 "JIT.lss"

static void note_jit(char *s, int n) { set_p_(jit_note(s, n)); }


/* NOTE_JIT(STRING,INTEGER) */
NOTE_JIT( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    note_jit(arg0,(int)LA_INT(1));
    RETNULL;
}
#line 78 "JIT.lss"

static void name_jit(char *s) { set_p_(jit_name(s)); }


/* NAME_JIT(STRING) */
NAME_JIT( LA_ALIST ) LA_DCL
{
    char arg0[1024];
    getstring(LA_PTR(0), arg0, sizeof(arg0));
    name_jit(arg0);
    RETNULL;
}
#line 82 "JIT.lss"

static void address_jit(void) { set_p_(jit_address(get_p_())); }


/* ADDRESS_JIT() */
ADDRESS_JIT( LA_ALIST ) LA_DCL
{
    address_jit();
    RETNULL;
}
#line 86 "JIT.lss"

static void disassemble_jit(void) { jit_disassemble(); }


/* DISASSEMBLE_JIT() */
DISASSEMBLE_JIT( LA_ALIST ) LA_DCL
{
    disassemble_jit();
    RETNULL;
}
#line 90 "JIT.lss"

static void emit_jit(void) { set_p_(jit_emit()); }


/* EMIT_JIT() */
EMIT_JIT( LA_ALIST ) LA_DCL
{
    emit_jit();
    RETNULL;
}
#line 94 "JIT.lss"

static void print_jit(void) { jit_print(); }


/* PRINT_JIT() */
PRINT_JIT( LA_ALIST ) LA_DCL
{
    print_jit();
    RETNULL;
}
#line 98 "JIT.lss"

static void label_jit(void) { set_p_(jit_label()); }


/* LABEL_JIT() */
LABEL_JIT( LA_ALIST ) LA_DCL
{
    label_jit();
    RETNULL;
}
#line 102 "JIT.lss"

static void ellipsis_jit(void) { jit_ellipsis(); }


/* ELLIPSIS_JIT() */
ELLIPSIS_JIT( LA_ALIST ) LA_DCL
{
    ellipsis_jit();
    RETNULL;
}
#line 106 "JIT.lss"

static int get_note_jit(void)
{
    int notei;
    void *p, *p2;
    jit_get_note(get_p_(), (char **)&p, (char **)&p2, &notei);
    set_p_(p);
    set_p2_(p2);
    return notei;
}


/* GET_NOTE_JIT()INTEGER */
GET_NOTE_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_note_jit());
}
#line 118 "JIT.lss"

static int pointer_p_jit(void) { return jit_pointer_p(get_p_()); }


/* POINTER_P_JIT()PREDICATE */
POINTER_P_JIT( LA_ALIST ) LA_DCL
{
    if (pointer_p_jit())
	RETNULL;
    RETFAIL;
}
#line 122 "JIT.lss"

static int callee_save_p(int r) { return jit_callee_save_p(r); }


/* CALLEE_SAVE_P_JIT(INTEGER)PREDICATE */
CALLEE_SAVE_P_JIT( LA_ALIST ) LA_DCL
{
    if (callee_save_p_jit((int)LA_INT(0)))
	RETNULL;
    RETFAIL;
}
#line 126 "JIT.lss"

static void patch_at_jit(void) { jit_patch_at(get_p_(), get_p2_()); }


/* PATCH_AT_JIT() */
PATCH_AT_JIT( LA_ALIST ) LA_DCL
{
    patch_at_jit();
    RETNULL;
}
#line 130 "JIT.lss"

static void patch_abs_jit(void) { jit_patch_abs(get_p_(), get_p2_()); }


/* PATCH_ABS_JIT() */
PATCH_ABS_JIT( LA_ALIST ) LA_DCL
{
    patch_abs_jit();
    RETNULL;
}
#line 134 "JIT.lss"

static void patch_jit(void) { jit_patch(get_p_()); }


/* PATCH_JIT() */
PATCH_JIT( LA_ALIST ) LA_DCL
{
    patch_jit();
    RETNULL;
}
#line 138 "JIT.lss"

static void prepare_jit(void) { jit_prepare(); }


/* PREPARE_JIT() */
PREPARE_JIT( LA_ALIST ) LA_DCL
{
    prepare_jit();
    RETNULL;
}
#line 142 "JIT.lss"

static int allocai_jit(int n) { return jit_allocai(n); }


/* ALLOCAI_JIT(INTEGER)INTEGER */
ALLOCAI_JIT( LA_ALIST ) LA_DCL
{
    RETINT(allocai_jit((int)LA_INT(0)));
}
#line 146 "JIT.lss"

/* DATA, LENGTH, ALIGNMENT (0..4). DATA/LENGTH HASHED */
static void data_jit(int l, int a) { set_p_(jit_data(get_p_(), l, a)); }


/* DATA_JIT(INTEGER,INTEGER) */
DATA_JIT( LA_ALIST ) LA_DCL
{
    data_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 151 "JIT.lss"

static void forward_jit(void) { set_p_(jit_forward()); }


/* FORWARD_JIT() */
FORWARD_JIT( LA_ALIST ) LA_DCL
{
    forward_jit();
    RETNULL;
}
#line 155 "JIT.lss"

static void live_jit(int r) { jit_live(r); }


/* LIVE_JIT(INTEGER) */
LIVE_JIT( LA_ALIST ) LA_DCL
{
    live_jit((int)LA_INT(0));
    RETNULL;
}
#line 159 "JIT.lss"

static void link_jit(void) { jit_link(get_p_()); }


/* LINK_JIT() */
LINK_JIT( LA_ALIST ) LA_DCL
{
    link_jit();
    RETNULL;
}
#line 163 "JIT.lss"

/* REGISTERS */
static int r_num_jit(void) { return jit_r_num(); }


/* R_NUM_JIT()INTEGER */
R_NUM_JIT( LA_ALIST ) LA_DCL
{
    RETINT(r_num_jit());
}
#line 168 "JIT.lss"

static int v_num_jit(void) { return jit_v_num(); }


/* V_NUM_JIT()INTEGER */
V_NUM_JIT( LA_ALIST ) LA_DCL
{
    RETINT(v_num_jit());
}
#line 172 "JIT.lss"

static int f_num_jit(void) { return jit_f_num(); }


/* F_NUM_JIT()INTEGER */
F_NUM_JIT( LA_ALIST ) LA_DCL
{
    RETINT(f_num_jit());
}
#line 176 "JIT.lss"

#line 178 "JIT.lss"
#line 179 "JIT.lss"
#line 180 "JIT.lss"
#line 181 "JIT.lss"
static int get_r0_jit(void) { 
#ifdef JIT_R0
    return JIT_R0;
#else
    return -1;
#endif
}

/* GET_R0_JIT()INTEGER */
GET_R0_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_r0_jit());
}
static int get_r1_jit(void) { 
#ifdef JIT_R1
    return JIT_R1;
#else
    return -1;
#endif
}

/* GET_R1_JIT()INTEGER */
GET_R1_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_r1_jit());
}
static int get_r2_jit(void) { 
#ifdef JIT_R2
    return JIT_R2;
#else
    return -1;
#endif
}

/* GET_R2_JIT()INTEGER */
GET_R2_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_r2_jit());
}
static int get_r3_jit(void) { 
#ifdef JIT_R3
    return JIT_R3;
#else
    return -1;
#endif
}

/* GET_R3_JIT()INTEGER */
GET_R3_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_r3_jit());
}
static int get_v0_jit(void) { 
#ifdef JIT_V0
    return JIT_V0;
#else
    return -1;
#endif
}

/* GET_V0_JIT()INTEGER */
GET_V0_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_v0_jit());
}
static int get_v1_jit(void) { 
#ifdef JIT_V1
    return JIT_V1;
#else
    return -1;
#endif
}

/* GET_V1_JIT()INTEGER */
GET_V1_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_v1_jit());
}
static int get_v2_jit(void) { 
#ifdef JIT_V2
    return JIT_V2;
#else
    return -1;
#endif
}

/* GET_V2_JIT()INTEGER */
GET_V2_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_v2_jit());
}
static int get_v3_jit(void) { 
#ifdef JIT_V3
    return JIT_V3;
#else
    return -1;
#endif
}

/* GET_V3_JIT()INTEGER */
GET_V3_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_v3_jit());
}
static int get_f0_jit(void) { 
#ifdef JIT_F0
    return JIT_F0;
#else
    return -1;
#endif
}

/* GET_F0_JIT()INTEGER */
GET_F0_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f0_jit());
}
static int get_f1_jit(void) { 
#ifdef JIT_F1
    return JIT_F1;
#else
    return -1;
#endif
}

/* GET_F1_JIT()INTEGER */
GET_F1_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f1_jit());
}
static int get_f2_jit(void) { 
#ifdef JIT_F2
    return JIT_F2;
#else
    return -1;
#endif
}

/* GET_F2_JIT()INTEGER */
GET_F2_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f2_jit());
}
static int get_f3_jit(void) { 
#ifdef JIT_F3
    return JIT_F3;
#else
    return -1;
#endif
}

/* GET_F3_JIT()INTEGER */
GET_F3_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f3_jit());
}
static int get_f4_jit(void) { 
#ifdef JIT_F4
    return JIT_F4;
#else
    return -1;
#endif
}

/* GET_F4_JIT()INTEGER */
GET_F4_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f4_jit());
}
static int get_f5_jit(void) { 
#ifdef JIT_F5
    return JIT_F5;
#else
    return -1;
#endif
}

/* GET_F5_JIT()INTEGER */
GET_F5_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f5_jit());
}
static int get_f6_jit(void) { 
#ifdef JIT_F6
    return JIT_F6;
#else
    return -1;
#endif
}

/* GET_F6_JIT()INTEGER */
GET_F6_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f6_jit());
}
static int get_f7_jit(void) { 
#ifdef JIT_F7
    return JIT_F7;
#else
    return -1;
#endif
}

/* GET_F7_JIT()INTEGER */
GET_F7_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_f7_jit());
}
static int get_fp_jit(void) { 
#ifdef JIT_FP
    return JIT_FP;
#else
    return -1;
#endif
}

/* GET_FP_JIT()INTEGER */
GET_FP_JIT( LA_ALIST ) LA_DCL
{
    RETINT(get_fp_jit());
}
#line 190 "JIT.lss"

/* REGISTER MATH */
#line 203 "JIT.lss"
#line 204 "JIT.lss"
#line 205 "JIT.lss"
#line 206 "JIT.lss"
static void addr_jit(int r1, int r2, int r3) { 
    jit_addr(r1, r2, r3);
}

/* ADDR_JIT(INTEGER,INTEGER,INTEGER) */
ADDR_JIT( LA_ALIST ) LA_DCL
{
    addr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void addcr_jit(int r1, int r2, int r3) { 
    jit_addcr(r1, r2, r3);
}

/* ADDCR_JIT(INTEGER,INTEGER,INTEGER) */
ADDCR_JIT( LA_ALIST ) LA_DCL
{
    addcr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void addxr_jit(int r1, int r2, int r3) { 
    jit_addxr(r1, r2, r3);
}

/* ADDXR_JIT(INTEGER,INTEGER,INTEGER) */
ADDXR_JIT( LA_ALIST ) LA_DCL
{
    addxr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void subr_jit(int r1, int r2, int r3) { 
    jit_subr(r1, r2, r3);
}

/* SUBR_JIT(INTEGER,INTEGER,INTEGER) */
SUBR_JIT( LA_ALIST ) LA_DCL
{
    subr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void subcr_jit(int r1, int r2, int r3) { 
    jit_subcr(r1, r2, r3);
}

/* SUBCR_JIT(INTEGER,INTEGER,INTEGER) */
SUBCR_JIT( LA_ALIST ) LA_DCL
{
    subcr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void subxr_jit(int r1, int r2, int r3) { 
    jit_subxr(r1, r2, r3);
}

/* SUBXR_JIT(INTEGER,INTEGER,INTEGER) */
SUBXR_JIT( LA_ALIST ) LA_DCL
{
    subxr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void mulr_jit(int r1, int r2, int r3) { 
    jit_mulr(r1, r2, r3);
}

/* MULR_JIT(INTEGER,INTEGER,INTEGER) */
MULR_JIT( LA_ALIST ) LA_DCL
{
    mulr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void divr_jit(int r1, int r2, int r3) { 
    jit_divr(r1, r2, r3);
}

/* DIVR_JIT(INTEGER,INTEGER,INTEGER) */
DIVR_JIT( LA_ALIST ) LA_DCL
{
    divr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void divr_u_jit(int r1, int r2, int r3) { 
    jit_divr_u(r1, r2, r3);
}

/* DIVR_U_JIT(INTEGER,INTEGER,INTEGER) */
DIVR_U_JIT( LA_ALIST ) LA_DCL
{
    divr_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void remr_jit(int r1, int r2, int r3) { 
    jit_remr(r1, r2, r3);
}

/* REMR_JIT(INTEGER,INTEGER,INTEGER) */
REMR_JIT( LA_ALIST ) LA_DCL
{
    remr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void remr_u_jit(int r1, int r2, int r3) { 
    jit_remr_u(r1, r2, r3);
}

/* REMR_U_JIT(INTEGER,INTEGER,INTEGER) */
REMR_U_JIT( LA_ALIST ) LA_DCL
{
    remr_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void andr_jit(int r1, int r2, int r3) { 
    jit_andr(r1, r2, r3);
}

/* ANDR_JIT(INTEGER,INTEGER,INTEGER) */
ANDR_JIT( LA_ALIST ) LA_DCL
{
    andr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void orr_jit(int r1, int r2, int r3) { 
    jit_orr(r1, r2, r3);
}

/* ORR_JIT(INTEGER,INTEGER,INTEGER) */
ORR_JIT( LA_ALIST ) LA_DCL
{
    orr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void xorr_jit(int r1, int r2, int r3) { 
    jit_xorr(r1, r2, r3);
}

/* XORR_JIT(INTEGER,INTEGER,INTEGER) */
XORR_JIT( LA_ALIST ) LA_DCL
{
    xorr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void lshr_jit(int r1, int r2, int r3) { 
    jit_lshr(r1, r2, r3);
}

/* LSHR_JIT(INTEGER,INTEGER,INTEGER) */
LSHR_JIT( LA_ALIST ) LA_DCL
{
    lshr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void rshr_jit(int r1, int r2, int r3) { 
    jit_rshr(r1, r2, r3);
}

/* RSHR_JIT(INTEGER,INTEGER,INTEGER) */
RSHR_JIT( LA_ALIST ) LA_DCL
{
    rshr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void rshr_u_jit(int r1, int r2, int r3) { 
    jit_rshr_u(r1, r2, r3);
}

/* RSHR_U_JIT(INTEGER,INTEGER,INTEGER) */
RSHR_U_JIT( LA_ALIST ) LA_DCL
{
    rshr_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltr_jit(int r1, int r2, int r3) { 
    jit_ltr(r1, r2, r3);
}

/* LTR_JIT(INTEGER,INTEGER,INTEGER) */
LTR_JIT( LA_ALIST ) LA_DCL
{
    ltr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltr_u_jit(int r1, int r2, int r3) { 
    jit_ltr_u(r1, r2, r3);
}

/* LTR_U_JIT(INTEGER,INTEGER,INTEGER) */
LTR_U_JIT( LA_ALIST ) LA_DCL
{
    ltr_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ler_jit(int r1, int r2, int r3) { 
    jit_ler(r1, r2, r3);
}

/* LER_JIT(INTEGER,INTEGER,INTEGER) */
LER_JIT( LA_ALIST ) LA_DCL
{
    ler_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ler_u_jit(int r1, int r2, int r3) { 
    jit_ler_u(r1, r2, r3);
}

/* LER_U_JIT(INTEGER,INTEGER,INTEGER) */
LER_U_JIT( LA_ALIST ) LA_DCL
{
    ler_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ger_jit(int r1, int r2, int r3) { 
    jit_ger(r1, r2, r3);
}

/* GER_JIT(INTEGER,INTEGER,INTEGER) */
GER_JIT( LA_ALIST ) LA_DCL
{
    ger_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ger_u_jit(int r1, int r2, int r3) { 
    jit_ger_u(r1, r2, r3);
}

/* GER_U_JIT(INTEGER,INTEGER,INTEGER) */
GER_U_JIT( LA_ALIST ) LA_DCL
{
    ger_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void gtr_jit(int r1, int r2, int r3) { 
    jit_gtr(r1, r2, r3);
}

/* GTR_JIT(INTEGER,INTEGER,INTEGER) */
GTR_JIT( LA_ALIST ) LA_DCL
{
    gtr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void gtr_u_jit(int r1, int r2, int r3) { 
    jit_gtr_u(r1, r2, r3);
}

/* GTR_U_JIT(INTEGER,INTEGER,INTEGER) */
GTR_U_JIT( LA_ALIST ) LA_DCL
{
    gtr_u_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void eqr_jit(int r1, int r2, int r3) { 
    jit_eqr(r1, r2, r3);
}

/* EQR_JIT(INTEGER,INTEGER,INTEGER) */
EQR_JIT( LA_ALIST ) LA_DCL
{
    eqr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ner_jit(int r1, int r2, int r3) { 
    jit_ner(r1, r2, r3);
}

/* NER_JIT(INTEGER,INTEGER,INTEGER) */
NER_JIT( LA_ALIST ) LA_DCL
{
    ner_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void addr_f_jit(int r1, int r2, int r3) { 
    jit_addr_f(r1, r2, r3);
}

/* ADDR_F_JIT(INTEGER,INTEGER,INTEGER) */
ADDR_F_JIT( LA_ALIST ) LA_DCL
{
    addr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void addr_d_jit(int r1, int r2, int r3) { 
    jit_addr_d(r1, r2, r3);
}

/* ADDR_D_JIT(INTEGER,INTEGER,INTEGER) */
ADDR_D_JIT( LA_ALIST ) LA_DCL
{
    addr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void subr_f_jit(int r1, int r2, int r3) { 
    jit_subr_f(r1, r2, r3);
}

/* SUBR_F_JIT(INTEGER,INTEGER,INTEGER) */
SUBR_F_JIT( LA_ALIST ) LA_DCL
{
    subr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void subr_d_jit(int r1, int r2, int r3) { 
    jit_subr_d(r1, r2, r3);
}

/* SUBR_D_JIT(INTEGER,INTEGER,INTEGER) */
SUBR_D_JIT( LA_ALIST ) LA_DCL
{
    subr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void mulr_f_jit(int r1, int r2, int r3) { 
    jit_mulr_f(r1, r2, r3);
}

/* MULR_F_JIT(INTEGER,INTEGER,INTEGER) */
MULR_F_JIT( LA_ALIST ) LA_DCL
{
    mulr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void mulr_d_jit(int r1, int r2, int r3) { 
    jit_mulr_d(r1, r2, r3);
}

/* MULR_D_JIT(INTEGER,INTEGER,INTEGER) */
MULR_D_JIT( LA_ALIST ) LA_DCL
{
    mulr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void divr_f_jit(int r1, int r2, int r3) { 
    jit_divr_f(r1, r2, r3);
}

/* DIVR_F_JIT(INTEGER,INTEGER,INTEGER) */
DIVR_F_JIT( LA_ALIST ) LA_DCL
{
    divr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void divr_d_jit(int r1, int r2, int r3) { 
    jit_divr_d(r1, r2, r3);
}

/* DIVR_D_JIT(INTEGER,INTEGER,INTEGER) */
DIVR_D_JIT( LA_ALIST ) LA_DCL
{
    divr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltr_f_jit(int r1, int r2, int r3) { 
    jit_ltr_f(r1, r2, r3);
}

/* LTR_F_JIT(INTEGER,INTEGER,INTEGER) */
LTR_F_JIT( LA_ALIST ) LA_DCL
{
    ltr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ler_f_jit(int r1, int r2, int r3) { 
    jit_ler_f(r1, r2, r3);
}

/* LER_F_JIT(INTEGER,INTEGER,INTEGER) */
LER_F_JIT( LA_ALIST ) LA_DCL
{
    ler_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void eqr_f_jit(int r1, int r2, int r3) { 
    jit_eqr_f(r1, r2, r3);
}

/* EQR_F_JIT(INTEGER,INTEGER,INTEGER) */
EQR_F_JIT( LA_ALIST ) LA_DCL
{
    eqr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ger_f_jit(int r1, int r2, int r3) { 
    jit_ger_f(r1, r2, r3);
}

/* GER_F_JIT(INTEGER,INTEGER,INTEGER) */
GER_F_JIT( LA_ALIST ) LA_DCL
{
    ger_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void gtr_f_jit(int r1, int r2, int r3) { 
    jit_gtr_f(r1, r2, r3);
}

/* GTR_F_JIT(INTEGER,INTEGER,INTEGER) */
GTR_F_JIT( LA_ALIST ) LA_DCL
{
    gtr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ner_f_jit(int r1, int r2, int r3) { 
    jit_ner_f(r1, r2, r3);
}

/* NER_F_JIT(INTEGER,INTEGER,INTEGER) */
NER_F_JIT( LA_ALIST ) LA_DCL
{
    ner_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unltr_f_jit(int r1, int r2, int r3) { 
    jit_unltr_f(r1, r2, r3);
}

/* UNLTR_F_JIT(INTEGER,INTEGER,INTEGER) */
UNLTR_F_JIT( LA_ALIST ) LA_DCL
{
    unltr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unler_f_jit(int r1, int r2, int r3) { 
    jit_unler_f(r1, r2, r3);
}

/* UNLER_F_JIT(INTEGER,INTEGER,INTEGER) */
UNLER_F_JIT( LA_ALIST ) LA_DCL
{
    unler_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void uneqr_f_jit(int r1, int r2, int r3) { 
    jit_uneqr_f(r1, r2, r3);
}

/* UNEQR_F_JIT(INTEGER,INTEGER,INTEGER) */
UNEQR_F_JIT( LA_ALIST ) LA_DCL
{
    uneqr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unger_f_jit(int r1, int r2, int r3) { 
    jit_unger_f(r1, r2, r3);
}

/* UNGER_F_JIT(INTEGER,INTEGER,INTEGER) */
UNGER_F_JIT( LA_ALIST ) LA_DCL
{
    unger_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ungtr_f_jit(int r1, int r2, int r3) { 
    jit_ungtr_f(r1, r2, r3);
}

/* UNGTR_F_JIT(INTEGER,INTEGER,INTEGER) */
UNGTR_F_JIT( LA_ALIST ) LA_DCL
{
    ungtr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltgtr_f_jit(int r1, int r2, int r3) { 
    jit_ltgtr_f(r1, r2, r3);
}

/* LTGTR_F_JIT(INTEGER,INTEGER,INTEGER) */
LTGTR_F_JIT( LA_ALIST ) LA_DCL
{
    ltgtr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ordr_f_jit(int r1, int r2, int r3) { 
    jit_ordr_f(r1, r2, r3);
}

/* ORDR_F_JIT(INTEGER,INTEGER,INTEGER) */
ORDR_F_JIT( LA_ALIST ) LA_DCL
{
    ordr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unordr_f_jit(int r1, int r2, int r3) { 
    jit_unordr_f(r1, r2, r3);
}

/* UNORDR_F_JIT(INTEGER,INTEGER,INTEGER) */
UNORDR_F_JIT( LA_ALIST ) LA_DCL
{
    unordr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltr_d_jit(int r1, int r2, int r3) { 
    jit_ltr_d(r1, r2, r3);
}

/* LTR_D_JIT(INTEGER,INTEGER,INTEGER) */
LTR_D_JIT( LA_ALIST ) LA_DCL
{
    ltr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ler_d_jit(int r1, int r2, int r3) { 
    jit_ler_d(r1, r2, r3);
}

/* LER_D_JIT(INTEGER,INTEGER,INTEGER) */
LER_D_JIT( LA_ALIST ) LA_DCL
{
    ler_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void eqr_d_jit(int r1, int r2, int r3) { 
    jit_eqr_d(r1, r2, r3);
}

/* EQR_D_JIT(INTEGER,INTEGER,INTEGER) */
EQR_D_JIT( LA_ALIST ) LA_DCL
{
    eqr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ger_d_jit(int r1, int r2, int r3) { 
    jit_ger_d(r1, r2, r3);
}

/* GER_D_JIT(INTEGER,INTEGER,INTEGER) */
GER_D_JIT( LA_ALIST ) LA_DCL
{
    ger_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void gtr_d_jit(int r1, int r2, int r3) { 
    jit_gtr_d(r1, r2, r3);
}

/* GTR_D_JIT(INTEGER,INTEGER,INTEGER) */
GTR_D_JIT( LA_ALIST ) LA_DCL
{
    gtr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ner_d_jit(int r1, int r2, int r3) { 
    jit_ner_d(r1, r2, r3);
}

/* NER_D_JIT(INTEGER,INTEGER,INTEGER) */
NER_D_JIT( LA_ALIST ) LA_DCL
{
    ner_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unltr_d_jit(int r1, int r2, int r3) { 
    jit_unltr_d(r1, r2, r3);
}

/* UNLTR_D_JIT(INTEGER,INTEGER,INTEGER) */
UNLTR_D_JIT( LA_ALIST ) LA_DCL
{
    unltr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unler_d_jit(int r1, int r2, int r3) { 
    jit_unler_d(r1, r2, r3);
}

/* UNLER_D_JIT(INTEGER,INTEGER,INTEGER) */
UNLER_D_JIT( LA_ALIST ) LA_DCL
{
    unler_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void uneqr_d_jit(int r1, int r2, int r3) { 
    jit_uneqr_d(r1, r2, r3);
}

/* UNEQR_D_JIT(INTEGER,INTEGER,INTEGER) */
UNEQR_D_JIT( LA_ALIST ) LA_DCL
{
    uneqr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unger_d_jit(int r1, int r2, int r3) { 
    jit_unger_d(r1, r2, r3);
}

/* UNGER_D_JIT(INTEGER,INTEGER,INTEGER) */
UNGER_D_JIT( LA_ALIST ) LA_DCL
{
    unger_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ungtr_d_jit(int r1, int r2, int r3) { 
    jit_ungtr_d(r1, r2, r3);
}

/* UNGTR_D_JIT(INTEGER,INTEGER,INTEGER) */
UNGTR_D_JIT( LA_ALIST ) LA_DCL
{
    ungtr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ltgtr_d_jit(int r1, int r2, int r3) { 
    jit_ltgtr_d(r1, r2, r3);
}

/* LTGTR_D_JIT(INTEGER,INTEGER,INTEGER) */
LTGTR_D_JIT( LA_ALIST ) LA_DCL
{
    ltgtr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ordr_d_jit(int r1, int r2, int r3) { 
    jit_ordr_d(r1, r2, r3);
}

/* ORDR_D_JIT(INTEGER,INTEGER,INTEGER) */
ORDR_D_JIT( LA_ALIST ) LA_DCL
{
    ordr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void unordr_d_jit(int r1, int r2, int r3) { 
    jit_unordr_d(r1, r2, r3);
}

/* UNORDR_D_JIT(INTEGER,INTEGER,INTEGER) */
UNORDR_D_JIT( LA_ALIST ) LA_DCL
{
    unordr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_c_jit(int r1, int r2, int r3) { 
    jit_ldxr_c(r1, r2, r3);
}

/* LDXR_C_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_C_JIT( LA_ALIST ) LA_DCL
{
    ldxr_c_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_uc_jit(int r1, int r2, int r3) { 
    jit_ldxr_uc(r1, r2, r3);
}

/* LDXR_UC_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_UC_JIT( LA_ALIST ) LA_DCL
{
    ldxr_uc_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_s_jit(int r1, int r2, int r3) { 
    jit_ldxr_s(r1, r2, r3);
}

/* LDXR_S_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_S_JIT( LA_ALIST ) LA_DCL
{
    ldxr_s_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_us_jit(int r1, int r2, int r3) { 
    jit_ldxr_us(r1, r2, r3);
}

/* LDXR_US_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_US_JIT( LA_ALIST ) LA_DCL
{
    ldxr_us_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_i_jit(int r1, int r2, int r3) { 
    jit_ldxr_i(r1, r2, r3);
}

/* LDXR_I_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_I_JIT( LA_ALIST ) LA_DCL
{
    ldxr_i_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_ui_jit(int r1, int r2, int r3) { 
    jit_ldxr_ui(r1, r2, r3);
}

/* LDXR_UI_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_UI_JIT( LA_ALIST ) LA_DCL
{
    ldxr_ui_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_l_jit(int r1, int r2, int r3) { 
    jit_ldxr_l(r1, r2, r3);
}

/* LDXR_L_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_L_JIT( LA_ALIST ) LA_DCL
{
    ldxr_l_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_jit(int r1, int r2, int r3) { 
    jit_ldxr(r1, r2, r3);
}

/* LDXR_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_JIT( LA_ALIST ) LA_DCL
{
    ldxr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_f_jit(int r1, int r2, int r3) { 
    jit_ldxr_f(r1, r2, r3);
}

/* LDXR_F_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_F_JIT( LA_ALIST ) LA_DCL
{
    ldxr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void ldxr_d_jit(int r1, int r2, int r3) { 
    jit_ldxr_d(r1, r2, r3);
}

/* LDXR_D_JIT(INTEGER,INTEGER,INTEGER) */
LDXR_D_JIT( LA_ALIST ) LA_DCL
{
    ldxr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_c_jit(int r1, int r2, int r3) { 
    jit_stxr_c(r1, r2, r3);
}

/* STXR_C_JIT(INTEGER,INTEGER,INTEGER) */
STXR_C_JIT( LA_ALIST ) LA_DCL
{
    stxr_c_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_s_jit(int r1, int r2, int r3) { 
    jit_stxr_s(r1, r2, r3);
}

/* STXR_S_JIT(INTEGER,INTEGER,INTEGER) */
STXR_S_JIT( LA_ALIST ) LA_DCL
{
    stxr_s_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_i_jit(int r1, int r2, int r3) { 
    jit_stxr_i(r1, r2, r3);
}

/* STXR_I_JIT(INTEGER,INTEGER,INTEGER) */
STXR_I_JIT( LA_ALIST ) LA_DCL
{
    stxr_i_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_jit(int r1, int r2, int r3) { 
    jit_stxr(r1, r2, r3);
}

/* STXR_JIT(INTEGER,INTEGER,INTEGER) */
STXR_JIT( LA_ALIST ) LA_DCL
{
    stxr_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_l_jit(int r1, int r2, int r3) { 
    jit_stxr_l(r1, r2, r3);
}

/* STXR_L_JIT(INTEGER,INTEGER,INTEGER) */
STXR_L_JIT( LA_ALIST ) LA_DCL
{
    stxr_l_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_f_jit(int r1, int r2, int r3) { 
    jit_stxr_f(r1, r2, r3);
}

/* STXR_F_JIT(INTEGER,INTEGER,INTEGER) */
STXR_F_JIT( LA_ALIST ) LA_DCL
{
    stxr_f_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void stxr_d_jit(int r1, int r2, int r3) { 
    jit_stxr_d(r1, r2, r3);
}

/* STXR_D_JIT(INTEGER,INTEGER,INTEGER) */
STXR_D_JIT( LA_ALIST ) LA_DCL
{
    stxr_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
#line 212 "JIT.lss"

/* INTEGER IMMEDIATE MATH */
#line 219 "JIT.lss"
#line 220 "JIT.lss"
#line 221 "JIT.lss"
#line 222 "JIT.lss"
static void addi_jit(int r1, int r2) { 
    jit_addi(r1, r2, (long)get_p_());
}

/* ADDI_JIT(INTEGER,INTEGER) */
ADDI_JIT( LA_ALIST ) LA_DCL
{
    addi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void addci_jit(int r1, int r2) { 
    jit_addci(r1, r2, (long)get_p_());
}

/* ADDCI_JIT(INTEGER,INTEGER) */
ADDCI_JIT( LA_ALIST ) LA_DCL
{
    addci_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void addxi_jit(int r1, int r2) { 
    jit_addxi(r1, r2, (long)get_p_());
}

/* ADDXI_JIT(INTEGER,INTEGER) */
ADDXI_JIT( LA_ALIST ) LA_DCL
{
    addxi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void subi_jit(int r1, int r2) { 
    jit_subi(r1, r2, (long)get_p_());
}

/* SUBI_JIT(INTEGER,INTEGER) */
SUBI_JIT( LA_ALIST ) LA_DCL
{
    subi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void subci_jit(int r1, int r2) { 
    jit_subci(r1, r2, (long)get_p_());
}

/* SUBCI_JIT(INTEGER,INTEGER) */
SUBCI_JIT( LA_ALIST ) LA_DCL
{
    subci_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void subxi_jit(int r1, int r2) { 
    jit_subxi(r1, r2, (long)get_p_());
}

/* SUBXI_JIT(INTEGER,INTEGER) */
SUBXI_JIT( LA_ALIST ) LA_DCL
{
    subxi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void muli_jit(int r1, int r2) { 
    jit_muli(r1, r2, (long)get_p_());
}

/* MULI_JIT(INTEGER,INTEGER) */
MULI_JIT( LA_ALIST ) LA_DCL
{
    muli_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void divi_jit(int r1, int r2) { 
    jit_divi(r1, r2, (long)get_p_());
}

/* DIVI_JIT(INTEGER,INTEGER) */
DIVI_JIT( LA_ALIST ) LA_DCL
{
    divi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void divi_u_jit(int r1, int r2) { 
    jit_divi_u(r1, r2, (long)get_p_());
}

/* DIVI_U_JIT(INTEGER,INTEGER) */
DIVI_U_JIT( LA_ALIST ) LA_DCL
{
    divi_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void remi_jit(int r1, int r2) { 
    jit_remi(r1, r2, (long)get_p_());
}

/* REMI_JIT(INTEGER,INTEGER) */
REMI_JIT( LA_ALIST ) LA_DCL
{
    remi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void remi_u_jit(int r1, int r2) { 
    jit_remi_u(r1, r2, (long)get_p_());
}

/* REMI_U_JIT(INTEGER,INTEGER) */
REMI_U_JIT( LA_ALIST ) LA_DCL
{
    remi_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void andi_jit(int r1, int r2) { 
    jit_andi(r1, r2, (long)get_p_());
}

/* ANDI_JIT(INTEGER,INTEGER) */
ANDI_JIT( LA_ALIST ) LA_DCL
{
    andi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ori_jit(int r1, int r2) { 
    jit_ori(r1, r2, (long)get_p_());
}

/* ORI_JIT(INTEGER,INTEGER) */
ORI_JIT( LA_ALIST ) LA_DCL
{
    ori_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void xori_jit(int r1, int r2) { 
    jit_xori(r1, r2, (long)get_p_());
}

/* XORI_JIT(INTEGER,INTEGER) */
XORI_JIT( LA_ALIST ) LA_DCL
{
    xori_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void lshi_jit(int r1, int r2) { 
    jit_lshi(r1, r2, (long)get_p_());
}

/* LSHI_JIT(INTEGER,INTEGER) */
LSHI_JIT( LA_ALIST ) LA_DCL
{
    lshi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void rshi_jit(int r1, int r2) { 
    jit_rshi(r1, r2, (long)get_p_());
}

/* RSHI_JIT(INTEGER,INTEGER) */
RSHI_JIT( LA_ALIST ) LA_DCL
{
    rshi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void rshi_u_jit(int r1, int r2) { 
    jit_rshi_u(r1, r2, (long)get_p_());
}

/* RSHI_U_JIT(INTEGER,INTEGER) */
RSHI_U_JIT( LA_ALIST ) LA_DCL
{
    rshi_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void lti_jit(int r1, int r2) { 
    jit_lti(r1, r2, (long)get_p_());
}

/* LTI_JIT(INTEGER,INTEGER) */
LTI_JIT( LA_ALIST ) LA_DCL
{
    lti_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void lti_u_jit(int r1, int r2) { 
    jit_lti_u(r1, r2, (long)get_p_());
}

/* LTI_U_JIT(INTEGER,INTEGER) */
LTI_U_JIT( LA_ALIST ) LA_DCL
{
    lti_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void lei_jit(int r1, int r2) { 
    jit_lei(r1, r2, (long)get_p_());
}

/* LEI_JIT(INTEGER,INTEGER) */
LEI_JIT( LA_ALIST ) LA_DCL
{
    lei_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void lei_u_jit(int r1, int r2) { 
    jit_lei_u(r1, r2, (long)get_p_());
}

/* LEI_U_JIT(INTEGER,INTEGER) */
LEI_U_JIT( LA_ALIST ) LA_DCL
{
    lei_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void gei_jit(int r1, int r2) { 
    jit_gei(r1, r2, (long)get_p_());
}

/* GEI_JIT(INTEGER,INTEGER) */
GEI_JIT( LA_ALIST ) LA_DCL
{
    gei_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void gei_u_jit(int r1, int r2) { 
    jit_gei_u(r1, r2, (long)get_p_());
}

/* GEI_U_JIT(INTEGER,INTEGER) */
GEI_U_JIT( LA_ALIST ) LA_DCL
{
    gei_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void gti_jit(int r1, int r2) { 
    jit_gti(r1, r2, (long)get_p_());
}

/* GTI_JIT(INTEGER,INTEGER) */
GTI_JIT( LA_ALIST ) LA_DCL
{
    gti_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void gti_u_jit(int r1, int r2) { 
    jit_gti_u(r1, r2, (long)get_p_());
}

/* GTI_U_JIT(INTEGER,INTEGER) */
GTI_U_JIT( LA_ALIST ) LA_DCL
{
    gti_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void eqi_jit(int r1, int r2) { 
    jit_eqi(r1, r2, (long)get_p_());
}

/* EQI_JIT(INTEGER,INTEGER) */
EQI_JIT( LA_ALIST ) LA_DCL
{
    eqi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void nei_jit(int r1, int r2) { 
    jit_nei(r1, r2, (long)get_p_());
}

/* NEI_JIT(INTEGER,INTEGER) */
NEI_JIT( LA_ALIST ) LA_DCL
{
    nei_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_c_jit(int r1, int r2) { 
    jit_ldxi_c(r1, r2, (long)get_p_());
}

/* LDXI_C_JIT(INTEGER,INTEGER) */
LDXI_C_JIT( LA_ALIST ) LA_DCL
{
    ldxi_c_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_uc_jit(int r1, int r2) { 
    jit_ldxi_uc(r1, r2, (long)get_p_());
}

/* LDXI_UC_JIT(INTEGER,INTEGER) */
LDXI_UC_JIT( LA_ALIST ) LA_DCL
{
    ldxi_uc_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_s_jit(int r1, int r2) { 
    jit_ldxi_s(r1, r2, (long)get_p_());
}

/* LDXI_S_JIT(INTEGER,INTEGER) */
LDXI_S_JIT( LA_ALIST ) LA_DCL
{
    ldxi_s_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_us_jit(int r1, int r2) { 
    jit_ldxi_us(r1, r2, (long)get_p_());
}

/* LDXI_US_JIT(INTEGER,INTEGER) */
LDXI_US_JIT( LA_ALIST ) LA_DCL
{
    ldxi_us_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_i_jit(int r1, int r2) { 
    jit_ldxi_i(r1, r2, (long)get_p_());
}

/* LDXI_I_JIT(INTEGER,INTEGER) */
LDXI_I_JIT( LA_ALIST ) LA_DCL
{
    ldxi_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_ui_jit(int r1, int r2) { 
    jit_ldxi_ui(r1, r2, (long)get_p_());
}

/* LDXI_UI_JIT(INTEGER,INTEGER) */
LDXI_UI_JIT( LA_ALIST ) LA_DCL
{
    ldxi_ui_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_l_jit(int r1, int r2) { 
    jit_ldxi_l(r1, r2, (long)get_p_());
}

/* LDXI_L_JIT(INTEGER,INTEGER) */
LDXI_L_JIT( LA_ALIST ) LA_DCL
{
    ldxi_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_jit(int r1, int r2) { 
    jit_ldxi(r1, r2, (long)get_p_());
}

/* LDXI_JIT(INTEGER,INTEGER) */
LDXI_JIT( LA_ALIST ) LA_DCL
{
    ldxi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_f_jit(int r1, int r2) { 
    jit_ldxi_f(r1, r2, (long)get_p_());
}

/* LDXI_F_JIT(INTEGER,INTEGER) */
LDXI_F_JIT( LA_ALIST ) LA_DCL
{
    ldxi_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldxi_d_jit(int r1, int r2) { 
    jit_ldxi_d(r1, r2, (long)get_p_());
}

/* LDXI_D_JIT(INTEGER,INTEGER) */
LDXI_D_JIT( LA_ALIST ) LA_DCL
{
    ldxi_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 227 "JIT.lss"

#line 229 "JIT.lss"
#line 230 "JIT.lss"
#line 231 "JIT.lss"
#line 232 "JIT.lss"
static void stxi_c_jit(int r1, int r2) { 
    jit_stxi_c(r1, (long)get_p_(), r2);
}

/* STXI_C_JIT(INTEGER,INTEGER) */
STXI_C_JIT( LA_ALIST ) LA_DCL
{
    stxi_c_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_s_jit(int r1, int r2) { 
    jit_stxi_s(r1, (long)get_p_(), r2);
}

/* STXI_S_JIT(INTEGER,INTEGER) */
STXI_S_JIT( LA_ALIST ) LA_DCL
{
    stxi_s_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_i_jit(int r1, int r2) { 
    jit_stxi_i(r1, (long)get_p_(), r2);
}

/* STXI_I_JIT(INTEGER,INTEGER) */
STXI_I_JIT( LA_ALIST ) LA_DCL
{
    stxi_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_l_jit(int r1, int r2) { 
    jit_stxi_l(r1, (long)get_p_(), r2);
}

/* STXI_L_JIT(INTEGER,INTEGER) */
STXI_L_JIT( LA_ALIST ) LA_DCL
{
    stxi_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_jit(int r1, int r2) { 
    jit_stxi(r1, (long)get_p_(), r2);
}

/* STXI_JIT(INTEGER,INTEGER) */
STXI_JIT( LA_ALIST ) LA_DCL
{
    stxi_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_f_jit(int r1, int r2) { 
    jit_stxi_f(r1, (long)get_p_(), r2);
}

/* STXI_F_JIT(INTEGER,INTEGER) */
STXI_F_JIT( LA_ALIST ) LA_DCL
{
    stxi_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void stxi_d_jit(int r1, int r2) { 
    jit_stxi_d(r1, (long)get_p_(), r2);
}

/* STXI_D_JIT(INTEGER,INTEGER) */
STXI_D_JIT( LA_ALIST ) LA_DCL
{
    stxi_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 237 "JIT.lss"

/* FLOAT IMMEDIATE MATH */
#line 240 "JIT.lss"
#line 241 "JIT.lss"
#line 242 "JIT.lss"
#line 243 "JIT.lss"
static void addi_f_jit(int r1, int r2) { 
    jit_addi_f(r1, r2, get_f_());
}

/* ADDI_F_JIT(INTEGER,INTEGER) */
ADDI_F_JIT( LA_ALIST ) LA_DCL
{
    addi_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void subi_f_jit(int r1, int r2) { 
    jit_subi_f(r1, r2, get_f_());
}

/* SUBI_F_JIT(INTEGER,INTEGER) */
SUBI_F_JIT( LA_ALIST ) LA_DCL
{
    subi_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void muli_f_jit(int r1, int r2) { 
    jit_muli_f(r1, r2, get_f_());
}

/* MULI_F_JIT(INTEGER,INTEGER) */
MULI_F_JIT( LA_ALIST ) LA_DCL
{
    muli_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void divi_f_jit(int r1, int r2) { 
    jit_divi_f(r1, r2, get_f_());
}

/* DIVI_F_JIT(INTEGER,INTEGER) */
DIVI_F_JIT( LA_ALIST ) LA_DCL
{
    divi_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 248 "JIT.lss"

/* DOUBLE IMMEDIATE MATH */
#line 251 "JIT.lss"
#line 252 "JIT.lss"
#line 253 "JIT.lss"
#line 254 "JIT.lss"
static void addi_d_jit(int r1, int r2) { 
    jit_addi_d(r1, r2, get_d_());
}

/* ADDI_D_JIT(INTEGER,INTEGER) */
ADDI_D_JIT( LA_ALIST ) LA_DCL
{
    addi_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void subi_d_jit(int r1, int r2) { 
    jit_subi_d(r1, r2, get_d_());
}

/* SUBI_D_JIT(INTEGER,INTEGER) */
SUBI_D_JIT( LA_ALIST ) LA_DCL
{
    subi_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void muli_d_jit(int r1, int r2) { 
    jit_muli_d(r1, r2, get_d_());
}

/* MULI_D_JIT(INTEGER,INTEGER) */
MULI_D_JIT( LA_ALIST ) LA_DCL
{
    muli_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void divi_d_jit(int r1, int r2) { 
    jit_divi_d(r1, r2, get_d_());
}

/* DIVI_D_JIT(INTEGER,INTEGER) */
DIVI_D_JIT( LA_ALIST ) LA_DCL
{
    divi_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 259 "JIT.lss"

/* BRANCH - REGISTER */
#line 270 "JIT.lss"
#line 271 "JIT.lss"
#line 272 "JIT.lss"
#line 273 "JIT.lss"
static void bltr_jit(int r1, int r2) { 
    set_p_(jit_bltr(r1, r2));
}

/* BLTR_JIT(INTEGER,INTEGER) */
BLTR_JIT( LA_ALIST ) LA_DCL
{
    bltr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bltr_u_jit(int r1, int r2) { 
    set_p_(jit_bltr_u(r1, r2));
}

/* BLTR_U_JIT(INTEGER,INTEGER) */
BLTR_U_JIT( LA_ALIST ) LA_DCL
{
    bltr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bler_jit(int r1, int r2) { 
    set_p_(jit_bler(r1, r2));
}

/* BLER_JIT(INTEGER,INTEGER) */
BLER_JIT( LA_ALIST ) LA_DCL
{
    bler_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bler_u_jit(int r1, int r2) { 
    set_p_(jit_bler_u(r1, r2));
}

/* BLER_U_JIT(INTEGER,INTEGER) */
BLER_U_JIT( LA_ALIST ) LA_DCL
{
    bler_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bgtr_jit(int r1, int r2) { 
    set_p_(jit_bgtr(r1, r2));
}

/* BGTR_JIT(INTEGER,INTEGER) */
BGTR_JIT( LA_ALIST ) LA_DCL
{
    bgtr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bgtr_u_jit(int r1, int r2) { 
    set_p_(jit_bgtr_u(r1, r2));
}

/* BGTR_U_JIT(INTEGER,INTEGER) */
BGTR_U_JIT( LA_ALIST ) LA_DCL
{
    bgtr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bger_jit(int r1, int r2) { 
    set_p_(jit_bger(r1, r2));
}

/* BGER_JIT(INTEGER,INTEGER) */
BGER_JIT( LA_ALIST ) LA_DCL
{
    bger_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bger_u_jit(int r1, int r2) { 
    set_p_(jit_bger_u(r1, r2));
}

/* BGER_U_JIT(INTEGER,INTEGER) */
BGER_U_JIT( LA_ALIST ) LA_DCL
{
    bger_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void beqr_jit(int r1, int r2) { 
    set_p_(jit_beqr(r1, r2));
}

/* BEQR_JIT(INTEGER,INTEGER) */
BEQR_JIT( LA_ALIST ) LA_DCL
{
    beqr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bner_jit(int r1, int r2) { 
    set_p_(jit_bner(r1, r2));
}

/* BNER_JIT(INTEGER,INTEGER) */
BNER_JIT( LA_ALIST ) LA_DCL
{
    bner_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bmsr_jit(int r1, int r2) { 
    set_p_(jit_bmsr(r1, r2));
}

/* BMSR_JIT(INTEGER,INTEGER) */
BMSR_JIT( LA_ALIST ) LA_DCL
{
    bmsr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bmcr_jit(int r1, int r2) { 
    set_p_(jit_bmcr(r1, r2));
}

/* BMCR_JIT(INTEGER,INTEGER) */
BMCR_JIT( LA_ALIST ) LA_DCL
{
    bmcr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void boaddr_jit(int r1, int r2) { 
    set_p_(jit_boaddr(r1, r2));
}

/* BOADDR_JIT(INTEGER,INTEGER) */
BOADDR_JIT( LA_ALIST ) LA_DCL
{
    boaddr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bxaddr_jit(int r1, int r2) { 
    set_p_(jit_bxaddr(r1, r2));
}

/* BXADDR_JIT(INTEGER,INTEGER) */
BXADDR_JIT( LA_ALIST ) LA_DCL
{
    bxaddr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bosubr_jit(int r1, int r2) { 
    set_p_(jit_bosubr(r1, r2));
}

/* BOSUBR_JIT(INTEGER,INTEGER) */
BOSUBR_JIT( LA_ALIST ) LA_DCL
{
    bosubr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bxsubr_jit(int r1, int r2) { 
    set_p_(jit_bxsubr(r1, r2));
}

/* BXSUBR_JIT(INTEGER,INTEGER) */
BXSUBR_JIT( LA_ALIST ) LA_DCL
{
    bxsubr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void boaddr_u_jit(int r1, int r2) { 
    set_p_(jit_boaddr_u(r1, r2));
}

/* BOADDR_U_JIT(INTEGER,INTEGER) */
BOADDR_U_JIT( LA_ALIST ) LA_DCL
{
    boaddr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bxaddr_u_jit(int r1, int r2) { 
    set_p_(jit_bxaddr_u(r1, r2));
}

/* BXADDR_U_JIT(INTEGER,INTEGER) */
BXADDR_U_JIT( LA_ALIST ) LA_DCL
{
    bxaddr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bosubr_u_jit(int r1, int r2) { 
    set_p_(jit_bosubr_u(r1, r2));
}

/* BOSUBR_U_JIT(INTEGER,INTEGER) */
BOSUBR_U_JIT( LA_ALIST ) LA_DCL
{
    bosubr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bxsubr_u_jit(int r1, int r2) { 
    set_p_(jit_bxsubr_u(r1, r2));
}

/* BXSUBR_U_JIT(INTEGER,INTEGER) */
BXSUBR_U_JIT( LA_ALIST ) LA_DCL
{
    bxsubr_u_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bltr_f_jit(int r1, int r2) { 
    set_p_(jit_bltr_f(r1, r2));
}

/* BLTR_F_JIT(INTEGER,INTEGER) */
BLTR_F_JIT( LA_ALIST ) LA_DCL
{
    bltr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bler_f_jit(int r1, int r2) { 
    set_p_(jit_bler_f(r1, r2));
}

/* BLER_F_JIT(INTEGER,INTEGER) */
BLER_F_JIT( LA_ALIST ) LA_DCL
{
    bler_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bgtr_f_jit(int r1, int r2) { 
    set_p_(jit_bgtr_f(r1, r2));
}

/* BGTR_F_JIT(INTEGER,INTEGER) */
BGTR_F_JIT( LA_ALIST ) LA_DCL
{
    bgtr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bger_f_jit(int r1, int r2) { 
    set_p_(jit_bger_f(r1, r2));
}

/* BGER_F_JIT(INTEGER,INTEGER) */
BGER_F_JIT( LA_ALIST ) LA_DCL
{
    bger_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void beqr_f_jit(int r1, int r2) { 
    set_p_(jit_beqr_f(r1, r2));
}

/* BEQR_F_JIT(INTEGER,INTEGER) */
BEQR_F_JIT( LA_ALIST ) LA_DCL
{
    beqr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bner_f_jit(int r1, int r2) { 
    set_p_(jit_bner_f(r1, r2));
}

/* BNER_F_JIT(INTEGER,INTEGER) */
BNER_F_JIT( LA_ALIST ) LA_DCL
{
    bner_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunltr_f_jit(int r1, int r2) { 
    set_p_(jit_bunltr_f(r1, r2));
}

/* BUNLTR_F_JIT(INTEGER,INTEGER) */
BUNLTR_F_JIT( LA_ALIST ) LA_DCL
{
    bunltr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunler_f_jit(int r1, int r2) { 
    set_p_(jit_bunler_f(r1, r2));
}

/* BUNLER_F_JIT(INTEGER,INTEGER) */
BUNLER_F_JIT( LA_ALIST ) LA_DCL
{
    bunler_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void buneqr_f_jit(int r1, int r2) { 
    set_p_(jit_buneqr_f(r1, r2));
}

/* BUNEQR_F_JIT(INTEGER,INTEGER) */
BUNEQR_F_JIT( LA_ALIST ) LA_DCL
{
    buneqr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunger_f_jit(int r1, int r2) { 
    set_p_(jit_bunger_f(r1, r2));
}

/* BUNGER_F_JIT(INTEGER,INTEGER) */
BUNGER_F_JIT( LA_ALIST ) LA_DCL
{
    bunger_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bungtr_f_jit(int r1, int r2) { 
    set_p_(jit_bungtr_f(r1, r2));
}

/* BUNGTR_F_JIT(INTEGER,INTEGER) */
BUNGTR_F_JIT( LA_ALIST ) LA_DCL
{
    bungtr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bltgtr_f_jit(int r1, int r2) { 
    set_p_(jit_bltgtr_f(r1, r2));
}

/* BLTGTR_F_JIT(INTEGER,INTEGER) */
BLTGTR_F_JIT( LA_ALIST ) LA_DCL
{
    bltgtr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bordr_f_jit(int r1, int r2) { 
    set_p_(jit_bordr_f(r1, r2));
}

/* BORDR_F_JIT(INTEGER,INTEGER) */
BORDR_F_JIT( LA_ALIST ) LA_DCL
{
    bordr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunordr_f_jit(int r1, int r2) { 
    set_p_(jit_bunordr_f(r1, r2));
}

/* BUNORDR_F_JIT(INTEGER,INTEGER) */
BUNORDR_F_JIT( LA_ALIST ) LA_DCL
{
    bunordr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bltr_d_jit(int r1, int r2) { 
    set_p_(jit_bltr_d(r1, r2));
}

/* BLTR_D_JIT(INTEGER,INTEGER) */
BLTR_D_JIT( LA_ALIST ) LA_DCL
{
    bltr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bler_d_jit(int r1, int r2) { 
    set_p_(jit_bler_d(r1, r2));
}

/* BLER_D_JIT(INTEGER,INTEGER) */
BLER_D_JIT( LA_ALIST ) LA_DCL
{
    bler_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bgtr_d_jit(int r1, int r2) { 
    set_p_(jit_bgtr_d(r1, r2));
}

/* BGTR_D_JIT(INTEGER,INTEGER) */
BGTR_D_JIT( LA_ALIST ) LA_DCL
{
    bgtr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bger_d_jit(int r1, int r2) { 
    set_p_(jit_bger_d(r1, r2));
}

/* BGER_D_JIT(INTEGER,INTEGER) */
BGER_D_JIT( LA_ALIST ) LA_DCL
{
    bger_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void beqr_d_jit(int r1, int r2) { 
    set_p_(jit_beqr_d(r1, r2));
}

/* BEQR_D_JIT(INTEGER,INTEGER) */
BEQR_D_JIT( LA_ALIST ) LA_DCL
{
    beqr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bner_d_jit(int r1, int r2) { 
    set_p_(jit_bner_d(r1, r2));
}

/* BNER_D_JIT(INTEGER,INTEGER) */
BNER_D_JIT( LA_ALIST ) LA_DCL
{
    bner_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunltr_d_jit(int r1, int r2) { 
    set_p_(jit_bunltr_d(r1, r2));
}

/* BUNLTR_D_JIT(INTEGER,INTEGER) */
BUNLTR_D_JIT( LA_ALIST ) LA_DCL
{
    bunltr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunler_d_jit(int r1, int r2) { 
    set_p_(jit_bunler_d(r1, r2));
}

/* BUNLER_D_JIT(INTEGER,INTEGER) */
BUNLER_D_JIT( LA_ALIST ) LA_DCL
{
    bunler_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void buneqr_d_jit(int r1, int r2) { 
    set_p_(jit_buneqr_d(r1, r2));
}

/* BUNEQR_D_JIT(INTEGER,INTEGER) */
BUNEQR_D_JIT( LA_ALIST ) LA_DCL
{
    buneqr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunger_d_jit(int r1, int r2) { 
    set_p_(jit_bunger_d(r1, r2));
}

/* BUNGER_D_JIT(INTEGER,INTEGER) */
BUNGER_D_JIT( LA_ALIST ) LA_DCL
{
    bunger_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bungtr_d_jit(int r1, int r2) { 
    set_p_(jit_bungtr_d(r1, r2));
}

/* BUNGTR_D_JIT(INTEGER,INTEGER) */
BUNGTR_D_JIT( LA_ALIST ) LA_DCL
{
    bungtr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bltgtr_d_jit(int r1, int r2) { 
    set_p_(jit_bltgtr_d(r1, r2));
}

/* BLTGTR_D_JIT(INTEGER,INTEGER) */
BLTGTR_D_JIT( LA_ALIST ) LA_DCL
{
    bltgtr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bordr_d_jit(int r1, int r2) { 
    set_p_(jit_bordr_d(r1, r2));
}

/* BORDR_D_JIT(INTEGER,INTEGER) */
BORDR_D_JIT( LA_ALIST ) LA_DCL
{
    bordr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void bunordr_d_jit(int r1, int r2) { 
    set_p_(jit_bunordr_d(r1, r2));
}

/* BUNORDR_D_JIT(INTEGER,INTEGER) */
BUNORDR_D_JIT( LA_ALIST ) LA_DCL
{
    bunordr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 278 "JIT.lss"

/* TWO REGISTER MOV, HTONR, NTOHR, COM, NEG, ABS, SQRT, EXT, TRUNC */
#line 290 "JIT.lss"
#line 291 "JIT.lss"
#line 292 "JIT.lss"
#line 293 "JIT.lss"
static void movr_jit(int r1, int r2) { 
    jit_movr(r1, r2);
}

/* MOVR_JIT(INTEGER,INTEGER) */
MOVR_JIT( LA_ALIST ) LA_DCL
{
    movr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_f_jit(int r1, int r2) { 
    jit_movr_f(r1, r2);
}

/* MOVR_F_JIT(INTEGER,INTEGER) */
MOVR_F_JIT( LA_ALIST ) LA_DCL
{
    movr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_d_jit(int r1, int r2) { 
    jit_movr_d(r1, r2);
}

/* MOVR_D_JIT(INTEGER,INTEGER) */
MOVR_D_JIT( LA_ALIST ) LA_DCL
{
    movr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_f_w_jit(int r1, int r2) { 
    jit_movr_f_w(r1, r2);
}

/* MOVR_F_W_JIT(INTEGER,INTEGER) */
MOVR_F_W_JIT( LA_ALIST ) LA_DCL
{
    movr_f_w_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_w_f_jit(int r1, int r2) { 
    jit_movr_w_f(r1, r2);
}

/* MOVR_W_F_JIT(INTEGER,INTEGER) */
MOVR_W_F_JIT( LA_ALIST ) LA_DCL
{
    movr_w_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_d_w_jit(int r1, int r2) { 
    jit_movr_d_w(r1, r2);
}

/* MOVR_D_W_JIT(INTEGER,INTEGER) */
MOVR_D_W_JIT( LA_ALIST ) LA_DCL
{
    movr_d_w_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void movr_w_d_jit(int r1, int r2) { 
    jit_movr_w_d(r1, r2);
}

/* MOVR_W_D_JIT(INTEGER,INTEGER) */
MOVR_W_D_JIT( LA_ALIST ) LA_DCL
{
    movr_w_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void htonr_jit(int r1, int r2) { 
    jit_htonr(r1, r2);
}

/* HTONR_JIT(INTEGER,INTEGER) */
HTONR_JIT( LA_ALIST ) LA_DCL
{
    htonr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ntohr_jit(int r1, int r2) { 
    jit_ntohr(r1, r2);
}

/* NTOHR_JIT(INTEGER,INTEGER) */
NTOHR_JIT( LA_ALIST ) LA_DCL
{
    ntohr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void comr_jit(int r1, int r2) { 
    jit_comr(r1, r2);
}

/* COMR_JIT(INTEGER,INTEGER) */
COMR_JIT( LA_ALIST ) LA_DCL
{
    comr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void negr_jit(int r1, int r2) { 
    jit_negr(r1, r2);
}

/* NEGR_JIT(INTEGER,INTEGER) */
NEGR_JIT( LA_ALIST ) LA_DCL
{
    negr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void negr_f_jit(int r1, int r2) { 
    jit_negr_f(r1, r2);
}

/* NEGR_F_JIT(INTEGER,INTEGER) */
NEGR_F_JIT( LA_ALIST ) LA_DCL
{
    negr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void negr_d_jit(int r1, int r2) { 
    jit_negr_d(r1, r2);
}

/* NEGR_D_JIT(INTEGER,INTEGER) */
NEGR_D_JIT( LA_ALIST ) LA_DCL
{
    negr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void absr_f_jit(int r1, int r2) { 
    jit_absr_f(r1, r2);
}

/* ABSR_F_JIT(INTEGER,INTEGER) */
ABSR_F_JIT( LA_ALIST ) LA_DCL
{
    absr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void absr_d_jit(int r1, int r2) { 
    jit_absr_d(r1, r2);
}

/* ABSR_D_JIT(INTEGER,INTEGER) */
ABSR_D_JIT( LA_ALIST ) LA_DCL
{
    absr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void sqrtr_f_jit(int r1, int r2) { 
    jit_sqrtr_f(r1, r2);
}

/* SQRTR_F_JIT(INTEGER,INTEGER) */
SQRTR_F_JIT( LA_ALIST ) LA_DCL
{
    sqrtr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void sqrtr_d_jit(int r1, int r2) { 
    jit_sqrtr_d(r1, r2);
}

/* SQRTR_D_JIT(INTEGER,INTEGER) */
SQRTR_D_JIT( LA_ALIST ) LA_DCL
{
    sqrtr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_c_jit(int r1, int r2) { 
    jit_extr_c(r1, r2);
}

/* EXTR_C_JIT(INTEGER,INTEGER) */
EXTR_C_JIT( LA_ALIST ) LA_DCL
{
    extr_c_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_uc_jit(int r1, int r2) { 
    jit_extr_uc(r1, r2);
}

/* EXTR_UC_JIT(INTEGER,INTEGER) */
EXTR_UC_JIT( LA_ALIST ) LA_DCL
{
    extr_uc_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_s_jit(int r1, int r2) { 
    jit_extr_s(r1, r2);
}

/* EXTR_S_JIT(INTEGER,INTEGER) */
EXTR_S_JIT( LA_ALIST ) LA_DCL
{
    extr_s_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_us_jit(int r1, int r2) { 
    jit_extr_us(r1, r2);
}

/* EXTR_US_JIT(INTEGER,INTEGER) */
EXTR_US_JIT( LA_ALIST ) LA_DCL
{
    extr_us_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_i_jit(int r1, int r2) { 
    jit_extr_i(r1, r2);
}

/* EXTR_I_JIT(INTEGER,INTEGER) */
EXTR_I_JIT( LA_ALIST ) LA_DCL
{
    extr_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_ui_jit(int r1, int r2) { 
    jit_extr_ui(r1, r2);
}

/* EXTR_UI_JIT(INTEGER,INTEGER) */
EXTR_UI_JIT( LA_ALIST ) LA_DCL
{
    extr_ui_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_f_jit(int r1, int r2) { 
    jit_extr_f(r1, r2);
}

/* EXTR_F_JIT(INTEGER,INTEGER) */
EXTR_F_JIT( LA_ALIST ) LA_DCL
{
    extr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_d_f_jit(int r1, int r2) { 
    jit_extr_d_f(r1, r2);
}

/* EXTR_D_F_JIT(INTEGER,INTEGER) */
EXTR_D_F_JIT( LA_ALIST ) LA_DCL
{
    extr_d_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_d_jit(int r1, int r2) { 
    jit_extr_d(r1, r2);
}

/* EXTR_D_JIT(INTEGER,INTEGER) */
EXTR_D_JIT( LA_ALIST ) LA_DCL
{
    extr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void extr_f_d_jit(int r1, int r2) { 
    jit_extr_f_d(r1, r2);
}

/* EXTR_F_D_JIT(INTEGER,INTEGER) */
EXTR_F_D_JIT( LA_ALIST ) LA_DCL
{
    extr_f_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_f_i_jit(int r1, int r2) { 
    jit_truncr_f_i(r1, r2);
}

/* TRUNCR_F_I_JIT(INTEGER,INTEGER) */
TRUNCR_F_I_JIT( LA_ALIST ) LA_DCL
{
    truncr_f_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_f_jit(int r1, int r2) { 
    jit_truncr_f(r1, r2);
}

/* TRUNCR_F_JIT(INTEGER,INTEGER) */
TRUNCR_F_JIT( LA_ALIST ) LA_DCL
{
    truncr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_f_l_jit(int r1, int r2) { 
    jit_truncr_f_l(r1, r2);
}

/* TRUNCR_F_L_JIT(INTEGER,INTEGER) */
TRUNCR_F_L_JIT( LA_ALIST ) LA_DCL
{
    truncr_f_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_d_i_jit(int r1, int r2) { 
    jit_truncr_d_i(r1, r2);
}

/* TRUNCR_D_I_JIT(INTEGER,INTEGER) */
TRUNCR_D_I_JIT( LA_ALIST ) LA_DCL
{
    truncr_d_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_d_jit(int r1, int r2) { 
    jit_truncr_d(r1, r2);
}

/* TRUNCR_D_JIT(INTEGER,INTEGER) */
TRUNCR_D_JIT( LA_ALIST ) LA_DCL
{
    truncr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void truncr_d_l_jit(int r1, int r2) { 
    jit_truncr_d_l(r1, r2);
}

/* TRUNCR_D_L_JIT(INTEGER,INTEGER) */
TRUNCR_D_L_JIT( LA_ALIST ) LA_DCL
{
    truncr_d_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_c_jit(int r1, int r2) { 
    jit_ldr_c(r1, r2);
}

/* LDR_C_JIT(INTEGER,INTEGER) */
LDR_C_JIT( LA_ALIST ) LA_DCL
{
    ldr_c_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_uc_jit(int r1, int r2) { 
    jit_ldr_uc(r1, r2);
}

/* LDR_UC_JIT(INTEGER,INTEGER) */
LDR_UC_JIT( LA_ALIST ) LA_DCL
{
    ldr_uc_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_s_jit(int r1, int r2) { 
    jit_ldr_s(r1, r2);
}

/* LDR_S_JIT(INTEGER,INTEGER) */
LDR_S_JIT( LA_ALIST ) LA_DCL
{
    ldr_s_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_us_jit(int r1, int r2) { 
    jit_ldr_us(r1, r2);
}

/* LDR_US_JIT(INTEGER,INTEGER) */
LDR_US_JIT( LA_ALIST ) LA_DCL
{
    ldr_us_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_i_jit(int r1, int r2) { 
    jit_ldr_i(r1, r2);
}

/* LDR_I_JIT(INTEGER,INTEGER) */
LDR_I_JIT( LA_ALIST ) LA_DCL
{
    ldr_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_jit(int r1, int r2) { 
    jit_ldr(r1, r2);
}

/* LDR_JIT(INTEGER,INTEGER) */
LDR_JIT( LA_ALIST ) LA_DCL
{
    ldr_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_ui_jit(int r1, int r2) { 
    jit_ldr_ui(r1, r2);
}

/* LDR_UI_JIT(INTEGER,INTEGER) */
LDR_UI_JIT( LA_ALIST ) LA_DCL
{
    ldr_ui_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_l_jit(int r1, int r2) { 
    jit_ldr_l(r1, r2);
}

/* LDR_L_JIT(INTEGER,INTEGER) */
LDR_L_JIT( LA_ALIST ) LA_DCL
{
    ldr_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_f_jit(int r1, int r2) { 
    jit_ldr_f(r1, r2);
}

/* LDR_F_JIT(INTEGER,INTEGER) */
LDR_F_JIT( LA_ALIST ) LA_DCL
{
    ldr_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void ldr_d_jit(int r1, int r2) { 
    jit_ldr_d(r1, r2);
}

/* LDR_D_JIT(INTEGER,INTEGER) */
LDR_D_JIT( LA_ALIST ) LA_DCL
{
    ldr_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_c_jit(int r1, int r2) { 
    jit_str_c(r1, r2);
}

/* STR_C_JIT(INTEGER,INTEGER) */
STR_C_JIT( LA_ALIST ) LA_DCL
{
    str_c_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_s_jit(int r1, int r2) { 
    jit_str_s(r1, r2);
}

/* STR_S_JIT(INTEGER,INTEGER) */
STR_S_JIT( LA_ALIST ) LA_DCL
{
    str_s_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_i_jit(int r1, int r2) { 
    jit_str_i(r1, r2);
}

/* STR_I_JIT(INTEGER,INTEGER) */
STR_I_JIT( LA_ALIST ) LA_DCL
{
    str_i_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_jit(int r1, int r2) { 
    jit_str(r1, r2);
}

/* STR_JIT(INTEGER,INTEGER) */
STR_JIT( LA_ALIST ) LA_DCL
{
    str_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_l_jit(int r1, int r2) { 
    jit_str_l(r1, r2);
}

/* STR_L_JIT(INTEGER,INTEGER) */
STR_L_JIT( LA_ALIST ) LA_DCL
{
    str_l_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_f_jit(int r1, int r2) { 
    jit_str_f(r1, r2);
}

/* STR_F_JIT(INTEGER,INTEGER) */
STR_F_JIT( LA_ALIST ) LA_DCL
{
    str_f_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
static void str_d_jit(int r1, int r2) { 
    jit_str_d(r1, r2);
}

/* STR_D_JIT(INTEGER,INTEGER) */
STR_D_JIT( LA_ALIST ) LA_DCL
{
    str_d_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 298 "JIT.lss"

/* THREE REGISTER MOV */
#line 301 "JIT.lss"
#line 302 "JIT.lss"
#line 303 "JIT.lss"
#line 304 "JIT.lss"
static void movr_d_ww_jit(int r,int s,int t) { 
    jit_movr_d_ww(r, s, t);
}

/* MOVR_D_WW_JIT(INTEGER,INTEGER,INTEGER) */
MOVR_D_WW_JIT( LA_ALIST ) LA_DCL
{
    movr_d_ww_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
static void movr_ww_d_jit(int r,int s,int t) { 
    jit_movr_ww_d(r, s, t);
}

/* MOVR_WW_D_JIT(INTEGER,INTEGER,INTEGER) */
MOVR_WW_D_JIT( LA_ALIST ) LA_DCL
{
    movr_ww_d_jit((int)LA_INT(0),(int)LA_INT(1),(int)LA_INT(2));
    RETNULL;
}
#line 310 "JIT.lss"

static void movi_jit(int r1)
{
    set_p_(jit_movi(r1, (jit_word_t)get_p_()));
}


/* MOVI_JIT(INTEGER) */
MOVI_JIT( LA_ALIST ) LA_DCL
{
    movi_jit((int)LA_INT(0));
    RETNULL;
}
#line 317 "JIT.lss"

static void movi_f_jit(int r1)
{
    jit_movi_f(r1, get_f_());
}


/* MOVI_F_JIT(INTEGER) */
MOVI_F_JIT( LA_ALIST ) LA_DCL
{
    movi_f_jit((int)LA_INT(0));
    RETNULL;
}
#line 324 "JIT.lss"

static void movi_d_jit(int r1)
{
    jit_movi_d(r1, get_d_());
}


/* MOVI_D_JIT(INTEGER) */
MOVI_D_JIT( LA_ALIST ) LA_DCL
{
    movi_d_jit((int)LA_INT(0));
    RETNULL;
}
#line 331 "JIT.lss"

static void movi_f_w_jit(int r1)
{
    jit_movi_f_w(r1, get_f_());
}


/* MOVI_F_W_JIT(INTEGER) */
MOVI_F_W_JIT( LA_ALIST ) LA_DCL
{
    movi_f_w_jit((int)LA_INT(0));
    RETNULL;
}
#line 338 "JIT.lss"

static void movi_d_w_jit(int r1)
{
    jit_movi_d_w(r1, get_d_());
}


/* MOVI_D_W_JIT(INTEGER) */
MOVI_D_W_JIT( LA_ALIST ) LA_DCL
{
    movi_d_w_jit((int)LA_INT(0));
    RETNULL;
}
#line 345 "JIT.lss"

static void movi_d_ww_jit(int r1, int r2)
{
    jit_movi_d_ww(r1, r2, get_d_());
}


/* MOVI_D_WW_JIT(INTEGER,INTEGER) */
MOVI_D_WW_JIT( LA_ALIST ) LA_DCL
{
    movi_d_ww_jit((int)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 352 "JIT.lss"

/* ARG */
#line 355 "JIT.lss"
#line 356 "JIT.lss"
#line 357 "JIT.lss"
#line 358 "JIT.lss"
static void arg_jit(void) { 
    set_p_(jit_arg());
}

/* ARG_JIT() */
ARG_JIT( LA_ALIST ) LA_DCL
{
    arg_jit();
    RETNULL;
}
static void arg_f_jit(void) { 
    set_p_(jit_arg_f());
}

/* ARG_F_JIT() */
ARG_F_JIT( LA_ALIST ) LA_DCL
{
    arg_f_jit();
    RETNULL;
}
static void arg_d_jit(void) { 
    set_p_(jit_arg_d());
}

/* ARG_D_JIT() */
ARG_D_JIT( LA_ALIST ) LA_DCL
{
    arg_d_jit();
    RETNULL;
}
#line 363 "JIT.lss"

#line 368 "JIT.lss"
#line 369 "JIT.lss"
#line 370 "JIT.lss"
#line 371 "JIT.lss"
static void getarg_jit(int r) { 
    jit_getarg(r, get_p_());
}

/* GETARG_JIT(INTEGER) */
GETARG_JIT( LA_ALIST ) LA_DCL
{
    getarg_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_c_jit(int r) { 
    jit_getarg_c(r, get_p_());
}

/* GETARG_C_JIT(INTEGER) */
GETARG_C_JIT( LA_ALIST ) LA_DCL
{
    getarg_c_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_uc_jit(int r) { 
    jit_getarg_uc(r, get_p_());
}

/* GETARG_UC_JIT(INTEGER) */
GETARG_UC_JIT( LA_ALIST ) LA_DCL
{
    getarg_uc_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_s_jit(int r) { 
    jit_getarg_s(r, get_p_());
}

/* GETARG_S_JIT(INTEGER) */
GETARG_S_JIT( LA_ALIST ) LA_DCL
{
    getarg_s_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_us_jit(int r) { 
    jit_getarg_us(r, get_p_());
}

/* GETARG_US_JIT(INTEGER) */
GETARG_US_JIT( LA_ALIST ) LA_DCL
{
    getarg_us_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_i_jit(int r) { 
    jit_getarg_i(r, get_p_());
}

/* GETARG_I_JIT(INTEGER) */
GETARG_I_JIT( LA_ALIST ) LA_DCL
{
    getarg_i_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_ui_jit(int r) { 
    jit_getarg_ui(r, get_p_());
}

/* GETARG_UI_JIT(INTEGER) */
GETARG_UI_JIT( LA_ALIST ) LA_DCL
{
    getarg_ui_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_l_jit(int r) { 
    jit_getarg_l(r, get_p_());
}

/* GETARG_L_JIT(INTEGER) */
GETARG_L_JIT( LA_ALIST ) LA_DCL
{
    getarg_l_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_f_jit(int r) { 
    jit_getarg_f(r, get_p_());
}

/* GETARG_F_JIT(INTEGER) */
GETARG_F_JIT( LA_ALIST ) LA_DCL
{
    getarg_f_jit((int)LA_INT(0));
    RETNULL;
}
static void getarg_d_jit(int r) { 
    jit_getarg_d(r, get_p_());
}

/* GETARG_D_JIT(INTEGER) */
GETARG_D_JIT( LA_ALIST ) LA_DCL
{
    getarg_d_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_c_jit(int r) { 
    jit_ldi_c(r, get_p_());
}

/* LDI_C_JIT(INTEGER) */
LDI_C_JIT( LA_ALIST ) LA_DCL
{
    ldi_c_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_uc_jit(int r) { 
    jit_ldi_uc(r, get_p_());
}

/* LDI_UC_JIT(INTEGER) */
LDI_UC_JIT( LA_ALIST ) LA_DCL
{
    ldi_uc_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_s_jit(int r) { 
    jit_ldi_s(r, get_p_());
}

/* LDI_S_JIT(INTEGER) */
LDI_S_JIT( LA_ALIST ) LA_DCL
{
    ldi_s_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_us_jit(int r) { 
    jit_ldi_us(r, get_p_());
}

/* LDI_US_JIT(INTEGER) */
LDI_US_JIT( LA_ALIST ) LA_DCL
{
    ldi_us_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_i_jit(int r) { 
    jit_ldi_i(r, get_p_());
}

/* LDI_I_JIT(INTEGER) */
LDI_I_JIT( LA_ALIST ) LA_DCL
{
    ldi_i_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_jit(int r) { 
    jit_ldi(r, get_p_());
}

/* LDI_JIT(INTEGER) */
LDI_JIT( LA_ALIST ) LA_DCL
{
    ldi_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_ui_jit(int r) { 
    jit_ldi_ui(r, get_p_());
}

/* LDI_UI_JIT(INTEGER) */
LDI_UI_JIT( LA_ALIST ) LA_DCL
{
    ldi_ui_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_l_jit(int r) { 
    jit_ldi_l(r, get_p_());
}

/* LDI_L_JIT(INTEGER) */
LDI_L_JIT( LA_ALIST ) LA_DCL
{
    ldi_l_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_f_jit(int r) { 
    jit_ldi_f(r, get_p_());
}

/* LDI_F_JIT(INTEGER) */
LDI_F_JIT( LA_ALIST ) LA_DCL
{
    ldi_f_jit((int)LA_INT(0));
    RETNULL;
}
static void ldi_d_jit(int r) { 
    jit_ldi_d(r, get_p_());
}

/* LDI_D_JIT(INTEGER) */
LDI_D_JIT( LA_ALIST ) LA_DCL
{
    ldi_d_jit((int)LA_INT(0));
    RETNULL;
}
#line 376 "JIT.lss"

#line 380 "JIT.lss"
#line 381 "JIT.lss"
#line 382 "JIT.lss"
#line 383 "JIT.lss"
static void blti_jit(int r) { 
 set_p_(jit_blti(r, (jit_word_t)get_p_()));
}

/* BLTI_JIT(INTEGER) */
BLTI_JIT( LA_ALIST ) LA_DCL
{
    blti_jit((int)LA_INT(0));
    RETNULL;
}
static void blti_u_jit(int r) { 
 set_p_(jit_blti_u(r, (jit_word_t)get_p_()));
}

/* BLTI_U_JIT(INTEGER) */
BLTI_U_JIT( LA_ALIST ) LA_DCL
{
    blti_u_jit((int)LA_INT(0));
    RETNULL;
}
static void blei_jit(int r) { 
 set_p_(jit_blei(r, (jit_word_t)get_p_()));
}

/* BLEI_JIT(INTEGER) */
BLEI_JIT( LA_ALIST ) LA_DCL
{
    blei_jit((int)LA_INT(0));
    RETNULL;
}
static void blei_u_jit(int r) { 
 set_p_(jit_blei_u(r, (jit_word_t)get_p_()));
}

/* BLEI_U_JIT(INTEGER) */
BLEI_U_JIT( LA_ALIST ) LA_DCL
{
    blei_u_jit((int)LA_INT(0));
    RETNULL;
}
static void beqi_jit(int r) { 
 set_p_(jit_beqi(r, (jit_word_t)get_p_()));
}

/* BEQI_JIT(INTEGER) */
BEQI_JIT( LA_ALIST ) LA_DCL
{
    beqi_jit((int)LA_INT(0));
    RETNULL;
}
static void bgei_jit(int r) { 
 set_p_(jit_bgei(r, (jit_word_t)get_p_()));
}

/* BGEI_JIT(INTEGER) */
BGEI_JIT( LA_ALIST ) LA_DCL
{
    bgei_jit((int)LA_INT(0));
    RETNULL;
}
static void bgei_u_jit(int r) { 
 set_p_(jit_bgei_u(r, (jit_word_t)get_p_()));
}

/* BGEI_U_JIT(INTEGER) */
BGEI_U_JIT( LA_ALIST ) LA_DCL
{
    bgei_u_jit((int)LA_INT(0));
    RETNULL;
}
static void bgti_jit(int r) { 
 set_p_(jit_bgti(r, (jit_word_t)get_p_()));
}

/* BGTI_JIT(INTEGER) */
BGTI_JIT( LA_ALIST ) LA_DCL
{
    bgti_jit((int)LA_INT(0));
    RETNULL;
}
static void bgti_u_jit(int r) { 
 set_p_(jit_bgti_u(r, (jit_word_t)get_p_()));
}

/* BGTI_U_JIT(INTEGER) */
BGTI_U_JIT( LA_ALIST ) LA_DCL
{
    bgti_u_jit((int)LA_INT(0));
    RETNULL;
}
static void bnei_jit(int r) { 
 set_p_(jit_bnei(r, (jit_word_t)get_p_()));
}

/* BNEI_JIT(INTEGER) */
BNEI_JIT( LA_ALIST ) LA_DCL
{
    bnei_jit((int)LA_INT(0));
    RETNULL;
}
static void bmsi_jit(int r) { 
 set_p_(jit_bmsi(r, (jit_word_t)get_p_()));
}

/* BMSI_JIT(INTEGER) */
BMSI_JIT( LA_ALIST ) LA_DCL
{
    bmsi_jit((int)LA_INT(0));
    RETNULL;
}
static void bmci_jit(int r) { 
 set_p_(jit_bmci(r, (jit_word_t)get_p_()));
}

/* BMCI_JIT(INTEGER) */
BMCI_JIT( LA_ALIST ) LA_DCL
{
    bmci_jit((int)LA_INT(0));
    RETNULL;
}
static void boaddi_jit(int r) { 
 set_p_(jit_boaddi(r, (jit_word_t)get_p_()));
}

/* BOADDI_JIT(INTEGER) */
BOADDI_JIT( LA_ALIST ) LA_DCL
{
    boaddi_jit((int)LA_INT(0));
    RETNULL;
}
static void boaddi_u_jit(int r) { 
 set_p_(jit_boaddi_u(r, (jit_word_t)get_p_()));
}

/* BOADDI_U_JIT(INTEGER) */
BOADDI_U_JIT( LA_ALIST ) LA_DCL
{
    boaddi_u_jit((int)LA_INT(0));
    RETNULL;
}
static void bxaddi_jit(int r) { 
 set_p_(jit_bxaddi(r, (jit_word_t)get_p_()));
}

/* BXADDI_JIT(INTEGER) */
BXADDI_JIT( LA_ALIST ) LA_DCL
{
    bxaddi_jit((int)LA_INT(0));
    RETNULL;
}
static void bxaddi_u_jit(int r) { 
 set_p_(jit_bxaddi_u(r, (jit_word_t)get_p_()));
}

/* BXADDI_U_JIT(INTEGER) */
BXADDI_U_JIT( LA_ALIST ) LA_DCL
{
    bxaddi_u_jit((int)LA_INT(0));
    RETNULL;
}
static void bosubi_jit(int r) { 
 set_p_(jit_bosubi(r, (jit_word_t)get_p_()));
}

/* BOSUBI_JIT(INTEGER) */
BOSUBI_JIT( LA_ALIST ) LA_DCL
{
    bosubi_jit((int)LA_INT(0));
    RETNULL;
}
static void bosubi_u_jit(int r) { 
 set_p_(jit_bosubi_u(r, (jit_word_t)get_p_()));
}

/* BOSUBI_U_JIT(INTEGER) */
BOSUBI_U_JIT( LA_ALIST ) LA_DCL
{
    bosubi_u_jit((int)LA_INT(0));
    RETNULL;
}
static void bxsubi_jit(int r) { 
 set_p_(jit_bxsubi(r, (jit_word_t)get_p_()));
}

/* BXSUBI_JIT(INTEGER) */
BXSUBI_JIT( LA_ALIST ) LA_DCL
{
    bxsubi_jit((int)LA_INT(0));
    RETNULL;
}
static void bxsubi_u_jit(int r) { 
 set_p_(jit_bxsubi_u(r, (jit_word_t)get_p_()));
}

/* BXSUBI_U_JIT(INTEGER) */
BXSUBI_U_JIT( LA_ALIST ) LA_DCL
{
    bxsubi_u_jit((int)LA_INT(0));
    RETNULL;
}
#line 388 "JIT.lss"

#line 390 "JIT.lss"
#line 391 "JIT.lss"
#line 392 "JIT.lss"
#line 393 "JIT.lss"
static void sti_c_jit(int r) { 
    jit_sti_c(get_p_(), r);
}

/* STI_C_JIT(INTEGER) */
STI_C_JIT( LA_ALIST ) LA_DCL
{
    sti_c_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_s_jit(int r) { 
    jit_sti_s(get_p_(), r);
}

/* STI_S_JIT(INTEGER) */
STI_S_JIT( LA_ALIST ) LA_DCL
{
    sti_s_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_i_jit(int r) { 
    jit_sti_i(get_p_(), r);
}

/* STI_I_JIT(INTEGER) */
STI_I_JIT( LA_ALIST ) LA_DCL
{
    sti_i_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_jit(int r) { 
    jit_sti(get_p_(), r);
}

/* STI_JIT(INTEGER) */
STI_JIT( LA_ALIST ) LA_DCL
{
    sti_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_l_jit(int r) { 
    jit_sti_l(get_p_(), r);
}

/* STI_L_JIT(INTEGER) */
STI_L_JIT( LA_ALIST ) LA_DCL
{
    sti_l_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_f_jit(int r) { 
    jit_sti_f(get_p_(), r);
}

/* STI_F_JIT(INTEGER) */
STI_F_JIT( LA_ALIST ) LA_DCL
{
    sti_f_jit((int)LA_INT(0));
    RETNULL;
}
static void sti_d_jit(int r) { 
    jit_sti_d(get_p_(), r);
}

/* STI_D_JIT(INTEGER) */
STI_D_JIT( LA_ALIST ) LA_DCL
{
    sti_d_jit((int)LA_INT(0));
    RETNULL;
}
#line 398 "JIT.lss"

#line 403 "JIT.lss"
#line 404 "JIT.lss"
#line 405 "JIT.lss"
#line 406 "JIT.lss"
static void pushargr_jit(int r) { 
    jit_pushargr(r);
}

/* PUSHARGR_JIT(INTEGER) */
PUSHARGR_JIT( LA_ALIST ) LA_DCL
{
    pushargr_jit((int)LA_INT(0));
    RETNULL;
}
static void pushargr_f_jit(int r) { 
    jit_pushargr_f(r);
}

/* PUSHARGR_F_JIT(INTEGER) */
PUSHARGR_F_JIT( LA_ALIST ) LA_DCL
{
    pushargr_f_jit((int)LA_INT(0));
    RETNULL;
}
static void pushargr_d_jit(int r) { 
    jit_pushargr_d(r);
}

/* PUSHARGR_D_JIT(INTEGER) */
PUSHARGR_D_JIT( LA_ALIST ) LA_DCL
{
    pushargr_d_jit((int)LA_INT(0));
    RETNULL;
}
static void retr_jit(int r) { 
    jit_retr(r);
}

/* RETR_JIT(INTEGER) */
RETR_JIT( LA_ALIST ) LA_DCL
{
    retr_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_c_jit(int r) { 
    jit_retval_c(r);
}

/* RETVAL_C_JIT(INTEGER) */
RETVAL_C_JIT( LA_ALIST ) LA_DCL
{
    retval_c_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_uc_jit(int r) { 
    jit_retval_uc(r);
}

/* RETVAL_UC_JIT(INTEGER) */
RETVAL_UC_JIT( LA_ALIST ) LA_DCL
{
    retval_uc_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_s_jit(int r) { 
    jit_retval_s(r);
}

/* RETVAL_S_JIT(INTEGER) */
RETVAL_S_JIT( LA_ALIST ) LA_DCL
{
    retval_s_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_us_jit(int r) { 
    jit_retval_us(r);
}

/* RETVAL_US_JIT(INTEGER) */
RETVAL_US_JIT( LA_ALIST ) LA_DCL
{
    retval_us_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_i_jit(int r) { 
    jit_retval_i(r);
}

/* RETVAL_I_JIT(INTEGER) */
RETVAL_I_JIT( LA_ALIST ) LA_DCL
{
    retval_i_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_jit(int r) { 
    jit_retval(r);
}

/* RETVAL_JIT(INTEGER) */
RETVAL_JIT( LA_ALIST ) LA_DCL
{
    retval_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_ui_jit(int r) { 
    jit_retval_ui(r);
}

/* RETVAL_UI_JIT(INTEGER) */
RETVAL_UI_JIT( LA_ALIST ) LA_DCL
{
    retval_ui_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_l_jit(int r) { 
    jit_retval_l(r);
}

/* RETVAL_L_JIT(INTEGER) */
RETVAL_L_JIT( LA_ALIST ) LA_DCL
{
    retval_l_jit((int)LA_INT(0));
    RETNULL;
}
static void retr_f_jit(int r) { 
    jit_retr_f(r);
}

/* RETR_F_JIT(INTEGER) */
RETR_F_JIT( LA_ALIST ) LA_DCL
{
    retr_f_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_f_jit(int r) { 
    jit_retval_f(r);
}

/* RETVAL_F_JIT(INTEGER) */
RETVAL_F_JIT( LA_ALIST ) LA_DCL
{
    retval_f_jit((int)LA_INT(0));
    RETNULL;
}
static void retr_d_jit(int r) { 
    jit_retr_d(r);
}

/* RETR_D_JIT(INTEGER) */
RETR_D_JIT( LA_ALIST ) LA_DCL
{
    retr_d_jit((int)LA_INT(0));
    RETNULL;
}
static void retval_d_jit(int r) { 
    jit_retval_d(r);
}

/* RETVAL_D_JIT(INTEGER) */
RETVAL_D_JIT( LA_ALIST ) LA_DCL
{
    retval_d_jit((int)LA_INT(0));
    RETNULL;
}
#line 411 "JIT.lss"

static void pushargi_jit(void) { jit_pushargi((jit_word_t)get_p_()); }


/* PUSHARGI_JIT() */
PUSHARGI_JIT( LA_ALIST ) LA_DCL
{
    pushargi_jit();
    RETNULL;
}
#line 415 "JIT.lss"

static void pushargi_f_jit(void) { jit_pushargi_f(get_f_()); }


/* PUSHARGI_F_JIT() */
PUSHARGI_F_JIT( LA_ALIST ) LA_DCL
{
    pushargi_f_jit();
    RETNULL;
}
#line 419 "JIT.lss"

static void pushargi_d_jit(void) { jit_pushargi_d(get_d_()); }


/* PUSHARGI_D_JIT() */
PUSHARGI_D_JIT( LA_ALIST ) LA_DCL
{
    pushargi_d_jit();
    RETNULL;
}
#line 423 "JIT.lss"

static void jmpr_jit(int r) { jit_jmpr(r); }


/* JMPR_JIT(INTEGER) */
JMPR_JIT( LA_ALIST ) LA_DCL
{
    jmpr_jit((int)LA_INT(0));
    RETNULL;
}
#line 427 "JIT.lss"

static void jmpi_jit(void) { set_p_(jit_jmpi()); }


/* JMPI_JIT() */
JMPI_JIT( LA_ALIST ) LA_DCL
{
    jmpi_jit();
    RETNULL;
}
#line 431 "JIT.lss"

static void callr_jit(int r) { jit_callr(r); }


/* CALLR_JIT(INTEGER) */
CALLR_JIT( LA_ALIST ) LA_DCL
{
    callr_jit((int)LA_INT(0));
    RETNULL;
}
#line 435 "JIT.lss"

static void calli_jit(void) { set_p_(jit_calli(get_p_())); }


/* CAllI_JIT() */
CAllI_JIT( LA_ALIST ) LA_DCL
{
    calli_jit();
    RETNULL;
}
#line 439 "JIT.lss"

static void finishr_jit(int r) { jit_finishr(r); }


/* FINISHR_JIT(INTEGER) */
FINISHR_JIT( LA_ALIST ) LA_DCL
{
    finishr_jit((int)LA_INT(0));
    RETNULL;
}
#line 443 "JIT.lss"

static void finishi_jit(void) { set_p_(jit_finishi(get_p_())); }


/* FINISHI_JIT() */
FINISHI_JIT( LA_ALIST ) LA_DCL
{
    finishi_jit();
    RETNULL;
}
#line 447 "JIT.lss"

static void ret_jit(void) { jit_ret(); }


/* RET_JIT() */
RET_JIT( LA_ALIST ) LA_DCL
{
    ret_jit();
    RETNULL;
}
#line 451 "JIT.lss"

static void reti_jit(void) { jit_reti((jit_word_t)get_p_()); }


/* RETI_JIT() */
RETI_JIT( LA_ALIST ) LA_DCL
{
    reti_jit();
    RETNULL;
}
#line 455 "JIT.lss"

static void reti_f_jit(void) { jit_reti_f(get_f_()); }


/* RETI_F_JIT() */
RETI_F_JIT( LA_ALIST ) LA_DCL
{
    reti_f_jit();
    RETNULL;
}
#line 459 "JIT.lss"

static void reti_d_jit(void) { jit_reti_d(get_d_()); }


/* RETI_D_JIT() */
RETI_D_JIT( LA_ALIST ) LA_DCL
{
    reti_d_jit();
    RETNULL;
}
#line 463 "JIT.lss"

