{
  "SOURCE": "JIT.lss",
  "COMMENT": "JIT module",
  "ARTIFACTS": [
    "JIT.INC",
    "JIT.html",
    "JIT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "JIT",
  "DEPENDS": [
    "CRACK",
    "SEQ"
  ],
  "INSTALL": [
    {
      "TARGET": "JIT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "JIT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "JIT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "JIT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "JIT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "JIT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "JIT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402368279",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e31f650ea7e9d8f00a5fedc106bbee07",
      "SIZE": 73433
    },
    {
      "NAME": "JIT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394874",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "0d81269b480047378c0f831f28a91699",
      "SIZE": 56318
    },
    {
      "NAME": "JIT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402368284",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "721d20ffb1878c806feebd70a0feaa31",
      "SIZE": 99195
    },
    {
      "NAME": "JIT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402368283",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "7793e1abe128877cf14c3e230b4e9055",
      "SIZE": 137
    }
  ]
}