{
  "SOURCE": "LAST.lss",
  "COMMENT": "LAST module",
  "ARTIFACTS": [
    "LAST.INC",
    "LAST.html",
    "LAST.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "LAST",
  "DEPENDS": [
    "LINK"
  ],
  "INSTALL": [
    {
      "TARGET": "LAST.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LAST.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LAST.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "LAST.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LAST.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LAST.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "LAST.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012740",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "d61c7a955cc10f3eacc2f5ede8da117b",
      "SIZE": 1853
    },
    {
      "NAME": "LAST.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012774",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "d162c34fa0dd4137cb80f06aff4f1a8f",
      "SIZE": 1417
    },
    {
      "NAME": "LAST.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012809",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "536a249774b044ea4dde5531bd87d521",
      "SIZE": 4173
    },
    {
      "NAME": "LAST.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012779",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "7ede4f287c5e67c67186a4cd262f4475",
      "SIZE": 137
    }
  ]
}