{
  "SOURCE": "list.lss",
  "COMMENT": "list module",
  "ARTIFACTS": [
    "list",
    "list.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "LIST",
  "DEPENDS": [
    "CHARS",
    "DISPLAY",
    "GETKEY",
    "HOST",
    "LOGIC",
    "READLINE",
    "REPL",
    "SEQ"
  ],
  "INSTALL": [
    {
      "TARGET": "list",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "list.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "list",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "list.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "list.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402079208",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "0f1ee7c56377674e0431a147088074c8",
      "SIZE": 8483
    },
    {
      "NAME": "list",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281634",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "d3840472e7fc726cbbd5aab7572a7f0d",
      "SIZE": 7865
    },
    {
      "NAME": "list.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402079210",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "3dad958863d8d74a3af83707779adf8a",
      "SIZE": 12565
    }
  ]
}