{
  "SOURCE": "LOG.lss",
  "COMMENT": "LOG module",
  "ARTIFACTS": [
    "LOG.INC",
    "LOG.html",
    "LOG.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "LOG",
  "DEPENDS": [
    "DEXP"
  ],
  "INSTALL": [
    {
      "TARGET": "LOG.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "LOG.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "LOG.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012742",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "5d12132523254cf4b79f4f425e4a5045",
      "SIZE": 2363
    },
    {
      "NAME": "LOG.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "419557e5ff0d14213335622d479bd6b7",
      "SIZE": 1674
    },
    {
      "NAME": "LOG.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012810",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "cfa5e0b59d6bec111c78bb39842b9448",
      "SIZE": 4818
    },
    {
      "NAME": "LOG.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "9aecc4042197cbe5acd30cc6895c2670",
      "SIZE": 344
    }
  ]
}