{
  "SOURCE": "LOG.lss",
  "COMMENT": "LOG module",
  "ARTIFACTS": [
    "LOG.INC",
    "LOG.html",
    "LOG.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "LOG",
  "DEPENDS": [
    "DEXP"
  ],
  "INSTALL": [
    {
      "TARGET": "LOG.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "LOG.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "LOG.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "LOG.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012742",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "LOG.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "LOG.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012810",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "LOG.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}