{
  "SOURCE": "lsinc.lss",
  "COMMENT": "lsinc module",
  "ARTIFACTS": [
    "lsinc",
    "lsinc.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "LSINC",
  "DEPENDS": [
    "CRACK",
    "HOST",
    "SEQ",
    "TRIMB"
  ],
  "INSTALL": [
    {
      "TARGET": "lsinc",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "lsinc.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "lsinc",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "lsinc.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "lsinc.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012743",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "cb58e961b4695dfd11b7fb9326c7f2b7",
      "SIZE": 3438
    },
    {
      "NAME": "lsinc",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "b36c19d30faa5f763dc02223967a0886",
      "SIZE": 3261
    },
    {
      "NAME": "lsinc.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012812",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "25e4f5e10c82f589305af5287934c144",
      "SIZE": 5792
    }
  ]
}