{
  "SOURCE": "MDY.lss",
  "COMMENT": "MDY module",
  "ARTIFACTS": [
    "MDY.INC",
    "MDY.html",
    "MDY.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "MDY",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "MDY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "MDY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "MDY.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012743",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "MDY.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "MDY.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012813",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "MDY.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}