{
  "SOURCE": "MDY.lss",
  "COMMENT": "MDY module",
  "ARTIFACTS": [
    "MDY.INC",
    "MDY.html",
    "MDY.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "MDY",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "MDY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "MDY.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "MDY.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "MDY.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012743",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "42a345c927cd3879ed200638d38b05d6",
      "SIZE": 2331
    },
    {
      "NAME": "MDY.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "bd2c75a17bdd8e6ac6f4d35c7b963548",
      "SIZE": 1941
    },
    {
      "NAME": "MDY.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012813",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "ec109aa5320dfde0a3a0d1a052910ad3",
      "SIZE": 4591
    },
    {
      "NAME": "MDY.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "46624c6e3222932fb7d424464aa2879c",
      "SIZE": 135
    }
  ]
}