{
  "SOURCE": "NDBM.lss",
  "COMMENT": "NDBM module",
  "ARTIFACTS": [
    "NDBM.INC",
    "NDBM.html",
    "NDBM.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "NDBM",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "NDBM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NDBM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NDBM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "NDBM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NDBM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NDBM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "NDBM.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012744",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "15e9e062587f06be5f4507524910e339",
      "SIZE": 3174
    },
    {
      "NAME": "NDBM.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "7a7d60e06fe806b6b0e7a8342532df71",
      "SIZE": 1997
    },
    {
      "NAME": "NDBM.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012813",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "0c329a9f9adc0d71d6d090585273180c",
      "SIZE": 5761
    },
    {
      "NAME": "NDBM.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "871b911b8be4404c7f5f8cbd3be7166e",
      "SIZE": 958
    }
  ]
}