{
  "SOURCE": "NOTP.lss",
  "COMMENT": "NOTP module",
  "ARTIFACTS": [
    "NOTP.INC",
    "NOTP.html",
    "NOTP.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "NOTP",
  "DEPENDS": [
    "STACK"
  ],
  "INSTALL": [
    {
      "TARGET": "NOTP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NOTP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NOTP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "NOTP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NOTP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "NOTP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "NOTP.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012744",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "49a2add2572da38bc8402870f2529fb2",
      "SIZE": 1959
    },
    {
      "NAME": "NOTP.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "ff8b53851edcd63e3748159599dd8496",
      "SIZE": 1342
    },
    {
      "NAME": "NOTP.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012814",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "18fc4a53d9a5756d173ecf0b0a6a632d",
      "SIZE": 4620
    },
    {
      "NAME": "NOTP.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "7413d159684caee999d0fe90c50fd21c",
      "SIZE": 137
    }
  ]
}