{
  "SOURCE": "ORDER.lss",
  "COMMENT": "ORDER module",
  "ARTIFACTS": [
    "ORDER.INC",
    "ORDER.html",
    "ORDER.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "ORDER",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "ORDER.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ORDER.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ORDER.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "ORDER.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ORDER.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ORDER.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "ORDER.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012744",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "b3dc95a012334c16eda1eb2c6bb1f3e5",
      "SIZE": 1742
    },
    {
      "NAME": "ORDER.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "620832ec1cf655b246cfd037ec4a6950",
      "SIZE": 1351
    },
    {
      "NAME": "ORDER.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012815",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "1f3f92306fc4f9a6e5ffc138afadd65c",
      "SIZE": 3961
    },
    {
      "NAME": "ORDER.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "24da91f1290dd22916082180a6593615",
      "SIZE": 212
    }
  ]
}