{
  "SOURCE": "P64.lss",
  "COMMENT": "P64 module",
  "ARTIFACTS": [
    "P64.INC",
    "P64.html",
    "P64.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "P64",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "P64.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "P64.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "P64.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "P64.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "P64.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "P64.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "P64.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402261818",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6bb59f9b046a5713e71ace0d21f8f677",
      "SIZE": 6136
    },
    {
      "NAME": "P64.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394872",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "391467d1e7d4b446ecfd52cc73d0d357",
      "SIZE": 2931
    },
    {
      "NAME": "P64.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402262511",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "aac39bb03e658acd3a0c33a9e7673272",
      "SIZE": 10337
    },
    {
      "NAME": "P64.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402262514",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "c99d2701f11ada8faca8af76c0c013ab",
      "SIZE": 136
    }
  ]
}