#line 54 "P64.lss"
/* Generated by WRAPPER on 08/31/2014 15:19:05 */

#include "config.h"
#include "h.h"
#include "snotypes.h"
#include "macros.h"
#include "load.h"
#include "equ.h"
#include <string.h>

#line 55 "P64.lss"

#include <stdlib.h>
#include <string.h>

/* PEEK_STRING(INTEGER)STRING */

PEEK_STRING( LA_ALIST ) LA_DCL
{
    char *p = LA_PTR(0);
    RETSTR(p);
}

/* POKE_STRING(INTEGER,STRING) */

POKE_STRING( LA_ALIST ) LA_DCL
{
    char *p = LA_PTR(0);
    char *s = LA_STR_PTR(1);
    int n = LA_STR_LEN(1);
    memcpy(p, s, n);
    p[n] = 0;
    RETNULL;
}

/* PEEK_BUFFER(INTEGER,INTEGER)STRING */

PEEK_BUFFER( LA_ALIST ) LA_DCL
{
    char *p = LA_PTR(0);
    int n = LA_INT(1);
    RETSTR2(p, n);
}

/* POKE_BUFFER(INTEGER,STRING) */

POKE_BUFFER( LA_ALIST ) LA_DCL
{
    char *p = LA_PTR(0);
    char *s = LA_STR_PTR(1);
    int n = LA_STR_LEN(1);
    memcpy(p, s, n);
    RETNULL;
}

static long peek_p(long p) { return (long)*(void **)p; }


/* PEEK_P(LONG)LONG */
PEEK_P( LA_ALIST ) LA_DCL
{
    RETINT((long)peek_p((long)LA_INT(0)));
}
#line 102 "P64.lss"

static long peek_c(long p) { return *(unsigned char *)p; }


/* PEEK_C(LONG)INTEGER */
PEEK_C( LA_ALIST ) LA_DCL
{
    RETINT(peek_c((long)LA_INT(0)));
}
#line 106 "P64.lss"

static long peek_s(long p) { return *(short *)p; }


/* PEEK_S(LONG)INTEGER */
PEEK_S( LA_ALIST ) LA_DCL
{
    RETINT(peek_s((long)LA_INT(0)));
}
#line 110 "P64.lss"

static long peek_i(long p) { return *(int *)p; }


/* PEEK_I(LONG)INTEGER */
PEEK_I( LA_ALIST ) LA_DCL
{
    RETINT(peek_i((long)LA_INT(0)));
}
#line 114 "P64.lss"

static double peek_d(long p) { return *(double *)p; }


/* PEEK_D(LONG)REAL */
PEEK_D( LA_ALIST ) LA_DCL
{
    RETREAL(peek_d((long)LA_INT(0)));
}
#line 118 "P64.lss"

static double peek_f(long p) { return *(float *)p; }


/* PEEK_F(LONG)REAL */
PEEK_F( LA_ALIST ) LA_DCL
{
    RETREAL(peek_f((long)LA_INT(0)));
}
#line 122 "P64.lss"

static double peek_ld(long p) { return *(long double *)p; }


/* PEEK_LD(LONG)REAL */
PEEK_LD( LA_ALIST ) LA_DCL
{
    RETREAL(peek_ld((long)LA_INT(0)));
}
#line 126 "P64.lss"

static void poke_p(long p, long v) { *(void **)p = (void *)v; }


/* POKE_P(LONG,LONG) */
POKE_P( LA_ALIST ) LA_DCL
{
    poke_p((long)LA_INT(0),(long)LA_INT(1));
    RETNULL;
}
#line 130 "P64.lss"

static void poke_c(long p, int c)
{
    *(unsigned char *)p = (unsigned char)c;
}


/* POKE_C(LONG,INTEGER) */
POKE_C( LA_ALIST ) LA_DCL
{
    poke_c((long)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 137 "P64.lss"

static void poke_s(long p, int s) { *(short *)p = (short)s; }


/* POKE_S(LONG,INTEGER) */
POKE_S( LA_ALIST ) LA_DCL
{
    poke_s((long)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 141 "P64.lss"

static void poke_i(long p, int i) { *(int *)p = (int)i; }


/* POKE_I(LONG,INTEGER) */
POKE_I( LA_ALIST ) LA_DCL
{
    poke_i((long)LA_INT(0),(int)LA_INT(1));
    RETNULL;
}
#line 145 "P64.lss"

static void poke_d(long p, double v) { *(double *)p = v; }


/* POKE_D(LONG,REAL) */
POKE_D( LA_ALIST ) LA_DCL
{
    poke_d((long)LA_INT(0),(double)LA_REAL(1));
    RETNULL;
}
#line 149 "P64.lss"

static void poke_f(long p, double v) { *(float *)p = v; }


/* POKE_F(LONG,REAL) */
POKE_F( LA_ALIST ) LA_DCL
{
    poke_f((long)LA_INT(0),(double)LA_REAL(1));
    RETNULL;
}
#line 153 "P64.lss"

static void poke_ld(long p, double v) { *(long double *)p = v; }


/* POKE_LD(LONG,REAL) */
POKE_LD( LA_ALIST ) LA_DCL
{
    poke_ld((long)LA_INT(0),(double)LA_REAL(1));
    RETNULL;
}
#line 157 "P64.lss"

