{
  "SOURCE": "PSQL.lss",
  "COMMENT": "PSQL module",
  "ARTIFACTS": [
    "PSQL.INC",
    "PSQL.html",
    "PSQL.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "PSQL",
  "DEPENDS": [
    "BRKREM",
    "CHARS",
    "COUNT",
    "CSNOBOL4",
    "REPL",
    "SCOOP",
    "SEQ",
    "UNIQUE"
  ],
  "INSTALL": [
    {
      "TARGET": "PSQL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "PSQL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "PSQL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "PSQL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "PSQL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "PSQL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "PSQL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012745",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "PSQL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402195044",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "PSQL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012836",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "PSQL.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}