{
  "SOURCE": "RANDOM.lss",
  "COMMENT": "RANDOM module",
  "ARTIFACTS": [
    "RANDOM.INC",
    "RANDOM.html",
    "RANDOM.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "RANDOM",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "RANDOM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "RANDOM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "RANDOM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "RANDOM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "RANDOM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "RANDOM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "RANDOM.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012746",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "37c339744859e8c9cce39e791d8f41d1",
      "SIZE": 2132
    },
    {
      "NAME": "RANDOM.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "b94390927f7ae65ffebc301e07afa0f9",
      "SIZE": 1802
    },
    {
      "NAME": "RANDOM.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012817",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "94d415de9520102863514c12b21e3253",
      "SIZE": 4471
    },
    {
      "NAME": "RANDOM.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "c9b66a4ca910e9f128ff7bfcce65a3bf",
      "SIZE": 141
    }
  ]
}