{
  "SOURCE": "READLINE.lss",
  "COMMENT": "READLINE module",
  "ARTIFACTS": [
    "READLINE.INC",
    "READLINE.html",
    "READLINE.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "READLINE",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "READLINE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READLINE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READLINE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "READLINE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READLINE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READLINE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "READLINE.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281632",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "4fddc6914ad682fcc73b3fb75f256002",
      "SIZE": 5146
    },
    {
      "NAME": "READLINE.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281634",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "9c74045afd30ba68e0f9b5dab54171ca",
      "SIZE": 2328
    },
    {
      "NAME": "READLINE.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281635",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "3d8e37559a4a2a792c8614e912752e83",
      "SIZE": 8344
    },
    {
      "NAME": "READLINE.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402281634",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "bd513428e71f1f45118f16516764ad31",
      "SIZE": 146
    }
  ]
}