{
  "SOURCE": "READFILE.lss",
  "COMMENT": "READFILE module",
  "ARTIFACTS": [
    "READFILE.INC",
    "READFILE.html",
    "READFILE.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "READFILE",
  "DEPENDS": [
    "BRKREM",
    "CHARS",
    "SYSTEM"
  ],
  "INSTALL": [
    {
      "TARGET": "READFILE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READFILE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READFILE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "READFILE.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READFILE.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "READFILE.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "READFILE.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012746",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "f5d2b2cf4ac43a008263f5a500b9ad1b",
      "SIZE": 3494
    },
    {
      "NAME": "READFILE.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "70d0a74f49086e368437e3144a212fbc",
      "SIZE": 2543
    },
    {
      "NAME": "READFILE.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012841",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "202c8f8d5783c36f3572056599d142b5",
      "SIZE": 6036
    },
    {
      "NAME": "READFILE.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "c36da357c0bc00f29bc7f50602b64233",
      "SIZE": 218
    }
  ]
}