{
  "SOURCE": "REVL.lss",
  "COMMENT": "REVL module",
  "ARTIFACTS": [
    "REVL.INC",
    "REVL.html",
    "REVL.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "REVL",
  "DEPENDS": [
    "LINK"
  ],
  "INSTALL": [
    {
      "TARGET": "REVL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "REVL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "REVL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "REVL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "REVL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "REVL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "REVL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012748",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "66ec94f252ade140a2e3dda293bf0711",
      "SIZE": 1923
    },
    {
      "NAME": "REVL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012775",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "7af608872d3a174d4bdd04e8f7d6a06a",
      "SIZE": 1544
    },
    {
      "NAME": "REVL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012820",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "c4c42596b0ff789a868ed8d64c5b53c8",
      "SIZE": 4091
    },
    {
      "NAME": "REVL.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "a166eb7f73001c95404fd0ec4f4265ff",
      "SIZE": 137
    }
  ]
}