{
  "SOURCE": "ROUTING.lss",
  "COMMENT": "ROUTING module",
  "ARTIFACTS": [
    "ROUTING.INC",
    "ROUTING.html",
    "ROUTING.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "ROUTING",
  "DEPENDS": [
    "BRKREM",
    "SDIFF",
    "UNIQUE"
  ],
  "INSTALL": [
    {
      "TARGET": "ROUTING.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ROUTING.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ROUTING.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "ROUTING.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ROUTING.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "ROUTING.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "ROUTING.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012749",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "0d4d365d39a024554656557d74623edf",
      "SIZE": 4434
    },
    {
      "NAME": "ROUTING.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012778",
      "ACCESS": "600",
      "LOCATION": "FILE",
      "MD5": "ffc0895265ddf973bd7d3f6fa8b19287",
      "SIZE": 2794
    },
    {
      "NAME": "ROUTING.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012848",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "55801cd7fb196d0e6533956d6c027a7b",
      "SIZE": 8185
    },
    {
      "NAME": "ROUTING.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "c1a76a8fe53e0aa44e50bc71ba98d9a0",
      "SIZE": 1235
    }
  ]
}