{
  "SOURCE": "rseq.lss",
  "COMMENT": "rseq module",
  "ARTIFACTS": [
    "rseq",
    "rseq.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "RSEQ",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "rseq",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "rseq.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "rseq",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "rseq.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "rseq.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012749",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "41ee2ec3ecbdffe93d2f96e1ed374296",
      "SIZE": 1536
    },
    {
      "NAME": "rseq",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012783",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "0938fd7e63cf106d12f4e32fcb4338f4",
      "SIZE": 1455
    },
    {
      "NAME": "rseq.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012821",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "8935605627d9285b746756d0dfd14932",
      "SIZE": 3535
    }
  ]
}