{
  "SOURCE": "scan.lss",
  "COMMENT": "scan module",
  "ARTIFACTS": [
    "scan",
    "scan.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "SCAN",
  "DEPENDS": [
    "HOST",
    "SLOAD"
  ],
  "INSTALL": [
    {
      "TARGET": "scan",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "scan.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "scan",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "scan.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "scan.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012749",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "b9a374b701ac7097acd6efee23ae03d5",
      "SIZE": 5218
    },
    {
      "NAME": "scan",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012784",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "e7562c10a3bac27edc8ce0207ccadce7",
      "SIZE": 3383
    },
    {
      "NAME": "scan.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012839",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "19f18fae6cc3f13d9b2d2c54240fc5df",
      "SIZE": 8530
    }
  ]
}