{
  "SOURCE": "SCOOP.lss",
  "COMMENT": "SCOOP module",
  "ARTIFACTS": [
    "SCOOP.INC",
    "SCOOP.html",
    "SCOOP.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SCOOP",
  "DEPENDS": [
    "VDIFFER"
  ],
  "INSTALL": [
    {
      "TARGET": "SCOOP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SCOOP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SCOOP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SCOOP.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SCOOP.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SCOOP.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SCOOP.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012750",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "c5c27ff5edecaf40be1839dc3960e6ee",
      "SIZE": 12344
    },
    {
      "NAME": "SCOOP.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012777",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6682b6248a7aa6e1eb08e182d1037b6c",
      "SIZE": 6455
    },
    {
      "NAME": "SCOOP.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012840",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "52c3dc902774e007ed96804be6abf5b0",
      "SIZE": 20646
    },
    {
      "NAME": "SCOOP.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "6c10dc641f69cb68d6ebce7d60da2a23",
      "SIZE": 1411
    }
  ]
}