{
  "SOURCE": "SESSION.lss",
  "COMMENT": "SESSION module",
  "ARTIFACTS": [
    "SESSION.INC",
    "SESSION.html",
    "SESSION.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SESSION",
  "DEPENDS": [
    "BQ",
    "CHARS",
    "CRACK",
    "JSON",
    "NDBM",
    "READFILE",
    "REPL",
    "TIME"
  ],
  "INSTALL": [
    {
      "TARGET": "SESSION.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SESSION.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SESSION.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SESSION.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SESSION.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SESSION.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SESSION.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012750",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "307b8ec461ac751b91da4fb6f53c90d3",
      "SIZE": 10577
    },
    {
      "NAME": "SESSION.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "083df1c366526f2dd207fc1c9301c6c6",
      "SIZE": 5159
    },
    {
      "NAME": "SESSION.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012842",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "9f582378f48657b909fd906d2593a638",
      "SIZE": 17267
    },
    {
      "NAME": "SESSION.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "f01570a71ed88408709e2a44e578738c",
      "SIZE": 1754
    }
  ]
}