{
  "SOURCE": "SIZET.lss",
  "COMMENT": "SIZET module",
  "ARTIFACTS": [
    "SIZET.INC",
    "SIZET.html",
    "SIZET.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SIZEL",
  "DEPENDS": [
    "SIZEA"
  ],
  "INSTALL": [
    {
      "TARGET": "SIZET.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SIZET.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SIZET.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SIZET.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SIZET.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SIZET.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SIZET.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394323",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "SIZET.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "600",
      "LOCATION": "FILE"
    },
    {
      "NAME": "SIZET.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402397367",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "SIZET.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394511",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}