{
  "SOURCE": "SLOAD.lss",
  "COMMENT": "SLOAD module",
  "ARTIFACTS": [
    "SLOAD.INC",
    "SLOAD.html",
    "SLOAD.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SLOAD",
  "DEPENDS": [
    "CRACK",
    "HOST",
    "TRIMB"
  ],
  "INSTALL": [
    {
      "TARGET": "SLOAD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SLOAD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SLOAD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SLOAD.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SLOAD.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SLOAD.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SLOAD.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012751",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "dd6340a2434acf0b8de04ec290a54736",
      "SIZE": 5072
    },
    {
      "NAME": "SLOAD.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "eb2d5e48d644cb3b94855f8509cd3c24",
      "SIZE": 4701
    },
    {
      "NAME": "SLOAD.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012823",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "50119a063037c3a07ab1a24d3528744a",
      "SIZE": 8391
    },
    {
      "NAME": "SLOAD.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012780",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "ec9ff553cb1861785441cd151859b98f",
      "SIZE": 140
    }
  ]
}