{
  "SOURCE": "SOUNDEX.lss",
  "COMMENT": "SOUNDEX module",
  "ARTIFACTS": [
    "SOUNDEX.INC",
    "SOUNDEX.html",
    "SOUNDEX.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SOUNDEX",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "SOUNDEX.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SOUNDEX.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SOUNDEX.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SOUNDEX.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SOUNDEX.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SOUNDEX.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SOUNDEX.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012752",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "8752041bae223c12cfed5396f976f6bc",
      "SIZE": 2171
    },
    {
      "NAME": "SOUNDEX.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "1bb5d6990d69c96f75d6ca2b10be5c67",
      "SIZE": 1878
    },
    {
      "NAME": "SOUNDEX.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012824",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "973ca38df4de53c70ccdae702f4bf61e",
      "SIZE": 4399
    },
    {
      "NAME": "SOUNDEX.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "c2acb6c49727373942ea3d1030adc331",
      "SIZE": 216
    }
  ]
}