{
  "SOURCE": "SPELL.lss",
  "COMMENT": "SPELL module",
  "ARTIFACTS": [
    "SPELL.INC",
    "SPELL.html",
    "SPELL.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SPELL",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "SPELL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SPELL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SPELL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SPELL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SPELL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SPELL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SPELL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012752",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "b4eb38a8a7a6e3e115f48de37b43bfb8",
      "SIZE": 2639
    },
    {
      "NAME": "SPELL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "532410bf3e748b2b936672b94fccfedb",
      "SIZE": 2321
    },
    {
      "NAME": "SPELL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012825",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "951701ba61babfa086f7fc0dd708de6d",
      "SIZE": 5048
    },
    {
      "NAME": "SPELL.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "b25e745c0d8a62057d3326b5c5fdbcf3",
      "SIZE": 139
    }
  ]
}