{
  "SOURCE": "STROUT.lss",
  "COMMENT": "STROUT module",
  "ARTIFACTS": [
    "STROUT.INC",
    "STROUT.html",
    "STROUT.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "STROUT",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "STROUT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STROUT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STROUT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "STROUT.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STROUT.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STROUT.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "STROUT.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012753",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "62ad8bba81dc4caaffc538d76331e11f",
      "SIZE": 1787
    },
    {
      "NAME": "STROUT.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "666a2ace11834646376a7180c3ae797c",
      "SIZE": 1380
    },
    {
      "NAME": "STROUT.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012827",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "260ab448a6f1226bc205bbaa430d73a7",
      "SIZE": 4043
    },
    {
      "NAME": "STROUT.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "43670dcf782fc98e578f4aa71e480ab6",
      "SIZE": 141
    }
  ]
}