{
  "SOURCE": "SYSTEM.lss",
  "COMMENT": "SYSTEM module",
  "ARTIFACTS": [
    "SYSTEM.INC",
    "SYSTEM.html",
    "SYSTEM.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "SYSTEM",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "SYSTEM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SYSTEM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SYSTEM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "SYSTEM.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SYSTEM.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "SYSTEM.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "SYSTEM.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012754",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "4cf0b60af53e1e29bd60554dea95ac7f",
      "SIZE": 4226
    },
    {
      "NAME": "SYSTEM.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "6127c2c4633aab9d62ab64a9b12595ab",
      "SIZE": 3424
    },
    {
      "NAME": "SYSTEM.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012828",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "5365b8e983c59355359e168cef612a7c",
      "SIZE": 7504
    },
    {
      "NAME": "SYSTEM.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "96225b3c6fa6882c05dcd9b3b193f8be",
      "SIZE": 142
    }
  ]
}