{
  "SOURCE": "STCL.lss",
  "COMMENT": "STCL module",
  "ARTIFACTS": [
    "STCL.INC",
    "STCL.html",
    "STCL.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TCL",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "STCL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STCL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STCL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "STCL.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STCL.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "STCL.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "STCL.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012753",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e990377a6ac4c4f74d526d0ff6470446",
      "SIZE": 4082
    },
    {
      "NAME": "STCL.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "1a4a781bdedc6bca0dd8ba7222605080",
      "SIZE": 2548
    },
    {
      "NAME": "STCL.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012826",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "8cad07c8eed411f31c2e7017c9effdb7",
      "SIZE": 7117
    },
    {
      "NAME": "STCL.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "cf24a51a69bd39cd1f90a0bfdafc0f80",
      "SIZE": 1453
    }
  ]
}