{
  "SOURCE": "TIME.lss",
  "COMMENT": "TIME module",
  "ARTIFACTS": [
    "TIME.INC",
    "TIME.html",
    "TIME.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TIME",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "TIME.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "TIME.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "TIME.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012755",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "695140fe353c93408c4ec0e7732c81f3",
      "SIZE": 3023
    },
    {
      "NAME": "TIME.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "f31d7f063b61ddf044739f0d3108607a",
      "SIZE": 2803
    },
    {
      "NAME": "TIME.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012830",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "6ea1238d7867d5098d908645ae1d47fd",
      "SIZE": 5768
    },
    {
      "NAME": "TIME.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "533e224da2a0ef44ba715dcac79b3a86",
      "SIZE": 137
    }
  ]
}