{
  "SOURCE": "TIME.lss",
  "COMMENT": "TIME module",
  "ARTIFACTS": [
    "TIME.INC",
    "TIME.html",
    "TIME.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TIME",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "TIME.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "TIME.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIME.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "TIME.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012755",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIME.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIME.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012830",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIME.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}