{
  "SOURCE": "TIMEGC.lss",
  "COMMENT": "TIMEGC module",
  "ARTIFACTS": [
    "TIMEGC.INC",
    "TIMEGC.html",
    "TIMEGC.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TIMEGC",
  "DEPENDS": [
    "LINK",
    "RESOL",
    "SYSTEM"
  ],
  "INSTALL": [
    {
      "TARGET": "TIMEGC.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "TIMEGC.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "TIMEGC.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012755",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "328d0cc7928bc377db25e9a992ac83fd",
      "SIZE": 2905
    },
    {
      "NAME": "TIMEGC.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "701be2d4e34530df923dc72917c72a67",
      "SIZE": 2352
    },
    {
      "NAME": "TIMEGC.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012829",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "de92cad51e4bf96b0501bdf54d300ea1",
      "SIZE": 5282
    },
    {
      "NAME": "TIMEGC.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "478b66433ddc164b54038136a96a16d5",
      "SIZE": 212
    }
  ]
}