{
  "SOURCE": "TIMEGC.lss",
  "COMMENT": "TIMEGC module",
  "ARTIFACTS": [
    "TIMEGC.INC",
    "TIMEGC.html",
    "TIMEGC.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TIMEGC",
  "DEPENDS": [
    "LINK",
    "RESOL",
    "SYSTEM"
  ],
  "INSTALL": [
    {
      "TARGET": "TIMEGC.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "TIMEGC.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TIMEGC.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "TIMEGC.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012755",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIMEGC.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIMEGC.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012829",
      "ACCESS": "664",
      "LOCATION": "FILE"
    },
    {
      "NAME": "TIMEGC.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE"
    }
  ]
}