{
  "SOURCE": "TRIMB.lss",
  "COMMENT": "TRIMB module",
  "ARTIFACTS": [
    "TRIMB.INC",
    "TRIMB.html",
    "TRIMB.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "TRIMB",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "TRIMB.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TRIMB.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TRIMB.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "TRIMB.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TRIMB.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "TRIMB.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "TRIMB.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012756",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "3850706da3c641cf879b3440b96be74f",
      "SIZE": 1595
    },
    {
      "NAME": "TRIMB.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "81bea9ee22307dc23a9b931c9c123e9d",
      "SIZE": 1238
    },
    {
      "NAME": "TRIMB.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012835",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "16a56cf1b87f6a87e928b6a426f24f41",
      "SIZE": 3839
    },
    {
      "NAME": "TRIMB.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "f4bd8e4ee009bcde5fe19c7a2e0f95eb",
      "SIZE": 214
    }
  ]
}