{
  "SOURCE": "uban.lss",
  "COMMENT": "uban module",
  "ARTIFACTS": [
    "uban",
    "uban.html"
  ],
  "TYPE": "PROGRAM",
  "NAME": "UBAN",
  "DEPENDS": [
    "CRACK",
    "SEQ",
    "TRIMB"
  ],
  "INSTALL": [
    {
      "TARGET": "uban",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "uban.html",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "uban",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "uban.html",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "uban.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012756",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "adaea53b57568383ec0f933e86a831fa",
      "SIZE": 6902
    },
    {
      "NAME": "uban",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402394875",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "8de2054c3b1485e0b2a8c1577672a2b4",
      "SIZE": 6484
    },
    {
      "NAME": "uban.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012832",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "863fd57da86def60ea7b9a78df7c1a4f",
      "SIZE": 9536
    }
  ]
}