#!/usr/bin/bash
 exec "snobol4" "-b" "$0" "$@"
 
* upinc
*
* Update include section of source. Requires lss input file to
* determine includes section and uses commentary to update. The
* file with the resultant program may be no extension (program)
* or INC file.

-include 'HOST.INC'
-include 'READFILE.INC'
-include 'BQ.INC'
-include 'JSON.INC'
-include 'CHARS.INC'
-include 'SEQ.INC'

 fn = host(HOST_ARGN, HOST(HOST_FIRSTARG)) :f(end)
 src = readfile(fn) :f(end)
 on = fn
 on '.lss' =
 obj = (readfile(on), readfile(on = on '.INC')) :f(end)
 inc = json_decode(bq('uses ' on)) :f(end)
 ld = ?(src ? '-' ('snocone' | 'SNOCONE')) '//'
 &fullscan = 1
 src '<H2>Uses</H2>' = '<h2>Uses</h2>'
 src '<h2>Uses</h2>' ((CHARS_NL @bh @eh CHARS_NL) |
+ (CHARS_NL @bh ARB CHARS_NL @eh CHARS_NL)) :f(tryi)
 dh = 1
tryi src '<<INCLUDES>>=' CHARS_NL @bi break('@') @ei '@' CHARS_NL
+ :f(noi)
 di = 1
noi q = "'"
 qq = '"'
 seq(' ni = ni ld "-INCLUDE " q inc<i> q CHARS_NL', .i)
 seq(' s = inc<i>; s ".INC" = ;'
+ ' nh = nh "<a href=" qq s ".html" qq ">" s "</a><br>" CHARS_NL;'
+ ' inc<i>', .i)
 src differ(di) pos(bi) len(ei - bi) = ni
 src differ(dh) pos(bh) len(eh - bh) = nh
 writefile(fn, src)
end
