{
  "SOURCE": "UTF8.lss",
  "COMMENT": "UTF8 module",
  "ARTIFACTS": [
    "UTF8.INC",
    "UTF8.html",
    "UTF8.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "UTF8",
  "DEPENDS": [
  ],
  "INSTALL": [
    {
      "TARGET": "UTF8.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "UTF8.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "UTF8.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "UTF8.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "UTF8.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "UTF8.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "UTF8.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012757",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "c5c1d5cd2e21916db1366e029bd4ccec",
      "SIZE": 8780
    },
    {
      "NAME": "UTF8.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012776",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "050978bd7b4fe0608e15ccc2042e6d72",
      "SIZE": 8471
    },
    {
      "NAME": "UTF8.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012833",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "bbea48ea435b5114e4d7770e061b4479",
      "SIZE": 16296
    },
    {
      "NAME": "UTF8.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012781",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "6d47a6e9345b957e2dc056cdc8d6edff",
      "SIZE": 138
    }
  ]
}