{
  "SOURCE": "VDIFFER.lss",
  "COMMENT": "VDIFFER module",
  "ARTIFACTS": [
    "VDIFFER.INC",
    "VDIFFER.html",
    "VDIFFER.tst"
  ],
  "TYPE": "MODULE",
  "NAME": "VDIFFER",
  "DEPENDS": [
    "SYSTEM"
  ],
  "INSTALL": [
    {
      "TARGET": "VDIFFER.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "VDIFFER.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "VDIFFER.tst",
      "COMMANDS": [
      ]
    }
  ],
  "BUILD": [
    {
      "TARGET": "VDIFFER.INC",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "VDIFFER.html",
      "COMMANDS": [
      ]
    },
    {
      "TARGET": "VDIFFER.tst",
      "COMMANDS": [
      ]
    }
  ],
  "FILES": [
    {
      "NAME": "VDIFFER.lss",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012758",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "d047950bb7a8042916b201845d837abf",
      "SIZE": 1674
    },
    {
      "NAME": "VDIFFER.INC",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012771",
      "ACCESS": "644",
      "LOCATION": "FILE",
      "MD5": "e68e28e10908999de18db62fddf0eeed",
      "SIZE": 1370
    },
    {
      "NAME": "VDIFFER.html",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012846",
      "ACCESS": "664",
      "LOCATION": "FILE",
      "MD5": "42ba54d37d87a4e7a6e40b5dcd48bd21",
      "SIZE": 3866
    },
    {
      "NAME": "VDIFFER.tst",
      "TYPE": "TEXT",
      "TIMESTAMP": "1402012782",
      "ACCESS": "775",
      "LOCATION": "FILE",
      "MD5": "91361e14b910886ffc5af596fded6bdf",
      "SIZE": 143
    }
  ]
}